/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/**
 * Coming-Soon Infrastructure
 *
 * Exposes the runtime-warner API (consumed by `src/index.ts:start()`) and
 * the committed registry of coming-soon Effect Schema names + variant
 * discriminators (regenerated by `bun run progress`).
 *
 * Privacy invariant: nothing in this module reads the gitignored internal
 * manifest at `schemas/.coming-soon.internal.json`. The public surface is
 * limited to schema names and discriminator tags — no spec IDs, no
 * user-story paths.
 */

export {
  detectComingSoonUsages,
  formatComingSoonWarning,
  warnForConfig,
  type ComingSoonUsage,
} from './coming-soon-warner'
export {
  COMING_SOON_DISCRIMINATORS,
  COMING_SOON_LEAF_SCHEMA_TAGS,
  COMING_SOON_SCHEMA_NAMES,
  COMING_SOON_TAGS,
} from './registry.generated'
