/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */
// GENERATED FILE — regenerated by `bun run progress`. DO NOT EDIT.

/**
 * Effect Schema names whose ENTIRE schema file is currently fixme-only.
 * Used by the runtime warner for whole-feature detection (no discriminated
 * variants involved). Example: `AiTranslateFieldSchema`.
 */
export const COMING_SOON_SCHEMA_NAMES: ReadonlySet<string> = new Set([
  'AgentActionSchema',
  'AgentApprovalEscalationSchema',
  'AgentApprovalSchema',
  'AgentCapabilitiesSchema',
  'AgentDefinitionSchema',
  'AgentKnowledgeSchema',
  'AgentLimitsSchema',
  'AgentMemorySchema',
  'AgentPermissionsSchema',
  'AgentScheduleSchema',
  'AgentSchema',
  'AgentsSchema',
  'AiAgentActionSchema',
  'AnalyticsActionSchema',
  'AnalyticsTrackActionSchema',
  'AntiSpamSchema',
  'ApprovalActionSchema',
  'ApprovalRequestActionSchema',
  'AuthAssignRoleActionSchema',
  'AuthBanUserActionSchema',
  'AuthCreateUserActionSchema',
  'AuthTriggerSchema',
  'AuthUnbanUserActionSchema',
  'BaseFieldSchema',
  'BucketPermissionsSchema',
  'CommentsComponentSchema',
  'CommentsConfigSchema',
  'ComponentSearchSchema',
  'CryptoActionSchema',
  'CryptoHashActionSchema',
  'CryptoHmacActionSchema',
  'CustomFieldSchema',
  'DigestActionSchema',
  'DigestCollectActionSchema',
  'DigestReleaseActionSchema',
  'FileCompressActionSchema',
  'FileExtractTextActionSchema',
  'FileGenerateCsvActionSchema',
  'FileGeneratePdfActionSchema',
  'FileTransformImageActionSchema',
  'FormAccessSchema',
  'FormAnalyticsSchema',
  'FormAvailabilitySchema',
  'FormDisplaySchema',
  'FormFieldGroupSchema',
  'LanguageCodeSchema',
  'LanguagesSchema',
  'ListDisplaySchema',
  'ListItemMetadataSchema',
  'ListItemTemplateSchema',
  'NotificationBellSchema',
  'NotificationSchema',
  'RateLimitSchema',
  'RecordDeleteActionSchema',
  'RecordUpsertActionSchema',
  'SearchWeightSchema',
  'SendNotificationActionSchema',
  'ShareOptionsSchema',
  'StateActionSchema',
  'StateDeleteActionSchema',
  'StateGetActionSchema',
  'StateIncrementActionSchema',
  'StateListActionSchema',
  'StateSetActionSchema',
  'SubmitterOptionsSchema',
])

/**
 * Map from parent union schema name to the set of discriminator tags
 * that are individually fixme. Used by the runtime warner to flag only
 * specific union variants (e.g. `'kanban'` inside `PageComponentSchema`)
 * without blanket-deprecating the parent type.
 */
export const COMING_SOON_DISCRIMINATORS: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  [
    'ComponentSchema',
    new Set([
      'avatar-group',
      'kpi',
      'number-input',
      'progress',
      'reorderable-list',
      'status-indicator',
      'tags',
      'time-picker',
      'timeline',
      'wizard',
    ]),
  ],
])

/**
 * Flattened union of all coming-soon discriminator tags across parents.
 * Pre-computed for fast runtime lookup before scanning the parent map.
 */
export const COMING_SOON_TAGS: ReadonlySet<string> = new Set([
  'avatar-group',
  'kpi',
  'number-input',
  'progress',
  'reorderable-list',
  'status-indicator',
  'tags',
  'time-picker',
  'timeline',
  'wizard',
])

/**
 * Auto-derived map from `Schema.Literal('xxx')` discriminator value to
 * the specific `*Schema` (within `COMING_SOON_SCHEMA_NAMES`) that
 * declares it. Used by the runtime warner for whole-file detection — when
 * a runtime `type: 'xxx'` value isn't covered by
 * `COMING_SOON_DISCRIMINATORS`, this map provides the schema name for
 * the legacy whole-file warning format.
 *
 * Replaces the hand-curated `TAG_TO_SCHEMA_NAME` from earlier commits;
 * derived directly from the manifest so the mapping never drifts.
 */
export const COMING_SOON_LEAF_SCHEMA_TAGS: ReadonlyMap<string, string> = new Map([
  ['analytics', 'AnalyticsTrackActionSchema'],
  ['approval', 'ApprovalRequestActionSchema'],
  ['notification', 'SendNotificationActionSchema'],
])
