/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/**
 * Delete the browser screenshots older than the retention period
 * (`BROWSER_ARTIFACT_RETENTION_DAYS`, 30 days by default).
 *
 * A screenshot's age is its RUN's: every picture a run kept sits under
 * `browser-runs/<run id>/` (`browser-artifact-service.ts`), whatever bucket the
 * run wrote it to, and the run's start is when the browser saw the page. A run
 * that records neither a start nor an end is aged by the picture's own stored
 * time instead, so every picture expires.
 *
 * Only a picture a run made is deleted, never another object a person stored
 * under the same prefix in a declared bucket: a key the run records in its
 * steps, or — for a run that no longer exists, or whose values were erased —
 * an object the storage catalog records as generated by an automation with
 * nobody as its uploader.
 *
 * This sweep is also the erasure control of those pictures (S5): a run's
 * artifacts carry no uploader, so they cannot be traced to a person beyond
 * what the run itself records, and nothing outlives the retention period.
 *
 * Run every day and once at start-up by `register-browser-artifact-sweep.ts`,
 * and on demand by the token-gated
 * `POST /api/internal/automations/sweep-browser-artifacts`.
 */

import { Clock, Effect } from 'effect'
import { AutomationRunRepository } from '@/application/ports/repositories/automations/automation-run-repository'
import {
  StorageService,
  UNATTRIBUTED_BUCKET,
  type BucketBinding,
  type StorageError,
} from '@/application/ports/services/storage-service'
import {
  BROWSER_ARTIFACT_PREFIX,
  runIdOfArtifactKey,
} from '@/domain/models/app/automations/actions/browser/browser-artifact-service'
import { logError } from '@/infrastructure/logging/logger'
import type { AutomationRunDatabaseError } from '@/application/ports/repositories/automations/automation-run-repository'

const DAY_MS = 86_400_000

/** What the sweep knows of one run's pictures. */
interface RunPictures {
  /** When the run started (or ended), in ms, or `undefined` when it records neither. */
  readonly ageMs: number | undefined
  /** The keys its steps record, or `undefined` when the run no longer records them. */
  readonly recorded: ReadonlySet<string> | undefined
}

/**
 * Every picture key of the run `runId` written anywhere in `value` — an object,
 * or the JSON text a dialect stores it as. A key is `browser-artifact-service`'s
 * shape exactly, so the text search reads nothing else.
 */
const keysUnder = (value: unknown, runId: string): readonly string[] => {
  const prefix = `${BROWSER_ARTIFACT_PREFIX}${runId}/`.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return JSON.stringify(value).match(new RegExp(`${prefix}\\d+-[\\w-]+\\.png`, 'g')) ?? []
}

/** The run's age and the picture keys its steps record. */
const runPictures = (runId: string) =>
  Effect.gen(function* () {
    const runs = yield* AutomationRunRepository
    const run = yield* runs.findById(runId)
    if (run === undefined) return { ageMs: undefined, recorded: undefined } satisfies RunPictures
    const started = Date.parse(run.startedAt ?? run.completedAt ?? '')
    const ageMs = Number.isFinite(started) ? started : undefined
    if (run.valuesErasedAt !== null) return { ageMs, recorded: undefined } satisfies RunPictures
    const steps = yield* runs.findStepsByRunId(runId)
    const recorded = new Set(steps.flatMap((step) => keysUnder([step.output, step.nested], runId)))
    return { ageMs, recorded } satisfies RunPictures
  })

/** The catalog's word on a key: its bucket, its stored time, and whether an automation made it. */
type Catalog =
  | {
      readonly bucket: BucketBinding
      readonly storedMs: number
      readonly generated: boolean
    }
  | undefined

const catalogOf = (key: string) =>
  Effect.gen(function* () {
    const storage = yield* StorageService
    const meta = yield* Effect.result(storage.getMetadata(key, UNATTRIBUTED_BUCKET))
    if (meta._tag === 'Failure') return undefined satisfies Catalog
    const { bucket, lastModified, generatedBy, uploadedBy } = meta.success
    const catalog: Catalog = {
      bucket: bucket ?? UNATTRIBUTED_BUCKET,
      storedMs: Date.parse(lastModified),
      generated: generatedBy !== undefined && uploadedBy === undefined,
    }
    return catalog
  })

/** Whether a picture is the run's, and older than `cutoffMs`. */
const isExpired = (key: string, run: RunPictures, catalog: Catalog, cutoffMs: number): boolean => {
  const made = run.recorded === undefined ? catalog?.generated === true : run.recorded.has(key)
  const ageMs = run.ageMs ?? catalog?.storedMs
  return made && ageMs !== undefined && Number.isFinite(ageMs) && ageMs < cutoffMs
}

/** The bucket of a picture to delete, or `undefined` to keep it. */
const bucketIfExpired = (key: string, run: RunPictures, cutoffMs: number) =>
  Effect.gen(function* () {
    if (run.recorded !== undefined && !run.recorded.has(key)) return undefined
    const catalog = yield* catalogOf(key)
    return isExpired(key, run, catalog, cutoffMs)
      ? (catalog?.bucket ?? UNATTRIBUTED_BUCKET)
      : undefined
  })

/** Delete one stored picture from the bucket that holds it. Answers whether it did. */
const deleteArtifact = (key: string, bucket: BucketBinding) =>
  Effect.gen(function* () {
    const storage = yield* StorageService
    yield* storage['delete'](key, bucket)
    return true
  }).pipe(
    Effect.tapCause((cause) =>
      Effect.sync(() => logError('[browser-artifacts] a screenshot could not be deleted', cause))
    ),
    // effect-swallow: logged above; one picture that cannot be deleted must not keep the others, and the next sweep tries again.
    Effect.catchCause(() => Effect.succeed(false))
  )

/** Delete every browser screenshot older than `retentionDays`. Answers the keys deleted. */
export const sweepBrowserArtifacts = (
  retentionDays: number
): Effect.Effect<
  readonly string[],
  StorageError | AutomationRunDatabaseError,
  StorageService | AutomationRunRepository
> =>
  Effect.gen(function* () {
    const storage = yield* StorageService
    const cutoffMs = (yield* Clock.currentTimeMillis) - retentionDays * DAY_MS
    const keys = yield* storage.list(BROWSER_ARTIFACT_PREFIX)
    const runIds = [...new Set(keys.map(runIdOfArtifactKey).filter((id) => id !== undefined))]
    const runs = new Map(
      yield* Effect.forEach(runIds, (runId) =>
        runPictures(runId).pipe(Effect.map((run) => [runId, run] as const))
      )
    )
    const deleted = yield* Effect.forEach(keys, (key) =>
      Effect.gen(function* () {
        const run = runs.get(runIdOfArtifactKey(key) ?? '')
        const bucket = run === undefined ? undefined : yield* bucketIfExpired(key, run, cutoffMs)
        if (bucket === undefined) return undefined
        return (yield* deleteArtifact(key, bucket)) ? key : undefined
      })
    )
    return deleted.filter((key): key is string => key !== undefined)
  }).pipe(Effect.withSpan('automations.sweep-browser-artifacts'))
