/**
 * Copyright (c) 2025 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/**
 * Common SQL/formula keywords and functions that should be excluded from field references.
 * This list includes SQL keywords, operators, functions, and data types that are part of
 * the PostgreSQL SQL syntax and should not be treated as field names when parsing formulas.
 *
 * Defined as a constant to avoid recreating the Set on every function call.
 * Exported from a separate module to reduce main table index file size.
 */
export const FORMULA_KEYWORDS = new Set([
  // SQL keywords
  'as',
  'from',
  'where',
  'on',
  'join',
  'left',
  'right',
  'inner',
  'outer',
  'distinct',
  'all',
  'any',
  'some',
  'between',
  'in',
  'like',
  'ilike',
  'is',
  'to',
  'for',
  'with',
  'desc',
  'asc',
  'by',
  'order',
  'group',
  'having',
  'limit',
  'offset',
  // Logical operators
  'if',
  'then',
  'else',
  'and',
  'or',
  'not',
  // Boolean literals
  'true',
  'false',
  'null',
  // Control flow
  'case',
  'when',
  'end',
  // String functions
  'concat',
  'upper',
  'lower',
  'trim',
  'length',
  'substr',
  'substring',
  'replace',
  'overlay',
  'repeat',
  'strpos',
  'string_to_array',
  'array_to_string',
  'chr',
  'ascii',
  'encode',
  'decode',
  'initcap',
  'placing',
  // Math functions
  'round',
  'ceil',
  'floor',
  'abs',
  'power',
  'sqrt',
  'mod',
  'greatest',
  'least',
  'exp',
  'trunc',
  'log',
  'ln',
  'sign',
  // Aggregate functions
  'sum',
  'avg',
  'max',
  'min',
  'count',
  'counta',
  'countall',
  // Date/time functions
  'current_date',
  'current_time',
  'current_timestamp',
  'now',
  'extract',
  'date_add',
  'date_sub',
  'date_diff',
  'date_trunc',
  'to_char',
  'to_date',
  'to_timestamp',
  'age',
  'year',
  'month',
  'day',
  'hour',
  'minute',
  'second',
  // Type conversions
  'cast',
  'coalesce',
  'nullif',
  // Data types
  'numeric',
  'integer',
  'int',
  'decimal',
  'text',
  'varchar',
  'char',
  'boolean',
  'bool',
  'date',
  'timestamp',
  'timestamptz',
  'time',
  'interval',
  'bytea',
  // Array functions
  'array',
  'array_length',
  'array_remove',
  'cardinality',
  'arrayunique',
  'unnest',
  'flatten',
  // Regex functions
  'regexp_match',
  'regexp_replace',
  // Binary/encoding functions
  'convert_from',
  // Date part keywords
  'dow',
  'week',
  'doy',
  'epoch',
  'isodow',
  'isoweek',
  'isoyear',
  'julian',
  'quarter',
  'timezone',
  // SQL statement keywords
  'select',
])
