/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/**
 * The accessibility FLOOR — the classes applied AFTER an operator's
 * `design.components` block so that block cannot remove them.
 *
 * ## Why a floor exists at all
 *
 * `design.components` is the first surface that lets one declaration restyle
 * every instance of an engine type across an app. A class list that zeroes the keyboard focus
 * ring is legal, an entirely plausible thing to write while tuning a button,
 * and the single most damaging class an operator can ship: a keyboard user
 * simply loses the page. So the operator's classes are a LAYER, not the last
 * word — `resolveClasses(defaults, app, author, floor)` puts this string last.
 *
 * ## What is in it, and why it is not more
 *
 * Each entry is the recipe's OWN accessibility block, imported rather than
 * copied, and replayed. That is the whole design, and it is what makes the
 * floor free:
 *
 *  - an app that declares no `design.components` block gets no floor at all
 *    (see {@link componentFloorFor}'s contract with `resolve-component-classes`),
 *    so its rendered HTML, its candidate corpus and its compiled CSS are
 *    byte-identical to what they were before this key existed;
 *  - an app that DOES declare one gets classes the compiled stylesheet already
 *    contains, because the recipe emits the same tokens — so the floor can
 *    never be a class the CSS pipeline has not seen.
 *
 * Three things the jalon-2 brief lists that are deliberately NOT here, each for
 * a measured reason rather than an oversight:
 *
 *  - **A minimum hit target.** The button recipe sizes its heights at 28, 32
 *    and 40 px. A 44 px floor would change the rendered height of every button
 *    in every app — a design change with its own visual baselines, not a floor.
 *  - **`motion-reduce:*`.** `motion-reduce:` appears nowhere in `src/` today, so
 *    it is absent from the build-time candidate corpus: putting it in the floor
 *    would emit a class with no CSS behind it. It belongs with the recipes
 *    adopting it, which is the recipe consolidation, not this key.
 *  - **The disabled treatment.** The button recipe applies
 *    its disabled treatment UNPREFIXED and conditionally (`STATE_CLASS`), so a
 *    prefixed floor would be a second, differently-shaped mechanism for the same
 *    thing. It is also not an accessibility invariant: an operator retuning
 *    disabled opacity is making a legitimate design choice, and a floor that
 *    overruled them would be paternalism rather than protection.
 *
 * The colour/`-fg` pairing rule from the same brief is not expressible as a
 * class list at all — it is a cross-key VALIDATION (a background role must
 * carry its foreground counterpart) and belongs to `design-validation.ts`.
 *
 * ## Follow-up (named, not silent)
 *
 * The table is hand-written here rather than generated by
 * `scripts/build/generate-default-design.ts`. The jalon-1 source
 * (`src/admin/config/design.ts`) models CSS TOKEN declarations — `TokenDecl`,
 * `ValueSpec`, `--sv-*` custom properties — and has no notion of a Tailwind
 * recipe class list; carrying a `floor` sub-key there would mean a new section,
 * a new emitter and a new drift rule, well past the ~20 lines that would make
 * the generator the cheaper home. The floor's real source is the RECIPES, which
 * are themselves not yet generated. When the recipe consolidation lands, this
 * table is the thing it should absorb.
 *
 * ## A note on the prose here
 *
 * The build-time CSS candidate scan reads this file, comments included, and any
 * bare Tailwind-shaped token it finds becomes a candidate and therefore a rule
 * in EVERY app's stylesheet. The classes discussed above are described rather
 * than spelled for that reason: a doc comment must not silently widen the
 * compiled CSS.
 *
 * Four types carry a ROOT floor, and the boundary is precise: a type is in
 * `ROOT_FLOOR` when its recipe puts the focus affordance on the SAME element
 * that receives `className` — i.e. on the component root. Every other focusable
 * engine type paints its ring on an INNER part that no `className` reaches, so
 * flooring their root would be inert decoration. Those are served by the
 * per-part table instead, under the stricter entry rule documented on it.
 */

import { TOKENS as T, withVarFallback as v } from './css-var'

/**
 * The keyboard focus ring, composed from the SAME `css-var` tokens the recipes
 * compose it from.
 *
 * Not imported from them, and that is a boundary fact rather than a choice: a
 * `presentation-util` may reach neither a `presentation-island`
 * (`islands/recipes/shared-tokens-default-classes.ts`, where the island copy
 * lives) nor a `presentation-component`
 * (`ui/sections/renderers/element-renderers/recipes/*`, where the SSR copies
 * live), and widening that rule for a five-token string would be a much larger
 * permission than the need.
 *
 * So the string is re-composed here, and the drift risk that creates is closed
 * by a test rather than by a comment: `component-floor.test.ts` asserts that
 * every token below appears VERBATIM in the recipe output it is meant to
 * replay, and that every token is already a build-time CSS candidate. A
 * divergence fails a unit test rather than silently emitting a class the
 * stylesheet has never seen.
 */
const FOCUS_VISIBLE_RING = [
  'focus-visible:outline-none',
  'focus-visible:ring-2',
  'focus-visible:ring-offset-2',
  `focus-visible:ring-[${v('sv-focus-ring', T.focusRing)}]`,
  `focus-visible:ring-offset-[${v('sv-bg', T.bg)}]`,
].join(' ')

/** A link's focus affordance — an underline, not a ring. Same derivation rule. */
const LINK_FOCUS_CLASS = [
  'focus-visible:outline-none focus-visible:underline',
  `focus-visible:decoration-[${v('sv-focus-ring', T.focusRing)}]`,
].join(' ')

/**
 * Per-engine-type floor for the component ROOT.
 *
 * Keyed by engine component type. A type absent from this table has no floor,
 * which is the honest answer for the ~81 types whose root is not the focusable
 * element.
 */
const ROOT_FLOOR: Readonly<Record<string, string>> = {
  // `<button>` — the recipe's own `FOCUS_CLASS` is byte-identical to the shared
  // island token, which is why one constant serves both.
  button: FOCUS_VISIBLE_RING,
  // `<input>` / `<textarea>` — `computeInputDefaultClasses`' `FOCUS` block.
  input: FOCUS_VISIBLE_RING,
  textarea: FOCUS_VISIBLE_RING,
  // `<a>` — an underline rather than a ring; see `LINK_FOCUS_CLASS`.
  link: LINK_FOCUS_CLASS,
}

/**
 * Per-engine-type floor for the parts that are NOT the root.
 *
 * Keyed by engine component type, then by the part name an operator writes in
 * `design.components.<type>.parts.<part>`. It exists because the root floor
 * above covers only the types whose focusable element IS the root: a `select`
 * takes keyboard focus on its trigger, and an operator who writes
 * `parts.trigger`, `states.focusVisible.trigger` or `replace: true` could
 * delete that trigger's ring outright while the root floor watched the wrong
 * element.
 *
 * ## The entry rule, which is stricter than the root table's
 *
 * A part belongs here only when all three hold, and each has to be checked
 * against the island's REAL rendered DOM rather than against the schema:
 *
 *  1. the island renders an element for that exact part name;
 *  2. that element is the one that takes keyboard focus — not merely a wrapper
 *     around it, since a `focus-visible:` rule on a wrapper never fires;
 *  3. the part is reachable from `design.components`, i.e. the island reads it
 *     out of the serialised `designClasses` map. A part no island reads cannot
 *     be broken by an operator, so flooring it protects nothing.
 *
 * An entry keyed on a part that fails any of the three is dead config that
 * reads as coverage — worse than an honest absence, because the next reader
 * takes it for a guarantee.
 *
 * `select.trigger` is the only entry that passes today: it is Base UI's
 * `Select.Trigger`, the `role="combobox"` button that `plain-select.tsx`
 * renders and focuses, and whose own recipe emits a byte-identical ring (see
 * `select-default-classes.ts`, pinned by `component-floor.test.ts`).
 *
 * ## Named, not silent: what is still uncovered
 *
 * `checkbox`, `switch`, `date-picker`, `slider`, the overlays and the tab strip
 * all put focus on an inner element too, and none of them is here — because
 * none of their islands reads `designClasses` at all, so criterion 3 fails.
 * `tabs` reads the map but exposes only its list and panel parts, neither of
 * which takes focus; its tab triggers are unreachable. A searchable `select`
 * is the same shape one level down: it swaps the trigger for a combobox input
 * inside a group whose focus treatment is scoped to the GROUP rather than to
 * the focused element, so `trigger` does not name its focusable element there
 * and a floor pointed at it would be inert.
 *
 * Each of those becomes eligible the moment its island reads the part map —
 * and not before.
 */
const PART_FLOOR: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  select: { trigger: FOCUS_VISIBLE_RING },
}

/** Shared empty map, so an unfloored type costs no allocation per render. */
const NO_PART_FLOOR: Readonly<Record<string, string>> = {}

/**
 * The floor for one engine component type's root, or `''` when it has none.
 *
 * Returns a string rather than `undefined` so callers can concatenate without
 * branching; `resolveClasses` treats `''` as "no layer".
 *
 * @param type - The engine component type being rendered.
 * @returns The non-overridable class list for that type's root.
 */
export const componentFloorFor = (type: string): string => ROOT_FLOOR[type] ?? ''

/**
 * The floors for one engine component type's non-root parts, keyed by part.
 *
 * Empty rather than `undefined` for the same reason as above: callers index it
 * and treat a miss as "no layer".
 *
 * @param type - The engine component type being rendered.
 * @returns The non-overridable class list for each floored part of that type.
 */
export const componentPartFloorsFor = (type: string): Readonly<Record<string, string>> =>
  PART_FLOOR[type] ?? NO_PART_FLOOR

/** The engine types that carry a root floor, for tests and the console. */
export const FLOORED_COMPONENT_TYPES: readonly string[] = Object.keys(ROOT_FLOOR)

/** The engine types that carry a per-part floor, for tests and the console. */
export const PART_FLOORED_COMPONENT_TYPES: readonly string[] = Object.keys(PART_FLOOR)
