/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

import {
  AgentApprovalEscalationSchema,
  AgentApprovalSchema,
  AgentCapabilitiesSchema,
  AgentDefinitionSchema,
  AgentKnowledgeSchema,
  AgentLimitsSchema,
  AgentPermissionsSchema,
  AgentScheduleSchema,
} from '@/domain/models/app/agents'
import agentApprovalsBody from '@/domain/models/app/agents/agent-approvals.docs.md' with { type: 'file' }
import agentScheduleLimitsBody from '@/domain/models/app/agents/agent-schedule-limits.docs.md' with { type: 'file' }
import agentToolsBody from '@/domain/models/app/agents/agent-tools.docs.md' with { type: 'file' }
import aiAgentsBody from '@/domain/models/app/agents/ai-agents.docs.md' with { type: 'file' }
import aiChatBody from '@/domain/models/app/agents/ai-chat.docs.md' with { type: 'file' }
import aiEcoRoutingBody from '@/domain/models/app/agents/ai-eco-routing.docs.md' with { type: 'file' }
import aiMemoryBody from '@/domain/models/app/agents/ai-memory.docs.md' with { type: 'file' }
import aiOverviewBody from '@/domain/models/app/agents/ai-overview.docs.md' with { type: 'file' }
import aiProvidersBody from '@/domain/models/app/agents/ai-providers.docs.md' with { type: 'file' }
import aiRagBody from '@/domain/models/app/agents/ai-rag.docs.md' with { type: 'file' }
import { AgentMemorySchema } from '@/domain/models/app/agents/memory'
import { defineArticle, defineSection } from './define'

export const ai = defineSection({
  slug: 'ai',
  title: 'AI',
  order: 6000,
  tab: 'agents',
  articles: [
    defineArticle({
      slug: 'ai-overview',
      title: 'AI Overview',
      description:
        'The Sovrium AI ecosystem — providers, AI fields, conversational chat, autonomous agents, RAG knowledge, agent memory, and MCP interoperability — all driven by environment-variable configuration.',
      keywords: [
        'sovrium',
        'ai',
        'llm',
        'ai provider',
        'ai fields',
        'ai chat',
        'agents',
        'rag',
        'memory',
        'mcp',
        'model context protocol',
        'ollama',
        'anthropic',
        'openai',
      ],
      order: 6000,
      sidebarLabel: 'AI Overview',
      body: aiOverviewBody,
      documents: [],
      stories: [
        'US-AI-AGENTS-INERT-WITHOUT-PROVIDER',
        'US-AI-CONFIGURATION-001',
        'US-AI-CONFIGURATION-002',
        'US-AI-CONFIGURATION-009',
        'US-AI-CONFIGURATION-010',
        'US-AI-CONFIGURATION-011',
        'US-AI-CONFIGURATION-012',
      ],
    }),
    defineArticle({
      slug: 'ai-providers',
      title: 'AI Providers',
      description:
        'Configure the LLM and embedding backend via AI_PROVIDER / AI_API_KEY / AI_MODEL — Anthropic, OpenAI, Mistral, Google Gemini, local Ollama, or any OpenAI-compatible endpoint.',
      keywords: [
        'sovrium',
        'ai provider',
        'AI_PROVIDER',
        'AI_API_KEY',
        'AI_MODEL',
        'AI_BASE_URL',
        'anthropic',
        'openai',
        'mistral',
        'gemini',
        'google',
        'ollama',
        'openai-compatible',
        'embedding model',
        'speech-to-text',
        'STT_PROVIDER',
        'transcription',
      ],
      order: 6010,
      sidebarLabel: 'AI Providers',
      body: aiProvidersBody,
      documents: [],
      stories: [
        'US-AI-CONFIGURATION-003',
        'US-AI-CONFIGURATION-004',
        'US-AI-CONFIGURATION-006',
        'US-AI-SPEECH-TO-TEXT',
      ],
    }),
    defineArticle({
      slug: 'ai-eco-routing',
      title: 'AI Eco Routing',
      description:
        'ECO_AI_PROVIDER_PRECEDENCE routes AI calls local-first by default — prefer a reachable local Ollama model, fall back to the configured cloud provider — as a frugal-by-default platform property.',
      keywords: [
        'sovrium',
        'eco',
        'ecoconception',
        'ECO_AI_PROVIDER_PRECEDENCE',
        'local-first',
        'cloud-first',
        'local-only',
        'ollama',
        'ai routing',
        'frugal',
        'sustainability',
      ],
      order: 6020,
      sidebarLabel: 'AI Eco Routing',
      body: aiEcoRoutingBody,
      documents: [],
      stories: [
        'US-AI-CONFIGURATION-005',
        'US-AI-CONFIGURATION-007',
        'US-AI-CONFIGURATION-008',
        'US-AI-ECO-ROUTING',
      ],
    }),
    defineArticle({
      slug: 'ai-chat',
      title: 'AI Chat',
      description:
        'A conversational interface over your application data — query records, create/update/delete with confirmation, and trigger automations in natural language, all bounded by RBAC and logged in the activity stream.',
      keywords: [
        'sovrium',
        'ai chat',
        'conversational',
        'natural language',
        'ai-chat component',
        'tool calling',
        'streaming',
        'SSE',
        'rate limiting',
        'record queries',
        'record mutations',
        'trigger automations',
      ],
      order: 6030,
      sidebarLabel: 'AI Chat',
      body: aiChatBody,
      documents: [],
      stories: [
        'US-AI-CHAT-CONTEXT',
        'US-AI-CHAT-CROSS-001',
        'US-AI-CHAT-ERROR-HANDLING',
        'US-AI-CHAT-RATE-LIMITING',
        'US-AI-CHAT-RECORD-MUTATIONS',
        'US-AI-CHAT-RECORD-QUERIES',
        'US-AI-CHAT-STREAMING',
        'US-AI-CHAT-TOOL-CALLING',
        'US-AI-CHAT-TRIGGER-AUTOMATIONS',
      ],
    }),
  ],
})

export const agents = defineSection({
  slug: 'agents',
  title: 'Agents',
  order: 6200,
  tab: 'agents',
  articles: [
    defineArticle({
      slug: 'ai-agents',
      title: 'Agents Overview',
      description:
        'An agent is a virtual user bound to an auth role — what that model buys you, the identity properties every agent declares, and a complete example.',
      keywords: [
        'sovrium',
        'ai agents',
        'agent-as-user',
        'virtual user',
        'systemPrompt',
        'instructions',
        'auth role',
        'agents.sovrium.local',
        'multi-agent',
      ],
      order: 6200,
      sidebarLabel: 'Agents Overview',
      body: aiAgentsBody,
      documents: [AgentDefinitionSchema],
      stories: [
        'US-AI-AGENTS-CROSS-CUTTING',
        'US-AI-AGENTS-DEFINITION-001',
        'US-AI-AGENTS-DEFINITION-002',
        'US-AI-AGENTS-PERMISSIONS',
      ],
    }),
    defineArticle({
      slug: 'agent-tools',
      title: 'Agent Tools',
      description:
        'The tables and actions an agent may touch — the full action vocabulary, and the double gate that means an allowlist can only ever narrow a role.',
      keywords: [
        'sovrium',
        'agent tools',
        'double gate',
        'allowlist',
        'record.read',
        'record.list',
        'state.set',
        'http.request',
        'code.runTypescript',
        'email.send',
        'auth.createUser',
      ],
      order: 6205,
      sidebarLabel: 'Tools',
      body: agentToolsBody,
      documents: [AgentCapabilitiesSchema],
      stories: ['US-AI-AGENTS-TOOLS'],
    }),
    defineArticle({
      slug: 'agent-approvals',
      title: 'Agent Permissions & Approval',
      description:
        'Who may invoke an agent, and which of its actions stop for a human first — approval modes, expiry timeouts, and escalation to another role.',
      keywords: [
        'sovrium',
        'agent approval',
        'human-in-the-loop',
        'approval mode',
        'selective',
        'escalation',
        'timeout',
        'agent permissions',
        'trigger',
        'permissions.trigger',
        'agent 404',
        'anti-enumeration',
      ],
      order: 6210,
      sidebarLabel: 'Permissions & Approval',
      body: agentApprovalsBody,
      documents: [AgentPermissionsSchema, AgentApprovalSchema, AgentApprovalEscalationSchema],
      stories: ['US-AI-AGENTS-APPROVAL'],
    }),
    defineArticle({
      slug: 'agent-schedule-limits',
      title: 'Agent Scheduling & Limits',
      description:
        'Make an agent run unprompted on a cron interval, and cap what it can consume when it does — actions per minute, tokens per day, concurrent tasks.',
      keywords: [
        'sovrium',
        'agent schedule',
        'cron',
        'timezone',
        'taskPrompt',
        'agent limits',
        'maxActionsPerMinute',
        'maxTokensPerDay',
        'maxConcurrentTasks',
        'schedule trigger',
        'scheduled agent run',
      ],
      order: 6215,
      sidebarLabel: 'Scheduling & Limits',
      body: agentScheduleLimitsBody,
      documents: [AgentScheduleSchema, AgentLimitsSchema],
      stories: ['US-AI-AGENTS-LIMITS', 'US-AI-AGENTS-SCHEDULE'],
    }),
    defineArticle({
      slug: 'ai-rag',
      title: 'AI RAG',
      description:
        'Retrieval-augmented generation — ground agents and chat in your tables and documents via vector embeddings, semantic search, per-agent knowledge scoping, and dialect-aware storage (pgvector or SQLite BLOB).',
      keywords: [
        'sovrium',
        'rag',
        'retrieval augmented generation',
        'embeddings',
        'pgvector',
        'sqlite rag',
        'vector search',
        'knowledge base',
        'table knowledge',
        'document knowledge',
        'chunking',
        'similarity',
        'AI_KNOWLEDGE_DIR',
      ],
      order: 6230,
      sidebarLabel: 'AI RAG',
      body: aiRagBody,
      documents: [AgentKnowledgeSchema],
      stories: [
        'US-AI-RAG-CROSS-001',
        'US-AI-RAG-DOCUMENT-KNOWLEDGE',
        'US-AI-RAG-EMBEDDING',
        'US-AI-RAG-PHASE-2-SQLITE-VECTOR-ACCELERATION',
        'US-AI-RAG-SQLITE-RAG',
        'US-AI-RAG-TABLE-KNOWLEDGE',
      ],
    }),
    defineArticle({
      slug: 'ai-memory',
      title: 'AI Memory',
      description:
        'Agent memory in two tiers — RAG-backed knowledge retrieval and persistent AI-managed facts with namespace isolation and per-user scoping.',
      keywords: [
        'sovrium',
        'ai memory',
        'agent memory',
        'knowledge memory',
        'facts memory',
        'namespace isolation',
        'retrievalLimit',
        'similarityThreshold',
        'maxFacts',
        'per-user scoping',
      ],
      order: 6240,
      sidebarLabel: 'AI Memory',
      body: aiMemoryBody,
      documents: [AgentMemorySchema],
      stories: [
        'US-AI-MEMORY-CONVERSATION-HISTORY',
        'US-AI-MEMORY-CROSS-001',
        'US-AI-MEMORY-FACTS-MEMORY',
        'US-AI-RAG-PER-AGENT-KNOWLEDGE',
      ],
    }),
  ],
})
