/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

import {
  AiActionSchema,
  AnalyticsTrackActionSchema,
  AuthActionSchema,
  EmailSendActionSchema,
  FileActionSchema,
  HttpActionSchema,
  LinkActionSchema,
  RecordActionSchema,
  WebhookActionSchema,
} from '@/domain/models/app/automations/actions'
import automationAiActionsBody from '@/domain/models/app/automations/actions/ai-actions.docs.md' with { type: 'file' }
import automationAuthActionsBody from '@/domain/models/app/automations/actions/auth-actions.docs.md' with { type: 'file' }
import { DocumentActionSchema } from '@/domain/models/app/automations/actions/document'
import automationDocumentActionsBody from '@/domain/models/app/automations/actions/document-actions.docs.md' with { type: 'file' }
import automationEmailActionsBody from '@/domain/models/app/automations/actions/email-analytics-actions.docs.md' with { type: 'file' }
import automationFileActionsBody from '@/domain/models/app/automations/actions/file-actions.docs.md' with { type: 'file' }
import automationHttpActionsBody from '@/domain/models/app/automations/actions/http-webhook-actions.docs.md' with { type: 'file' }
import automationLinkActionsBody from '@/domain/models/app/automations/actions/link-actions.docs.md' with { type: 'file' }
import { PdfActionSchema } from '@/domain/models/app/automations/actions/pdf'
import automationPdfActionsBody from '@/domain/models/app/automations/actions/pdf-actions.docs.md' with { type: 'file' }
import automationRecordActionsBody from '@/domain/models/app/automations/actions/record-actions.docs.md' with { type: 'file' }
import { defineArticle, defineSection } from './define'

export const automationIntegrations = defineSection({
  slug: 'automation-integrations',
  title: 'Integrations',
  order: 5400,
  tab: 'automations',
  articles: [
    defineArticle({
      slug: 'automation-http-actions',
      title: 'HTTP & Webhook Actions',
      description:
        'Make authenticated outbound HTTP requests (http) and send outgoing webhooks or respond to inbound ones (webhook).',
      keywords: [
        'sovrium',
        'automation http action',
        'http request',
        'get post put patch delete',
        'connection',
        'outgoing webhook',
        'webhook response',
        'status codes',
      ],
      order: 5400,
      sidebarLabel: 'HTTP & Webhooks',
      body: automationHttpActionsBody,
      documents: [HttpActionSchema, WebhookActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-HTTP-DELETE',
        'US-AUTOMATIONS-ACTIONS-HTTP-GET',
        'US-AUTOMATIONS-ACTIONS-HTTP-PATCH',
        'US-AUTOMATIONS-ACTIONS-HTTP-POST',
        'US-AUTOMATIONS-ACTIONS-HTTP-PUT',
        'US-AUTOMATIONS-ACTIONS-HTTP-QUERY',
        'US-AUTOMATIONS-ACTIONS-HTTP-REQUEST',
        'US-AUTOMATIONS-ACTIONS-HTTP-REQUEST-OPTIONS',
        'US-AUTOMATIONS-ACTIONS-HTTP-RESPONSE-BODY',
        'US-AUTOMATIONS-ACTIONS-WEBHOOK-RESPONSE',
        'US-AUTOMATIONS-ACTIONS-WEBHOOK-SEND',
      ],
    }),
    defineArticle({
      slug: 'automation-record-actions',
      title: 'Record Actions',
      description:
        'Reading and writing table records from a workflow — single-row CRUD, filtered reads, and the batch operators.',
      keywords: [
        'sovrium',
        'automation record action',
        'create',
        'read',
        'list',
        'update',
        'delete',
        'upsert',
        'batch',
        'matchField',
      ],
      order: 5410,
      sidebarLabel: 'Record Actions',
      body: automationRecordActionsBody,
      documents: [RecordActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-RECORD-AUTHORITY',
        'US-AUTOMATIONS-ACTIONS-RECORD-BATCH-CREATE',
        'US-AUTOMATIONS-ACTIONS-RECORD-BATCH-DELETE',
        'US-AUTOMATIONS-ACTIONS-RECORD-BATCH-UPDATE',
        'US-AUTOMATIONS-ACTIONS-RECORD-BATCH-UPSERT',
        'US-AUTOMATIONS-ACTIONS-RECORD-CREATE',
        'US-AUTOMATIONS-ACTIONS-RECORD-DELETE',
        'US-AUTOMATIONS-ACTIONS-RECORD-FILTER-FIELDS',
        'US-AUTOMATIONS-ACTIONS-RECORD-LIST',
        'US-AUTOMATIONS-ACTIONS-RECORD-READ',
        'US-AUTOMATIONS-ACTIONS-RECORD-UPDATE',
        'US-AUTOMATIONS-ACTIONS-RECORD-UPSERT',
      ],
    }),
    defineArticle({
      slug: 'automation-file-actions',
      title: 'File Actions',
      description:
        'Fourteen operators over storage — moving files, reading their metadata, writing CSV, and the closed spreadsheet subset.',
      keywords: [
        'sovrium',
        'automation file action',
        'upload',
        'download',
        'signUrl',
        'generateCsv',
        'parseXlsx',
        'transformImage',
        'compress',
      ],
      order: 5412,
      sidebarLabel: 'File Actions',
      body: automationFileActionsBody,
      documents: [FileActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-FILE-COMPRESS',
        'US-AUTOMATIONS-ACTIONS-FILE-COPY',
        'US-AUTOMATIONS-ACTIONS-FILE-DELETE',
        'US-AUTOMATIONS-ACTIONS-FILE-DOWNLOAD',
        'US-AUTOMATIONS-ACTIONS-FILE-EXTRACTTEXT',
        'US-AUTOMATIONS-ACTIONS-FILE-GENERATE-CSV',
        'US-AUTOMATIONS-ACTIONS-FILE-GETMETADATA',
        'US-AUTOMATIONS-ACTIONS-FILE-LIST',
        'US-AUTOMATIONS-ACTIONS-FILE-MOVE',
        'US-AUTOMATIONS-ACTIONS-FILE-PARSECSV',
        'US-AUTOMATIONS-ACTIONS-FILE-PARSEXLSX',
        'US-AUTOMATIONS-ACTIONS-FILE-SIGNURL',
        'US-AUTOMATIONS-ACTIONS-FILE-TEMP-CLEANUP',
        'US-AUTOMATIONS-ACTIONS-FILE-TRANSFORMIMAGE',
        'US-AUTOMATIONS-ACTIONS-FILE-UPLOAD',
      ],
    }),
    defineArticle({
      slug: 'automation-document-actions',
      title: 'Document Actions',
      description:
        'Generate PDFs, images and Word documents from templates filled with run data, and workbooks from rows, into temporary storage or a record attachment.',
      keywords: [
        'sovrium',
        'automation document action',
        'generatePdf',
        'html to pdf',
        'generateImage',
        'svg to png',
        'generateDocx',
        'word template',
        'generateXlsx',
        'xlsx',
        'document template',
        'attachTo',
        'ifExists',
      ],
      order: 5414,
      sidebarLabel: 'Document Actions',
      body: automationDocumentActionsBody,
      documents: [DocumentActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-CONVERT',
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-GENERATE-DOCX',
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-GENERATE-IMAGE',
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-GENERATE-PDF',
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-GENERATE-XLSX',
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-OUTPUT',
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-SOCIAL-CARD',
        'US-AUTOMATIONS-ACTIONS-DOCUMENT-XLSX-TEMPLATE',
      ],
    }),
    defineArticle({
      slug: 'automation-pdf-actions',
      title: 'PDF Actions',
      description:
        'Merge, split and rearrange PDFs you already have, mark them with a watermark, a stamp or page numbers, fill their forms, read what they hold, or make one from pictures — all with no external engine.',
      keywords: [
        'sovrium',
        'automation pdf action',
        'merge pdf',
        'split pdf',
        'page ranges',
        'watermark pdf',
        'page numbers',
        'fill pdf form',
        'images to pdf',
        'pdf/merge',
      ],
      order: 5416,
      sidebarLabel: 'PDF Actions',
      body: automationPdfActionsBody,
      documents: [PdfActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-PDF-MERGE',
        'US-AUTOMATIONS-ACTIONS-PDF-SPLIT',
        'US-AUTOMATIONS-ACTIONS-PDF-PAGES',
        'US-AUTOMATIONS-ACTIONS-PDF-WATERMARK',
        'US-AUTOMATIONS-ACTIONS-PDF-STAMP',
        'US-AUTOMATIONS-ACTIONS-PDF-FILL-FORM',
        'US-AUTOMATIONS-ACTIONS-PDF-INSPECT',
        'US-AUTOMATIONS-ACTIONS-PDF-FROM-IMAGES',
      ],
    }),
    defineArticle({
      slug: 'automation-email-actions',
      title: 'Email & Notification Actions',
      description:
        'Send transactional email (email) and emit analytics/notification events (analytics) from a running automation.',
      keywords: [
        'sovrium',
        'automation email action',
        'send email',
        'cc bcc replyTo',
        'analytics track',
        'notifications',
        'transactional email',
        'SMTP',
      ],
      order: 5420,
      sidebarLabel: 'Email & Notifications',
      body: automationEmailActionsBody,
      documents: [EmailSendActionSchema, AnalyticsTrackActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-ANALYTICS',
        'US-AUTOMATIONS-ACTIONS-EMAIL',
        'US-AUTOMATIONS-ACTIONS-EMAIL-RENDERING',
        'US-AUTOMATIONS-ACTIONS-EMAIL-TEMPLATE-ATTACHMENTS',
      ],
    }),
    defineArticle({
      slug: 'automation-ai-actions',
      title: 'AI Actions',
      description:
        'Run LLM operations inside automations — generate text, classify input, extract structured data, and invoke autonomous agents.',
      keywords: [
        'sovrium',
        'automation ai action',
        'ai generate',
        'ai classify',
        'ai extract',
        'ai transcribe',
        'ai agent',
        'openai',
        'anthropic',
        'ollama',
        'responseFormat',
        'connection',
      ],
      order: 5430,
      sidebarLabel: 'AI Actions',
      body: automationAiActionsBody,
      documents: [AiActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-AI-AGENT',
        'US-AUTOMATIONS-ACTIONS-AI-CLASSIFY',
        'US-AUTOMATIONS-ACTIONS-AI-ERROR-HANDLING',
        'US-AUTOMATIONS-ACTIONS-AI-EXTRACT',
        'US-AUTOMATIONS-ACTIONS-AI-GENERATE',
        'US-AUTOMATIONS-ACTIONS-AI-TRANSCRIBE',
      ],
    }),
    defineArticle({
      slug: 'automation-auth-actions',
      title: 'Auth Actions',
      description:
        'Manage user accounts from a running automation — create users, assign roles, and ban or unban accounts.',
      keywords: [
        'sovrium',
        'automation auth action',
        'createUser',
        'assignRole',
        'banUser',
        'unbanUser',
        'user management',
        'rbac',
        'roles',
      ],
      order: 5440,
      sidebarLabel: 'Auth Actions',
      body: automationAuthActionsBody,
      documents: [AuthActionSchema],
      stories: [
        'US-AUTOMATIONS-ACTIONS-AUTH-ASSIGN-ROLE',
        'US-AUTOMATIONS-ACTIONS-AUTH-BAN-USER',
        'US-AUTOMATIONS-ACTIONS-AUTH-CREATE-USER',
        'US-AUTOMATIONS-ACTIONS-AUTH-UNBAN-USER',
      ],
    }),
    defineArticle({
      slug: 'automation-link-actions',
      title: 'Link Actions',
      description:
        'Mint, re-point and retire tracked short links from a workflow — the three operators, the address a later step can send, and the three refusals that fail the step.',
      keywords: [
        'sovrium',
        'automation link action',
        'short link',
        'link/create',
        'link/update',
        'link/delete',
        'shortUrl',
        'qrUrl',
        'campaign',
        'utm',
      ],
      order: 5450,
      sidebarLabel: 'Link Actions',
      body: automationLinkActionsBody,
      documents: [LinkActionSchema],
      stories: ['US-LINKS-AUTOMATION-LINK-ACTION'],
    }),
  ],
})
