/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

import { Schema } from 'effect'
import { TemplateStringSchema } from '../../template'
import { ActionBaseFields } from '../base'

/**
 * File Upload Action (type: file, operator: upload)
 *
 * Upload a file to storage from binary data, URL, or previous step output.
 * The uploaded file is available as the step output for subsequent actions.
 */
export const FileUploadActionSchema = Schema.Struct({
  ...ActionBaseFields,
  type: Schema.Literal('file').pipe(
    Schema.annotate({
      description: "Constant value 'file' for type discrimination in discriminated unions",
    })
  ),
  operator: Schema.Literal('upload').pipe(
    Schema.annotate({
      description:
        "Selects the operation within the 'file' action family; it decides which props the step takes",
    })
  ),
  props: Schema.Struct({
    /** Source data for the upload */
    source: TemplateStringSchema.pipe(
      Schema.annotate({
        description:
          'Previous step result key, URL (with `headers` when the download needs credentials), or base64 data',
      })
    ),

    /** Storage key destination */
    path: Schema.optional(
      TemplateStringSchema.pipe(
        Schema.annotate({
          description: 'Storage key destination. If omitted, auto-generated.',
        })
      )
    ),

    /**
     * Request headers sent when `source` is an `http(s)://` URL — the API key
     * of a service whose downloads are authenticated. Never sent to another
     * origin a redirect points to; every value is a secret in the run record.
     */
    headers: Schema.optional(
      Schema.Record(Schema.String, TemplateStringSchema).pipe(
        Schema.annotate({
          description:
            'Request headers sent with the download when `source` is a URL, for a service whose files need its API key (values support template variables and `$env`, e.g. `Authorization: Bearer $env.API_KEY`). They are sent to the source as written, a plain `http://` URL included, so use an `https://` source. They are not sent on to another origin a redirect points to, every value is redacted from the run record, and they are ignored for a source that is not a URL.',
        })
      )
    ),

    /**
     * The bucket the stored file belongs to. Absent, the file is a temporary
     * artifact in no bucket. Named, the file is catalogued in that bucket, so an
     * attachment column bound to it accepts the key and its read hands back a
     * working link. A literal name, never a template: the run's input never
     * chooses where a file lands.
     */
    bucket: Schema.optional(
      Schema.String.pipe(
        Schema.annotate({
          description:
            'The bucket to store the file in: a name from `buckets`, or `system`. Omitted, the file belongs to no bucket and cannot be written into an attachment column bound to one. Named, the file is catalogued in that bucket and recorded as generated by this automation, so a later `record/create` or `record/update` can put its key into an attachment column bound to the same bucket. A literal, never a template. With `path`, a key that already holds a file this automation did not store is refused, and the file there is kept.',
          examples: ['message-attachments'],
        })
      ).check(Schema.isMinLength(1))
    ),

    /** MIME type */
    contentType: Schema.optional(
      TemplateStringSchema.pipe(
        Schema.annotate({
          description: 'MIME type. If omitted, auto-detected from filename.',
        })
      )
    ),
  }).annotate({
    description: 'The file to store, the path and bucket it is stored under, and its content type.',
  }),
}).pipe(
  Schema.annotate({
    identifier: 'FileUploadAction',
    title: 'File Upload Action',
    description: 'Upload a file to storage from binary data, URL, or previous step output',
  })
)

/** @public */
export type FileUploadAction = Schema.Schema.Type<typeof FileUploadActionSchema>
