/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/**
 * `--help` for the REFERENCE verbs — `docs`, `changelog` and `library` — which
 * read the catalogues compiled into the binary (the manual, the release notes
 * and the installable library) rather than an app. Split out of
 * `command-help.ts`, which sits at its line ceiling; `COMMAND_HELP` there still
 * owns the lookup.
 */
export const DOCS_HELP_TEXT = [
  'Usage: sovrium docs [address] [options]',
  '       sovrium docs <subcommand> <argument> [options]',
  '',
  'Read the platform manual out of this binary — offline, with no config file,',
  'no database and no network. What it prints describes the engine you are',
  'actually running, so it can never document a different version.',
  '',
  'Markdown is the default because the intended reader is an AI agent: point one',
  'at `sovrium docs search <topic>` from your CLAUDE.md instead of at the web.',
  '',
  'Arguments:',
  '  address                       <section> or <section>/<slug>; omit it for the',
  '                                table of contents',
  '',
  'Subcommands:',
  '  search <query>                Find the article covering a topic',
  '  config <path>                 One option: kind, values, default, prose',
  '  env <NAME>                    One environment variable',
  '  cli <verb>                    One command, beside its help text',
  '',
  'Options:',
  '  --full                        The whole manual, for a context window',
  '  --format <md|json|llms>       md (default), json for tooling, llms for an index',
  '  --section <slug>              Restrict to one section, repeatable',
  '  --list-sections               Print the section slugs and exit',
  '  --lang <code>                 Manual locale; `en` only, anything else refused',
  '  --output <path>               Write to a file instead of stdout (creates parent dirs)',
  '  --export <dir>                Write every article plus _nav.json into <dir> (refuses a',
  '                                non-empty dir without --force)',
  '  --force                       With --export, replace the files a previous export owns',
  '  --help, -h                    Show this help message',
  '',
  'Exit codes:',
  '  0                             The manual, or the piece of it you addressed',
  '  1                             Unknown address, option path, variable, verb,',
  '                                format or locale — each refused by name',
  '',
  'Examples:',
  '  sovrium docs                                  # Table of contents',
  '  sovrium docs app-schema/llms-txt              # One article',
  '  sovrium docs search llms                      # Find the article',
  '  sovrium docs config llms.full                 # Look one option up',
  '  sovrium docs env DATABASE_URL                 # One variable',
  '  sovrium docs cli migrate                      # One command',
  '  sovrium docs --full --output MANUAL.md        # The whole manual',
  "  sovrium docs --export content/docs/en         # A docs site's article tree",
].join('\n')

export const LIBRARY_HELP_TEXT = [
  'Usage: sovrium library list [--kind <kind>] [--category <c>] [--format md|json]',
  '       sovrium library search <query> [--format md|json]',
  '       sovrium library show <id> [--format md|json]',
  '       sovrium library add <id> [--set key=value]… [--as <name>] [--into <config>]',
  '                                [--dry-run] [--no-wire]',
  '',
  'Browse the ready-made blocks, connections and automation recipes shipped in',
  'this binary, and copy one into your config. The installed fragment is yours:',
  'it lands in library/<kind>/<name>.yaml beside your config, and app.yaml gains',
  'one `- $ref:` line. app.ts is never edited; the lines to paste are printed.',
  '',
  'Options:',
  '  --kind <kind>                 block, connection or recipe (list)',
  '  --category <category>         Narrow the list to one category (list)',
  '  --format <md|json>            md (default) or json for tooling',
  '  --set <key=value>             Fill a declared parameter, repeatable (add)',
  '  --as <name>                   Install under another name (add)',
  '  --into <config>               The config to install into, inside the working',
  '                                directory (add; default: discovered like `start`)',
  '  --dry-run                     Print what would be written, write nothing (add)',
  '  --no-wire                     Write the fragment, print the line to add (add)',
  '  --help, -h                    Show this help message',
  '',
  'Examples:',
  '  sovrium library search brevo',
  '  sovrium library show connection/qonto',
  '  sovrium library add block/hero-centered --set headline="Welcome" --dry-run',
  '  sovrium library add recipe/form-to-brevo --set form=newsletter --set listId=7',
].join('\n')

export const CHANGELOG_HELP_TEXT = [
  'Usage: sovrium changelog [<version>] [--list] [--since <version>] [--format md|json]',
  '                         [--output <path>]',
  '',
  'Read the release notes this binary carries — offline, with no config file,',
  'no database and no network. With no argument it prints the entry of the',
  'version you run, then how many earlier releases it knows about.',
  '',
  'Arguments:',
  '  version                       One release, as 0.27.0 or v0.27.0',
  '',
  'Options:',
  '  --list                        One line per release, newest first, with what',
  '                                each entry holds; the running one marked current',
  '  --since <version>             Every release after <version> up to the running',
  '                                one, its breaking changes gathered first',
  '  --format <md|json>            md (default), or one json document for tooling',
  '  --output <path>               Write to a file instead of stdout (creates parent dirs)',
  '  --help, -h                    Show this help message',
  '',
  'Exit codes:',
  '  0                             The notes asked for, or `Already up to date`',
  '  1                             A version this binary does not carry, a word that',
  '                                is not a version, two views at once, or an',
  '                                unknown format — each refused by name',
  '',
  'Examples:',
  '  sovrium changelog                             # What changed in this version',
  '  sovrium changelog 0.27.0                      # One release',
  '  sovrium changelog --list                      # Every release',
  '  sovrium changelog --since 0.26.0              # Everything since an upgrade',
  '  sovrium changelog --since 0.26.0 --format json',
].join('\n')
