/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

import { Schema } from 'effect'
import { AiChatTypeLiteral, aiChatFields } from './ai'
import {
  TextTypeLiteral,
  textFields,
  IconTypeLiteral,
  iconFields,
  ImageTypeLiteral,
  imageFields,
  VideoTypeLiteral,
  videoFields,
  AudioTypeLiteral,
  audioFields,
  IframeTypeLiteral,
  iframeFields,
  CodeElementTypeLiteral,
  codeElementFields,
  TocTypeLiteral,
  tocFields,
  SearchInputTypeLiteral,
  searchInputFields,
} from './content'
import { CustomHtmlTypeLiteral, customHtmlFields } from './custom'
import {
  DataTableTypeLiteral,
  dataTableFields,
  KanbanTypeLiteral,
  kanbanFields,
  CalendarTypeLiteral,
  calendarFields,
  ChartTypeLiteral,
  chartFields,
  KpiTypeLiteral,
  kpiFields,
  GalleryTypeLiteral,
  galleryFields,
  FormTypeLiteral,
  formFields,
  ListTypeLiteral,
  listFields,
  DataTimelineTypeLiteral,
  dataTimelineFields,
} from './data'
import {
  StaticTableTypeLiteral,
  staticTableFields,
  EmptyStateTypeLiteral,
  emptyStateFields,
  CarouselTypeLiteral,
  carouselFields,
  CommandTypeLiteral,
  commandFields,
  ResizableTypeLiteral,
  resizableFields,
  ScrollAreaTypeLiteral,
  scrollAreaFields,
  AspectRatioTypeLiteral,
  aspectRatioFields,
  AccordionTypeLiteral,
  accordionFields,
  TabsTypeLiteral,
  tabsFields,
  TimelineTypeLiteral,
  timelineFields,
  ListItemTypeLiteral,
  listItemFields,
  SpeechBubbleTypeLiteral,
  speechBubbleFields,
} from './display'
import {
  SkeletonTypeLiteral,
  skeletonFields,
  ProgressTypeLiteral,
  progressFields,
  SpinnerTypeLiteral,
  spinnerFields,
} from './feedback'
import {
  InputTypeLiteral,
  inputFields,
  CheckboxTypeLiteral,
  checkboxFields,
  RadioGroupTypeLiteral,
  radioGroupFields,
  SelectTypeLiteral,
  selectFields,
  ComboboxTypeLiteral,
  comboboxFields,
  TextareaTypeLiteral,
  textareaFields,
  DatePickerTypeLiteral,
  datePickerFields,
  SliderTypeLiteral,
  sliderFields,
  InputOtpTypeLiteral,
  inputOtpFields,
  FieldTypeLiteral,
  fieldFields,
  ToggleTypeLiteral,
  toggleFields,
  ToggleGroupTypeLiteral,
  toggleGroupFields,
  SwitchTypeLiteral,
  switchFields,
} from './form-controls'
import {
  ButtonTypeLiteral,
  buttonFields,
  BadgeTypeLiteral,
  badgeFields,
  AlertTypeLiteral,
  alertFields,
  LinkTypeLiteral,
  linkFields,
  ButtonGroupTypeLiteral,
  buttonGroupFields,
} from './interactive'
import {
  ContainerTypeLiteral,
  containerFields,
  FlexTypeLiteral,
  flexFields,
  GridTypeLiteral,
  gridFields,
  ResponsiveGridTypeLiteral,
  responsiveGridFields,
  SidebarTypeLiteral,
  sidebarFields,
  TabPanelTypeLiteral,
  tabPanelFields,
  CardTypeLiteral,
  cardFields,
  HeroTypeLiteral,
  heroFields,
  ModalTypeLiteral,
  modalFields,
} from './layout'
import {
  BreadcrumbTypeLiteral,
  breadcrumbFields,
  DropdownMenuTypeLiteral,
  dropdownMenuFields,
  ContextMenuTypeLiteral,
  contextMenuFields,
  MenubarTypeLiteral,
  menubarFields,
  NavigationMenuTypeLiteral,
  navigationMenuFields,
  PaginationTypeLiteral,
  paginationFields,
} from './navigation'
import {
  AlertDialogTypeLiteral,
  alertDialogFields,
  DialogTypeLiteral,
  dialogFields,
  DrawerTypeLiteral,
  drawerFields,
  PopoverTypeLiteral,
  popoverFields,
  TooltipTypeLiteral,
  tooltipFields,
  HoverCardTypeLiteral,
  hoverCardFields,
  ToastTypeLiteral,
  toastFields,
} from './overlays'
import {
  FileUploadTypeLiteral,
  fileUploadFields,
  WizardTypeLiteral,
  wizardFields,
  NumberInputTypeLiteral,
  numberInputFields,
  TimePickerTypeLiteral,
  timePickerFields,
  StatusIndicatorTypeLiteral,
  statusIndicatorFields,
  ReorderableListTypeLiteral,
  reorderableListFields,
  LanguageSwitcherTypeLiteral,
  languageSwitcherFields,
  CommentsTypeLiteral,
  commentsFields,
  CommentCountTypeLiteral,
  commentCountFields,
} from './specialty'
import { DividerTypeLiteral, dividerFields, SpacerTypeLiteral, spacerFields } from './structural'


export * from './layout'
export * from './content'
export * from './data'
export * from './form-controls'
export * from './interactive'
export * from './navigation'
export * from './overlays'
export * from './display'
export * from './feedback'
export * from './specialty'
export * from './structural'
export * from './ai'
export * from './custom'
export * from './modules'


const allComponents = [
  [ContainerTypeLiteral, containerFields],
  [FlexTypeLiteral, flexFields],
  [GridTypeLiteral, gridFields],
  [ResponsiveGridTypeLiteral, responsiveGridFields],
  [SidebarTypeLiteral, sidebarFields],
  [TabPanelTypeLiteral, tabPanelFields],
  [CardTypeLiteral, cardFields],
  [HeroTypeLiteral, heroFields],
  [ModalTypeLiteral, modalFields],
  [TextTypeLiteral, textFields],
  [IconTypeLiteral, iconFields],
  [ImageTypeLiteral, imageFields],
  [VideoTypeLiteral, videoFields],
  [AudioTypeLiteral, audioFields],
  [IframeTypeLiteral, iframeFields],
  [CodeElementTypeLiteral, codeElementFields],
  [TocTypeLiteral, tocFields],
  [SearchInputTypeLiteral, searchInputFields],
  [DataTableTypeLiteral, dataTableFields],
  [KanbanTypeLiteral, kanbanFields],
  [CalendarTypeLiteral, calendarFields],
  [ChartTypeLiteral, chartFields],
  [KpiTypeLiteral, kpiFields],
  [GalleryTypeLiteral, galleryFields],
  [FormTypeLiteral, formFields],
  [ListTypeLiteral, listFields],
  [DataTimelineTypeLiteral, dataTimelineFields],
  [InputTypeLiteral, inputFields],
  [CheckboxTypeLiteral, checkboxFields],
  [RadioGroupTypeLiteral, radioGroupFields],
  [SelectTypeLiteral, selectFields],
  [ComboboxTypeLiteral, comboboxFields],
  [TextareaTypeLiteral, textareaFields],
  [DatePickerTypeLiteral, datePickerFields],
  [SliderTypeLiteral, sliderFields],
  [InputOtpTypeLiteral, inputOtpFields],
  [FieldTypeLiteral, fieldFields],
  [ToggleTypeLiteral, toggleFields],
  [ToggleGroupTypeLiteral, toggleGroupFields],
  [SwitchTypeLiteral, switchFields],
  [ButtonTypeLiteral, buttonFields],
  [BadgeTypeLiteral, badgeFields],
  [AlertTypeLiteral, alertFields],
  [LinkTypeLiteral, linkFields],
  [ButtonGroupTypeLiteral, buttonGroupFields],
  [BreadcrumbTypeLiteral, breadcrumbFields],
  [DropdownMenuTypeLiteral, dropdownMenuFields],
  [ContextMenuTypeLiteral, contextMenuFields],
  [MenubarTypeLiteral, menubarFields],
  [NavigationMenuTypeLiteral, navigationMenuFields],
  [PaginationTypeLiteral, paginationFields],
  [AlertDialogTypeLiteral, alertDialogFields],
  [DialogTypeLiteral, dialogFields],
  [DrawerTypeLiteral, drawerFields],
  [PopoverTypeLiteral, popoverFields],
  [TooltipTypeLiteral, tooltipFields],
  [HoverCardTypeLiteral, hoverCardFields],
  [ToastTypeLiteral, toastFields],
  [StaticTableTypeLiteral, staticTableFields],
  [EmptyStateTypeLiteral, emptyStateFields],
  [CarouselTypeLiteral, carouselFields],
  [CommandTypeLiteral, commandFields],
  [ResizableTypeLiteral, resizableFields],
  [ScrollAreaTypeLiteral, scrollAreaFields],
  [AspectRatioTypeLiteral, aspectRatioFields],
  [AccordionTypeLiteral, accordionFields],
  [TabsTypeLiteral, tabsFields],
  [TimelineTypeLiteral, timelineFields],
  [ListItemTypeLiteral, listItemFields],
  [SpeechBubbleTypeLiteral, speechBubbleFields],
  [SkeletonTypeLiteral, skeletonFields],
  [ProgressTypeLiteral, progressFields],
  [SpinnerTypeLiteral, spinnerFields],
  [FileUploadTypeLiteral, fileUploadFields],
  [WizardTypeLiteral, wizardFields],
  [NumberInputTypeLiteral, numberInputFields],
  [TimePickerTypeLiteral, timePickerFields],
  [StatusIndicatorTypeLiteral, statusIndicatorFields],
  [ReorderableListTypeLiteral, reorderableListFields],
  [LanguageSwitcherTypeLiteral, languageSwitcherFields],
  [CommentsTypeLiteral, commentsFields],
  [CommentCountTypeLiteral, commentCountFields],
  [DividerTypeLiteral, dividerFields],
  [SpacerTypeLiteral, spacerFields],
  [AiChatTypeLiteral, aiChatFields],
  [CustomHtmlTypeLiteral, customHtmlFields],
] as const


export const ComponentTypeSchema = Schema.Union(
  ContainerTypeLiteral,
  FlexTypeLiteral,
  GridTypeLiteral,
  ResponsiveGridTypeLiteral,
  SidebarTypeLiteral,
  TabPanelTypeLiteral,
  CardTypeLiteral,
  HeroTypeLiteral,
  ModalTypeLiteral,
  TextTypeLiteral,
  IconTypeLiteral,
  ImageTypeLiteral,
  VideoTypeLiteral,
  AudioTypeLiteral,
  IframeTypeLiteral,
  CodeElementTypeLiteral,
  TocTypeLiteral,
  SearchInputTypeLiteral,
  DataTableTypeLiteral,
  KanbanTypeLiteral,
  CalendarTypeLiteral,
  ChartTypeLiteral,
  KpiTypeLiteral,
  GalleryTypeLiteral,
  FormTypeLiteral,
  ListTypeLiteral,
  DataTimelineTypeLiteral,
  InputTypeLiteral,
  CheckboxTypeLiteral,
  RadioGroupTypeLiteral,
  SelectTypeLiteral,
  ComboboxTypeLiteral,
  TextareaTypeLiteral,
  DatePickerTypeLiteral,
  SliderTypeLiteral,
  InputOtpTypeLiteral,
  FieldTypeLiteral,
  ToggleTypeLiteral,
  ToggleGroupTypeLiteral,
  SwitchTypeLiteral,
  ButtonTypeLiteral,
  BadgeTypeLiteral,
  AlertTypeLiteral,
  LinkTypeLiteral,
  ButtonGroupTypeLiteral,
  BreadcrumbTypeLiteral,
  DropdownMenuTypeLiteral,
  ContextMenuTypeLiteral,
  MenubarTypeLiteral,
  NavigationMenuTypeLiteral,
  PaginationTypeLiteral,
  AlertDialogTypeLiteral,
  DialogTypeLiteral,
  DrawerTypeLiteral,
  PopoverTypeLiteral,
  TooltipTypeLiteral,
  HoverCardTypeLiteral,
  ToastTypeLiteral,
  StaticTableTypeLiteral,
  EmptyStateTypeLiteral,
  CarouselTypeLiteral,
  CommandTypeLiteral,
  ResizableTypeLiteral,
  ScrollAreaTypeLiteral,
  AspectRatioTypeLiteral,
  AccordionTypeLiteral,
  TabsTypeLiteral,
  TimelineTypeLiteral,
  ListItemTypeLiteral,
  SpeechBubbleTypeLiteral,
  SkeletonTypeLiteral,
  ProgressTypeLiteral,
  SpinnerTypeLiteral,
  FileUploadTypeLiteral,
  WizardTypeLiteral,
  NumberInputTypeLiteral,
  TimePickerTypeLiteral,
  StatusIndicatorTypeLiteral,
  ReorderableListTypeLiteral,
  LanguageSwitcherTypeLiteral,
  CommentsTypeLiteral,
  CommentCountTypeLiteral,
  DividerTypeLiteral,
  SpacerTypeLiteral,
  AiChatTypeLiteral,
  CustomHtmlTypeLiteral
).annotations({
  title: 'Component Type',
  description: 'Component type for page building',
})

export type ComponentType = Schema.Schema.Type<typeof ComponentTypeSchema>


const CONTAINER_TYPES: ReadonlySet<string> = new Set([
  'container',
  'flex',
  'grid',
  'responsive-grid',
  'sidebar',
  'tab-panel',
  'card',
  'hero',
  'modal',
  'text',
  'button',
  'badge',
  'link',
  'alert',
  'button-group',
  'form',
  'list',
  'field',
  'alert-dialog',
  'dialog',
  'drawer',
  'popover',
  'tooltip',
  'hover-card',
  'empty-state',
  'carousel',
  'command',
  'resizable',
  'scroll-area',
  'aspect-ratio',
  'accordion',
  'tabs',
  'timeline',
  'list-item',
  'wizard',
  'reorderable-list',
  'custom-react',
  'customHTML',
])


type InjectableFields = Record<string, any>

export function buildComponentUnion(
  childrenField: InjectableFields,
  extraFields: InjectableFields = {}
): Schema.Schema<any, any, never> {
  const branches = allComponents.map(([typeLiteral, fields]) => {
    const { ast } = typeLiteral
    const isContainer =
      ast._tag === 'Literal' && typeof ast.literal === 'string' && CONTAINER_TYPES.has(ast.literal)

    return Schema.Struct({
      type: typeLiteral,
      ...(isContainer ? childrenField : {}),
      ...fields,
      ...extraFields,
    })
  })

  return Schema.Union(
    ...(branches as [(typeof branches)[0], (typeof branches)[0], ...typeof branches])
  )
}
