/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

// Automations — the catalog of what the operator declared, and the history of
// what it did.
//
// ─── WHAT KEPT THIS A BUILDER, AND WHAT CLOSED IT ──────────────────────────
//
// Two gaps, both properties of the config surface rather than of this console,
// and each found by spending the previous one.
//
// The first was the CONTROL. A config `select` hydrated into a Base UI trigger +
// listbox, while this surface's own acceptance tests drive it as a browser
// `<select>` — `selectOption('bump-views-on-update')`, `toHaveValue('')`. That
// is a DOM change the tests refuse, and rewriting them is a specification
// decision rather than part of a migration. `select.native` is the
// answer: the engine already server-renders a real element with the real
// choices in it and disables it only because an island is about to replace it,
// so the mode is that element left enabled.
//
// The second was the "All" ROW. The filter's options can only come from
// `dataSource.system` — a preset page cannot read the OPERATOR's
// `app.automations` — and a system option source REPLACES `options` outright,
// while `options` XOR `dataSource` is refused at decode. So the row that
// submits nothing had nowhere to be declared, and a native select with no such
// row selects its FIRST option: the surface would have opened pre-filtered to
// whichever automation sorted first, quietly contradicting the unfiltered count
// printed beside it. `select.emptyOption` is that row, folded into the
// resolved list before either renderer sees it.
//
// ─── THE FILTER BAR IS TWO PUBLISHERS, NOT AN ISLAND ───────────────────────
//
// `shared-filter-select` was a bespoke island whose entire job was to dispatch
// one `island:system-query` event. `select.publishes` is that dispatch as a
// declaration: each control names the channel and the request-param key it
// contributes, the grid's `bindTo` + `sharedFilter` names the same channel, and
// the vanilla runtime binds the `change` listener. No hydration at all.
//
// ─── WHAT MOVED, VISIBLY ───────────────────────────────────────────────────
//
// The two filter captions. The island rendered "Automation" / "Status" beside
// the control and carried the accessible name in an `aria-label`; the native
// rendering derives its accessible name from the visible label it wraps, so the
// caption IS the name — "Filter by automation" / "Filter by status". Every
// locator in the specs addresses the accessible name, which is unchanged; the
// `@regression` screenshot is not, and its Linux baseline is regenerated by CI.

import {
  emptyState,
  pageHeading,
  tabQuery,
  tabbedBody,
  tabPanel,
  toolbarRow,
} from '../../components/data-page'
import { withShell } from '../../components/shell'
import {
  AUTOMATION_RUN_DETAIL_ENDPOINT,
  AUTOMATION_RUNS_ENDPOINT,
  AUTOMATIONS_ENDPOINT,
  AUTOMATIONS_OVERVIEW_ENDPOINT,
} from '../../system-sources'
import type { Page as PageConfig } from '@/domain/models/app'

/** One node of a page's component tree, as the config type expresses it. */
type PageComponent = NonNullable<PageConfig['components']>[number]

/**
 * Id of the catalog grid. Doubles as the `onSuccess.refetch` target, so a pause
 * or resume re-queries this same table and the State cell reconciles without a
 * page reload.
 */
const CATALOG_GRID_ID = 'automations-catalog-grid'

/** Id of the run-history grid — addressed directly by the surface's own specs. */
/**
 * The run status badge: an outline-dot chip, the dot painted with `dot`.
 *
 * A function rather than six literals so the six statuses cannot drift apart;
 * the CSS candidates are harvested from the resolved preset, so a composed
 * class string still reaches the stylesheet.
 */
const runStatusBadge = (dot: string): string =>
  [
    '[&>span]:inline-flex [&>span]:items-center [&>span]:gap-1.5 [&>span]:rounded-full',
    '[&>span]:border [&>span]:border-border-strong [&>span]:px-2 [&>span]:py-0.5',
    '[&>span]:text-xs [&>span]:text-foreground',
    `[&>span]:before:size-1.5 [&>span]:before:shrink-0 [&>span]:before:rounded-full [&>span]:before:${dot}`,
  ].join(' ')
const QUIET_BADGE = runStatusBadge('bg-foreground-subtle')

const RUNS_GRID_ID = 'automation-runs-grid'

/**
 * The shared-filter CHANNEL both selects publish on and the runs grid subscribes
 * to.
 *
 * It was the bespoke publisher island's `sourceId`; under `publishes` it is a
 * plain channel name that no element has to own. Kept spelled the same so the
 * before/after of this migration is a change of mechanism and not of address.
 */
const RUNS_FILTER_CHANNEL = 'automation-runs-filter'

/**
 * Catalog columns.
 *
 * `valueLabels` is render-time only: the endpoint contract keeps the raw
 * `'active' | 'paused' | 'disabled'` enum, and its response schema is strict, so
 * relabelling server-side is impossible by design.
 *
 * `Paused by` / `Paused at` are two columns rather than one concatenated string:
 * during an incident an operator needs both WHO stopped it and WHEN, and
 * separate columns sort and format properly. `pausedBy` is nullable — the pause
 * outlives the account that set it (`ON DELETE SET NULL`), so a deleted operator
 * leaves the pause standing with an empty actor.
 *
 * The State column carries no colour. [internal ref] A7 names this exact surface: the
 * console's own status pills are chrome, because Sovrium invented that
 * vocabulary rather than the app author, and A1 retired `success` / `warning`.
 */
const CATALOG_COLUMNS = [
  { field: 'name', label: '$t:admin.automations.catalog.col.automation' },
  { field: 'trigger', label: '$t:admin.automations.catalog.col.trigger' },
  {
    field: 'state',
    label: '$t:admin.automations.catalog.col.state',
    valueLabels: {
      active: '$t:admin.automations.catalog.state.active',
      paused: '$t:admin.automations.catalog.state.paused',
      disabled: '$t:admin.automations.catalog.state.disabled',
    },
  },
  // Only a platform pause carries a `reason`; an operator pause leaves it null
  // and `Paused by` names who. So the column is sparse by design: a mark in it
  // means nobody chose this pause, which is the one thing an operator must see
  // before deciding whether Resume is safe.
  {
    field: 'reason',
    label: '$t:admin.automations.catalog.reason',
    valueLabels: { 'consecutive-failures': '$t:admin.automations.catalog.reason.automatic' },
  },
  { field: 'pausedBy', label: '$t:admin.automations.catalog.col.pausedBy' },
  { field: 'pausedAt', label: '$t:admin.automations.catalog.col.pausedAt', format: 'datetime' },
  {
    type: 'actions',
    label: '',
    capability: 'edit-operations',
    actions: [
      {
        label: '$t:admin.automations.catalog.action.pause',
        visibleWhen: { field: 'state', eq: 'active' },
        // Both labels EXPLICIT: the confirm-gate runtime falls back to FRENCH
        // ('Confirmer' / 'Annuler'). Do not drop these: the default is wrong.
        //
        // The message's second sentence is a factual claim, verified before it
        // shipped: every gate is consulted at dispatch/resolve time, nothing
        // re-checks inside the run loop, and there is no delayed-resume path.
        confirm: {
          title: '$t:admin.automations.catalog.pause.title',
          message: '$t:admin.automations.catalog.pause.message',
          confirmLabel: '$t:admin.automations.catalog.action.pause',
          cancelLabel: '$t:admin.automations.cancel',
        },
        action: {
          type: 'fetch',
          method: 'POST',
          // Automation names are constrained to /^[a-z][a-z0-9-]*$/ by AppSchema,
          // so they are URL-safe unencoded — the same property the webhook routes
          // already rely on.
          url: '/api/admin/automations/$record.name/pause',
          // `type` + `message` are REQUIRED on a fetch `onSuccess`, so the
          // refetch cannot ride alone. The retired builder declared a bare
          // `{ refetch }` and got away with it only because a synthesised page
          // is never decoded; expressed as config it has to say what the
          // operator is told, which is the users directory's pattern too.
          onSuccess: {
            type: 'toast',
            message: '$t:admin.automations.catalog.pause.toast',
            refetch: CATALOG_GRID_ID,
          },
        },
      },
      {
        // No confirm gate: resume is the reversal of a reversible action, so a
        // gate here is friction without consequence. Confirmation is reserved
        // for the direction that stops production work.
        label: '$t:admin.automations.catalog.action.resume',
        visibleWhen: { field: 'state', eq: 'paused' },
        action: {
          type: 'fetch',
          method: 'POST',
          url: '/api/admin/automations/$record.name/resume',
          onSuccess: {
            type: 'toast',
            message: '$t:admin.automations.catalog.resume.toast',
            refetch: CATALOG_GRID_ID,
          },
        },
      },
      // A `state: 'disabled'` row satisfies NEITHER predicate, so no control
      // renders on it. Configuration is code-only ([internal ref] D2) and the console
      // must never offer to change it; a Resume button that cannot work would be
      // the same class of lie as a search box returning wrong answers.
    ],
  },
]

/**
 * The catalog grid, with NO heading of its own.
 *
 * It sits directly under the page heading, which already reads "Automations" —
 * a section heading here restated it verbatim, which is the ornament [internal ref] D4
 * cuts. The run history below DOES take an `h3`, because it is the section that
 * needs naming to be told apart from the catalog above it.
 */
const catalogGrid = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: { className: 'px-6' },
    children: [
      {
        type: 'table',
        props: { id: CATALOG_GRID_ID, 'aria-label': '$t:admin.automations.region' },
        dataSource: {
          system: { endpoint: AUTOMATIONS_ENDPOINT, rowsKey: 'items', idKey: 'name' },
        },
        columns: CATALOG_COLUMNS,
        toolbar: { sort: true },
        emptyMessage: '$t:admin.automations.catalog.empty',
      },
    ],
  }) as PageComponent

/**
 * One filter control.
 *
 * `props.className` lands on the `<label>` the native rendering wraps the
 * control in; the caption's own class list is the renderer's, so the two
 * controls cannot drift apart. `w-56` is what keeps them from stretching: the
 * control carries `w-full`, so an unbounded label would let the automation
 * filter's width follow its longest option name.
 */
const filter = (
  id: string,
  label: string,
  param: string,
  choices: Readonly<Record<string, unknown>>
): PageComponent =>
  ({
    type: 'select',
    native: true,
    props: { id, label, className: 'w-56' },
    emptyOption: { label: '$t:admin.automations.runs.filter.all' },
    publishes: { bindTo: RUNS_FILTER_CHANNEL, param },
    ...choices,
  }) as PageComponent

/**
 * The filter bar: the automation picker and the status picker, both publishing
 * on {@link RUNS_FILTER_CHANNEL}.
 *
 * The automation options come from the SAME endpoint the catalog above binds —
 * one projection, two consumers — because the operator's `app.automations` is
 * unreadable from a preset page and this is the fact that stands in for it.
 *
 * The status list is static and its VALUES are the engine's, not the operator's:
 * a successful run persists as `completed`, so the "Success" choice carries
 * `completed`. The retired island held that mapping in TypeScript
 * (`toQueryStatus`) precisely because its option value was the operator word;
 * declaring the engine value directly deletes the mapping rather than moving it.
 *
 * The two CAPTIONS are translated like everything else: the select renderer
 * resolves a `$t:` label itself, because the caption is read off the raw
 * `props` that the props translation pass never reaches.
 */
const filterBar = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: { className: 'mb-4 flex flex-wrap items-end gap-3' },
    children: [
      filter('automation-filter', '$t:admin.automations.runs.filter.automation', 'automationName', {
        dataSource: {
          system: { endpoint: AUTOMATIONS_ENDPOINT, rowsKey: 'items', idKey: 'name' },
          valueKey: 'name',
          labelKey: 'name',
        },
      }),
      filter('status-filter', '$t:admin.automations.runs.filter.status', 'status', {
        options: [
          { value: 'completed', label: '$t:admin.automations.runs.status.success' },
          { value: 'failed', label: '$t:admin.automations.runs.status.failed' },
          { value: 'completed-with-errors', label: '$t:admin.automations.runs.status.partial' },
          { value: 'waiting-approval', label: '$t:admin.automations.runs.status.waitingApproval' },
          { value: 'waiting-delay', label: '$t:admin.automations.runs.status.waitingDelay' },
          { value: 'rejected', label: '$t:admin.automations.runs.status.rejected' },
          { value: 'cancelled', label: '$t:admin.automations.runs.status.cancelled' },
        ],
      }),
    ],
  }) as PageComponent

/**
 * The run-history grid.
 *
 * ## Why the search box needs BOTH `search` and `toolbar.search`
 *
 * The render guard is `showSearch && searchConfig` — `toolbar.search` alone
 * renders no box, and `search` alone leaves the toolbar without the affordance.
 * Declaring only one is the quiet way to ship an inert control.
 *
 * The term goes to the SERVER, which applies it over every run and echoes
 * `appliedQuery` — the signal that tells the grid to stand down from filtering
 * the page it holds. Without that echo a client narrows an already-narrowed page
 * and hides matches living past it, and only on fields that happen to be
 * rendered columns, which is how that class of bug stays invisible.
 */
const runsGrid = (): PageComponent =>
  ({
    type: 'table',
    props: { id: RUNS_GRID_ID, 'aria-label': '$t:admin.automations.runs.heading' },
    dataSource: {
      system: {
        endpoint: AUTOMATION_RUNS_ENDPOINT,
        rowsKey: 'items',
        idKey: 'id',
        bindTo: RUNS_FILTER_CHANNEL,
        sharedFilter: { params: ['automationName', 'status'] },
      },
    },
    columns: [
      { field: 'automationName', label: '$t:admin.automations.runs.col.automation' },
      {
        field: 'status',
        label: '$t:admin.automations.runs.col.status',
        // The platform has already turned the engine's word into the operator's
        // (`completed` → `Success`, `waiting-approval` → `Waiting for approval`,
        // see `automation-run-status.ts`) before a row reaches the grid, so the
        // map is keyed on THAT word, and so is `cellStyle`, which reads the
        // value and never the label.
        valueLabels: {
          Success: '$t:admin.automations.runs.status.success',
          Failed: '$t:admin.automations.runs.status.failed',
          Partial: '$t:admin.automations.runs.status.partial',
          'Waiting for approval': '$t:admin.automations.runs.status.waitingApproval',
          'Waiting to resume': '$t:admin.automations.runs.status.waitingDelay',
          Rejected: '$t:admin.automations.runs.status.rejected',
          Cancelled: '$t:admin.automations.runs.status.cancelled',
          'Retries exhausted': '$t:admin.automations.runs.status.retriesExhausted',
          'Timed out': '$t:admin.automations.runs.status.timedOut',
          Queued: '$t:admin.automations.runs.status.queued',
          Running: '$t:admin.automations.runs.status.running',
          Skipped: '$t:admin.automations.runs.status.skipped',
        },
        // One outline-dot badge per status, the form the templates' option
        // chips take: an outlined chip on the page's strong edge with a leading
        // dot, so the word stays the reading and the dot only marks the kind.
        // Every class is scoped to the cell's inner `span` (`[&>span]:`): the
        // grid writes a `cellStyle` class on the cell AND on the span inside
        // it, and a pill painted on the whole cell reads as a grey slab.
        cellStyle: [
          { when: { eq: 'Success' }, className: runStatusBadge('bg-success-solid') },
          // The error role — the one status here that has to read at a glance.
          { when: { eq: 'Failed' }, className: runStatusBadge('bg-error-solid') },
          { when: { eq: 'Partial' }, className: runStatusBadge('bg-warning-solid') },
          // Someone has to answer before the run can go on.
          { when: { eq: 'Waiting for approval' }, className: runStatusBadge('bg-info-solid') },
          // A decision, not a fault: an approver said no, or the run was
          // stopped on purpose. Neither is painted as a failure.
          { when: { in: ['Rejected', 'Cancelled'] }, className: QUIET_BADGE },
          // Every retry spent: a failure, painted as one.
          { when: { eq: 'Retries exhausted' }, className: runStatusBadge('bg-error-solid') },
          // It ran out of time rather than broke: a warning.
          { when: { eq: 'Timed out' }, className: runStatusBadge('bg-warning-solid') },
          // Not finished yet: queued, parked on a long wait (nobody has to act), or under way.
          { when: { in: ['Queued', 'Waiting to resume'] }, className: QUIET_BADGE },
          { when: { eq: 'Running' }, className: runStatusBadge('bg-info-solid') },
          // A filter stopped it, as written — not a fault.
          { when: { eq: 'Skipped' }, className: QUIET_BADGE },
        ],
      },
      { field: 'startedAt', label: '$t:admin.automations.runs.col.started', format: 'datetime' },
      { field: 'durationMs', label: '$t:admin.automations.runs.col.duration', align: 'right' },
      {
        type: 'actions',
        label: '',
        actions: [
          {
            label: '$t:admin.automations.runs.action.view',
            action: { type: 'fetch', mode: 'navigate', url: '/automations/runs/$record.id' },
          },
        ],
      },
    ],
    search: { enabled: true, placeholder: '$t:admin.automations.runs.search' },
    toolbar: { search: true, sort: true },
    // The grid owns the page's scroll on this surface: the KPI strip, the
    // filter bar and the read-window note keep their natural height above it
    // and the rows take whatever is left, so the column header stays pinned
    // and the operator never scrolls a labelled table into an unlabelled one.
    layout: 'fill',
    emptyMessage: '$t:admin.automations.runs.empty',
    noMatchMessage: '$t:admin.automations.runs.noMatch',
  }) as PageComponent

/**
 * The two halves of this route, and the `?tab=` value that addresses each.
 *
 * HISTORY FIRST, and that is the whole point of the reorder. An operator opens
 * this surface because something ran — or did not — so the run feed is the
 * answer they came for; the catalogue is what they consult once they know which
 * automation to look at. It was the other way round, with the catalogue on top
 * and the feed below a heading, so reading the last failure meant scrolling
 * past a directory every time.
 */
const TABS = [
  { id: 'history', label: '$t:admin.automations.tabs.history' },
  { id: 'automations', label: '$t:admin.automations.tabs.automations' },
] as const

/**
 * One run figure, read as a pre-computed scalar from the automations-overview
 * envelope.
 *
 * All four tiles share ONE request: the system-value hook keys its cache on the
 * endpoint AND the query and deliberately not on the value path.
 */
const overviewKpi = (
  label: string,
  valuePath: string,
  kpiFormat: Readonly<Record<string, unknown>>
): PageComponent =>
  ({
    type: 'kpi',
    label,
    dataSource: { system: { endpoint: AUTOMATIONS_OVERVIEW_ENDPOINT, valuePath } },
    kpiFormat,
  }) as PageComponent

/**
 * The run figures, which shipped in `/api/admin/automations/overview` and were
 * drawn by nothing.
 *
 * ─── WHY HERE AND NOT IN THE CHROME BAR ────────────────────────────────────
 *
 * The canvas puts these four in the 48px bar as a count and a facts line — a
 * row of plain text, not cards. Config cannot express that: a system-bound
 * scalar is a `kpi`, `kpi` is a lazy island, and an island in the chrome paints
 * a skeleton inside the bar on every load. There is no `text` that binds a
 * system value, so the bar placement is a PLATFORM gap rather than an authoring
 * choice, and it is filed as one. A strip at the top of the panel is what
 * config does support, and it is what every sibling data surface already does.
 *
 * `success_rate` formats with `scale: '100'`, which is the combinator that
 * renders a 0–1 RATIO as a whole percent — the endpoint returns `1` for "every
 * run succeeded". Read as "the number is already a percentage, leave it alone"
 * it goes the other way and prints `1%` over a perfect record; measured, and
 * that is what it printed before this line was corrected.
 */
const runsKpiStrip = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: {
      role: 'region',
      'aria-label': '$t:admin.automations.metrics.region',
      // Two-up at the narrowest width, not one-up. This strip sits ABOVE a
      // `layout: 'fill'` grid, which takes whatever height the chrome above it
      // leaves; one-up stacked all four cards and took 376px of a 665px pinned
      // column at 375, which with the filter bar, the read-window note and the
      // gaps over-subscribed the column and squeezed the grid to its 2px
      // border. The rows were then clipped inside a zero-height scroller on a
      // page that does not scroll, so the run feed was unreachable by any
      // gesture. Four short figures read fine two-up, and it hands ~172px back.
      className: 'grid grid-cols-2 gap-4 lg:grid-cols-4',
    },
    children: [
      overviewKpi('$t:admin.automations.metrics.automations', 'totals.automations', {
        type: 'number',
      }),
      overviewKpi('$t:admin.automations.metrics.runs24h', 'totals.runs_24h', { type: 'number' }),
      overviewKpi('$t:admin.automations.metrics.failures24h', 'totals.failures_24h', {
        type: 'number',
      }),
      overviewKpi('$t:admin.automations.metrics.successRate', 'totals.success_rate', {
        type: 'percentage',
        options: { scale: '100' },
      }),
    ],
  }) as PageComponent

/**
 * The History panel: the run figures, the filter bar, the run feed and its
 * read-window statement. A run opens on its own page, not over this panel.
 *
 * The `px-6` / `p-6` the two sections carried are GONE. They were the gutter of
 * a body stacked under a page title; the console's content column supplies its
 * own 16px now, and a second inset made the grid sit 24px further in than every
 * other grid in the console.
 */
const historyPanel = (): PageComponent =>
  tabPanel([
    runsKpiStrip(),
    filterBar(),
    runsGrid(),
    // The read-window statement, and the load-bearing half is the second
    // sentence: it names the affordance that DOES reach older runs (search
    // and the filters both query server-side over every run) and admits
    // that a narrowed result carries the same 25-row cap. Without it,
    // removing the pager would just relocate the wrong answer one
    // interaction later.
    {
      type: 'text',
      element: 'p',
      props: { className: 'text-foreground-subtle text-md' },
      content: '$t:admin.automations.runs.scope',
    } as PageComponent,
  ])

/**
 * The Automations panel: the catalogue, with pause and resume on each row.
 *
 * Its own `h3` is gone with the split — the tab caption above it names it, and
 * a heading directly under a trigger that says the same word is the duplication
 * the chrome bar already retired once this console.
 */
const catalogPanel = (): PageComponent => tabPanel([catalogGrid()], { scroll: true })

/**
 * Everything that needs at least one declared automation.
 *
 * `declares` EXCLUDES rather than hides, so exactly one of this and the empty
 * state below reaches the document. The predicate is the same one the retired
 * builder tested — a non-empty `app.automations` — expressed as a capability
 * rather than recomputed here.
 *
 * The GATE is on the strip, not inside it: an app declaring no automations gets
 * the empty state and NO tab bar, rather than two triggers over two empty
 * tables. A strip is an offer of two answers, and there are none to offer.
 */
const liveBody = (): PageComponent =>
  ({
    ...(tabbedBody('$t:admin.automations.tabs.region', TABS, [historyPanel(), catalogPanel()], {
      fill: true,
    }) as Record<string, unknown>),
    visibility: { declares: 'automations' },
  }) as PageComponent

/**
 * The whole-page empty state.
 *
 * With no automations declared there is nothing to catalogue AND nothing to run,
 * so one region stands in for both sections.
 */
const noAutomations = (): PageComponent =>
  ({
    ...(emptyState(
      '$t:admin.automations.empty.heading',
      '$t:admin.automations.empty.body',
      '$t:admin.automations.empty.hint'
    ) as Record<string, unknown>),
    visibility: { unlessDeclares: 'automations' },
  }) as PageComponent

const runsPage: PageConfig = withShell(
  {
    id: 'dashboard-data-automations',
    name: 'dashboard-data-automations',
    path: '/automations',
    meta: { title: '$t:admin.meta.automations', lang: 'en-US' },
    // `?tab=` is the address of each half. Without this block `$query.tab` is
    // left verbatim and the strip silently opens on History for every link.
    query: tabQuery(TABS),
    components: [
      pageHeading('$t:admin.automations.heading', '$t:admin.automations.blurb'),
      liveBody(),
      noAutomations(),
    ],
  } as PageConfig,
  { breadcrumb: { automations: '$t:admin.crumb.automations' }, fill: true }
)

// ─── THE RUN PAGE — `/automations/runs/:id` ─────────────────────────────
//
// One run, read in full: its header, what it was given, each step with what it
// was handed, what it returned and what it logged, and the Retry gesture.
//
// It replaced a record-bound drawer over the grid. A drawer and a page showing
// the same run would each need the steps, the logs, the status words and Retry,
// and two surfaces describing one run had already drifted here once — the grid
// said `Success` while the drawer it opened said `completed`. So there is one
// run view, and it is this page.
//
// THE RECORD IS READ ON THE SERVER. The page-level `{ system }` binding reads
// the run-detail endpoint as the visitor before the page is sent, so every
// `$record.` value is in the first response, a run id that names nothing is the
// page's own 404, and `$record.id` is already in the Retry action's URL before
// anyone can press it.
//
// EVERY FIELD IS LABELLED FOR THE PERSON READING IT. Unlabelled, a field falls
// back to its envelope key — `automationName`, `durationMs`, `triggerType` —
// which is the API's spelling rather than the operator's, and reads as a debug
// dump beside the English the rest of the console speaks.
//
// OBJECTS PRINT AS JSON, AND ONLY IN A LONE-TOKEN `code` BLOCK. `triggerData`,
// a step's `input` and its `output` are arbitrary objects whose shape differs
// per trigger and per action. A `code` node whose whole content is one token
// prints such a value as indented JSON with sorted keys; anywhere else an
// object-valued token stays a literal token rather than printing
// `[object Object]`. So each of the three sits alone in its own `code` block.

/** A quiet section heading — the page's `h2` voice. */
const caption = (content: string): PageComponent =>
  ({
    type: 'text',
    element: 'h2',
    props: { className: 'text-foreground-subtle text-xs font-medium tracking-wide uppercase' },
    content,
  }) as PageComponent

/**
 * One JSON block, named in its own frame — "Data in", "Data out".
 *
 * The token stands ALONE in `content`, which is what makes an object print as
 * indented JSON rather than stay a literal token. The label is the frame's
 * `filename`: left unset, the frame captions itself from the language and
 * reads `app.json`, which names a file the run never had. As the filename it
 * also labels the block for assistive technology, so no heading repeats it.
 */
const jsonSection = (label: string, token: string): PageComponent =>
  ({
    type: 'code',
    filename: label,
    props: { language: 'json' },
    content: token,
  }) as PageComponent

/** One key–value pair of the run header. The value's props carry its own hooks. */
const headerField = (
  label: string,
  value: string,
  valueProps: Readonly<Record<string, string>> = {}
): readonly PageComponent[] => [
  {
    type: 'text',
    element: 'span',
    props: { className: 'text-foreground-subtle' },
    content: label,
  } as PageComponent,
  {
    type: 'text',
    element: 'span',
    props: { ...valueProps, className: 'text-foreground min-w-0 break-words' },
    content: value,
  } as PageComponent,
]

/**
 * The run header, a quiet key–value group.
 *
 * The status value carries `data-testid="run-status"` because the same raw word
 * can also appear inside the Data in JSON below, where it is a fact on the wire
 * and correctly verbatim; the header's value is the one that must speak the
 * grid's vocabulary.
 *
 * It does, without a map in this file: the platform relabels any read of the
 * runs endpoint — the grid's in the browser, this page's `{ system }` record on
 * the server — from one shared table, so the header and each station print
 * `Success` where the engine stored `completed`. The server read also puts the
 * word in the reader's language, from the same `$t:` keys the grid's
 * `valueLabels` name — a French operator reads « Ignorée » here as in the
 * history. Adding a second map here is exactly how one vocabulary would come to
 * have two spellings.
 */
const runHeader = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: {
      className: 'grid grid-cols-[max-content_minmax(0,1fr)] gap-x-6 gap-y-1 text-sm',
    },
    children: [
      ...headerField(
        '$t:admin.automations.runs.detail.field.automation',
        '$record.automationName',
        {
          className: 'font-mono',
        }
      ),
      // The VALUE is the grid's word in the reader's language: the server-side
      // read relabels it from the keys the grid's `valueLabels` name.
      ...headerField('$t:admin.automations.runs.detail.field.status', '$record.status', {
        'data-testid': 'run-status',
      }),
      ...headerField('$t:admin.automations.runs.detail.field.trigger', '$record.triggerType'),
      ...headerField('$t:admin.automations.runs.detail.field.started', '$record.startedAt'),
      ...headerField('$t:admin.automations.runs.detail.field.finished', '$record.completedAt'),
      ...headerField('$t:admin.automations.runs.detail.field.duration', '$record.durationMs'),
      ...headerField('$t:admin.automations.runs.detail.field.attempt', '$record.attempt'),
    ],
  }) as PageComponent

/**
 * The run's failure, shown as stored — and only when there is one.
 *
 * A `null` error substitutes to the empty string, which leaves the message
 * element with no content at all; the `has-[>p:empty]` rule then hides the
 * caption with it, so a run that succeeded shows no "Failure" heading over
 * nothing. The gate is a style rule rather than `visibility.record`, because a
 * page's `{ system }` record substitutes but does not gate.
 */
const runFailure = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: { className: 'flex flex-col gap-1 has-[>p:empty]:hidden' },
    children: [
      caption('$t:admin.automations.runs.detail.failure'),
      {
        type: 'text',
        element: 'p',
        props: { className: 'text-error-fg font-mono text-xs break-words whitespace-pre-wrap' },
        content: '$record.error',
      },
    ],
  }) as PageComponent

/**
 * One logged line: the engine's own level word, then the message.
 *
 * `data-log-level` is the hook the console styles, and the ONLY one: the line
 * turns to the error role through `data-[log-level=error]:` and the level label
 * follows it through `in-data-[log-level=error]:`, so the colour rides a data
 * attribute and never a token inside a class list. Inside a repeat a token
 * resolves in content and in `data-*` attributes and in no other prop.
 */
const logLine = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: {
      role: 'listitem',
      'data-testid': 'run-log',
      'data-log-level': '$log.level',
      className:
        'text-foreground flex items-baseline gap-3 px-3 py-1.5 data-[log-level=error]:text-error-fg',
    },
    children: [
      {
        type: 'text',
        element: 'span',
        props: {
          className:
            'text-foreground-subtle in-data-[log-level=error]:text-error-fg w-12 shrink-0 font-mono text-xs uppercase',
        },
        content: '$log.level',
      },
      {
        type: 'text',
        element: 'span',
        props: { className: 'min-w-0 font-mono text-xs break-words whitespace-pre-wrap' },
        content: '$log.message',
      },
    ],
  }) as PageComponent

/**
 * A step's log: every line it wrote, in call order — or a sentence saying it
 * wrote none.
 *
 * The list repeats over the step's `logs`, the second level of a named, nested
 * repeat. A step that logged nothing draws no copy, which leaves the list with
 * no content at all, so `empty:hidden` removes it and the sentence right after
 * it — its next sibling, which is what `peer-empty:` needs — appears instead.
 * The endpoint always ships `logs`, empty for a silent step, so there is no
 * third state to handle.
 */
const stepLog = (): readonly PageComponent[] => [
  {
    type: 'container',
    element: 'div',
    repeat: { record: 'logs', as: 'log' },
    props: {
      role: 'list',
      'aria-label': '$t:admin.automations.runs.detail.log',
      className:
        'peer border-border divide-border flex max-h-64 flex-col divide-y overflow-y-auto rounded border empty:hidden',
    },
    children: [logLine()],
  } as PageComponent,
  {
    type: 'text',
    element: 'p',
    props: { className: 'text-foreground-subtle hidden text-sm peer-empty:block' },
    content: '$t:admin.automations.runs.detail.noLogs',
  } as PageComponent,
]

/**
 * One station per step: its name and status on one line, its error, what it
 * was handed and what it returned, and what it logged.
 *
 * A station is NOT a control. Step-to-panel selection is not offered, and a
 * marker that cannot act is the affordance `BRAND.md` §9 forbids; a station
 * contains controls (the copy buttons of its JSON blocks) but is never one.
 *
 * `data-testid` is a literal; `data-step-index` and `data-step-status` resolve
 * per copy. The error line is empty — and invisible — on a step that did not
 * fail, because `null` substitutes to the empty string; that is what makes it
 * safe without the `visibility.record` gate a repeat may not carry.
 */
const stepStation = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: {
      className: 'flex flex-col gap-3 px-4 py-3',
      'data-testid': 'run-step',
      'data-step-index': '$step.index',
      'data-step-status': '$step.status',
    },
    children: [
      {
        type: 'container',
        element: 'div',
        props: { className: 'flex items-baseline justify-between gap-3' },
        children: [
          {
            type: 'text',
            element: 'span',
            props: { className: 'text-foreground min-w-0 font-mono text-sm' },
            content: '$step.name',
          },
          // Like the run header's status, the step's word is relabelled in the
          // reader's language on the server (`filtered` under its own key).
          {
            type: 'text',
            element: 'span',
            props: { className: 'text-foreground-subtle shrink-0 text-xs' },
            content: '$step.status',
          },
        ],
      },
      {
        type: 'text',
        element: 'p',
        props: { className: 'text-error-fg text-xs break-words empty:hidden' },
        content: '$step.error',
      },
      {
        type: 'container',
        element: 'div',
        props: { className: 'grid gap-3 lg:grid-cols-2' },
        children: [
          jsonSection('$t:admin.automations.runs.detail.dataIn', '$step.input'),
          jsonSection('$t:admin.automations.runs.detail.dataOut', '$step.output'),
        ],
      },
      ...stepLog(),
    ],
  }) as PageComponent

/**
 * The steps, one station each, drawn on the server from the run's `steps`.
 *
 * The repeat is NAMED (`as: 'step'`) because a second repeat — each step's
 * `logs` — nests inside it, and an unnamed outer repeat would leave `$record.`
 * meaning two things at once. Inside it `$step.` reads the step and `$record.`
 * keeps reading the run.
 *
 * The host's `divide-y` separates the copies: a `first:` variant on the
 * template would fire on every copy, since each one is rendered as its own.
 */
const stepsSection = (): PageComponent =>
  ({
    type: 'container',
    element: 'section',
    props: {
      'aria-label': '$t:admin.automations.runs.detail.steps',
      className: 'flex flex-col gap-2',
    },
    children: [
      caption('$t:admin.automations.runs.detail.steps'),
      {
        type: 'container',
        element: 'div',
        repeat: { record: 'steps', as: 'step' },
        props: {
          className: 'border-border divide-border divide-y overflow-hidden rounded-lg border',
        },
        children: [stepStation()],
      },
    ],
  }) as PageComponent

/**
 * Where this automation lives, in place of a control.
 *
 * Configuration is code-only, so the console answers "where do I
 * change this?" with the ADDRESS rather than an edit affordance it would have to
 * refuse. Two lines, because they do two jobs: the first is a value an operator
 * copies into an editor, the second is why there is no button to press instead.
 */
const configuredInCode = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: { className: 'border-border flex flex-col gap-1 border-t pt-3' },
    children: [
      {
        type: 'text',
        element: 'span',
        props: { className: 'text-foreground-subtle font-mono text-xs' },
        // A config PATH, not prose: it reads the same in every language.
        content: 'automations[] → $record.automationName',
      },
      {
        type: 'text',
        element: 'p',
        props: { className: 'text-foreground-subtle text-sm' },
        content: '$t:admin.automations.runs.detail.configuredInCode',
      },
    ],
  }) as PageComponent

/** Back to the history — the page's way out, where the drawer's was Escape. */
const backToRuns = (): PageComponent =>
  ({
    type: 'link',
    content: '$t:admin.automations.runs.detail.back',
    props: {
      href: '/automations',
      className: 'text-foreground-muted hover:text-foreground text-sm underline',
    },
  }) as PageComponent

/**
 * Retry, confirm-gated: it starts a NEW run and leaves this one as it was. Both labels are spelled out because the confirm
 * gate's own defaults are French.
 */
const retryButton = (): PageComponent =>
  ({
    type: 'button',
    label: '$t:admin.automations.runs.detail.retry',
    variant: 'secondary',
    visibility: { capability: 'edit-operations' },
    confirm: {
      title: '$t:admin.automations.runs.detail.retry.title',
      message: '$t:admin.automations.runs.detail.retry.message',
      role: 'alertdialog',
      confirmLabel: '$t:admin.automations.runs.detail.retry',
      cancelLabel: '$t:admin.automations.cancel',
    },
    action: {
      type: 'fetch',
      method: 'POST',
      url: '/api/admin/automations/runs/$param.id/retry',
      onSuccess: { type: 'toast', message: '$t:admin.automations.runs.detail.retry.toast' },
      onError: {
        type: 'toast',
        variant: 'destructive',
        message: '$t:admin.automations.runs.detail.retry.error',
      },
    },
  }) as PageComponent

/**
 * `/automations/runs/:id` — one run, read in full.
 *
 * Unlike the object sub-pages whose `h1` names the surface, this one's `h1`
 * names the run's AUTOMATION: a run has no name of its own, and "which
 * automation did this" is the first thing an operator opening it needs. The
 * trail carries the rest.
 *
 * `meta.title` cannot name the run: the route-param pass walks `components`
 * and `layout`, deliberately not `meta`.
 */
const runPage: PageConfig = withShell(
  {
    id: 'dashboard-data-automation-run',
    name: 'dashboard-data-automation-run',
    path: '/automations/runs/:id',
    meta: { title: '$t:admin.meta.automationRun', lang: 'en-US' },
    dataSource: { system: { endpoint: AUTOMATION_RUN_DETAIL_ENDPOINT, param: 'id' } },
    components: [
      {
        type: 'container',
        element: 'div',
        props: { className: 'flex min-w-0 flex-col gap-6 pt-2 pb-8' },
        children: [
          toolbarRow([backToRuns(), retryButton()]),
          {
            type: 'container',
            element: 'div',
            props: { className: 'flex flex-col gap-1' },
            children: [
              {
                type: 'text',
                element: 'h1',
                props: { className: 'text-foreground font-mono text-lg font-medium' },
                content: '$record.automationName',
              },
              {
                type: 'text',
                element: 'p',
                props: { className: 'sr-only' },
                content: '$t:admin.automations.runs.detail.blurb',
              },
            ],
          },
          runHeader(),
          jsonSection('$t:admin.automations.runs.detail.dataIn', '$record.triggerData'),
          runFailure(),
          stepsSection(),
          configuredInCode(),
        ],
      } as PageComponent,
    ],
  } as PageConfig,
  {
    breadcrumb: {
      automations: '$t:admin.crumb.automations',
      runs: '$t:admin.crumb.automationRun',
    },
    // Nothing answers at /automations/runs: the history is /automations.
    breadcrumbUnlinked: ['runs'],
  }
)

/** The run history and the one run that reads out of it. */
export const automationPages: readonly PageConfig[] = [runsPage, runPage]
