/**
 * @sovrium/types - TypeScript type definitions for Sovrium app configuration
 *
 * This package provides zero-dependency TypeScript types for authoring
 * Sovrium configuration files with full IDE autocompletion.
 *
 * @example
 * ```typescript
 * import { defineConfig } from '@sovrium/types'
 *
 * export default defineConfig({
 *   name: 'my-app',
 *   description: 'My Sovrium application',
 *   tables: [{ id: 1, name: 'contacts', fields: [] }],
 * })
 * ```
 */

// NOTE: The actual type definitions in dist/ are generated by scripts/build/build-types.ts.
// It uses the TypeScript Compiler API to resolve Effect Schema types into plain
// structural types, producing a zero-dependency .d.ts file.
//
// This source file is NOT used directly by consumers — it serves as documentation
// and build reference. The build script extracts types from src/index.ts exports.

// These type re-exports are for reference only (build script extracts from src/index.ts):
export type { AppEncoded as AppConfig } from '@/domain/models/app'
export type { Table } from '@/domain/models/app/tables'
export type { Page } from '@/domain/models/app/pages'
// Markdown-page surfaces (nested under Page) — re-exported directly so authors
// can annotate `markdown` / `contentDir` config blocks. `Markdown.layout`
// includes the `'none'` wrapper mode; `ContentDir.nav` describes the docs
// sidebar derivation. Mirrored here as build-script-resolved structural types
// (no effect/markdown-it/shiki imports — this package stays zero-dependency).
export type { Markdown, ContentDir } from '@/domain/models/app/pages/markdown'
export type { Theme } from '@/domain/models/app/theme'
// `Theme.codeBlock` selects the Shiki syntax-highlighting theme for markdown
// fenced code blocks. Re-exported as a structural type alias.
export type { CodeBlockConfig } from '@/domain/models/app/theme/code-block'
export type { Auth } from '@/domain/models/app/auth'
export type { Languages } from '@/domain/models/app/languages'
export type { BuiltInAnalytics } from '@/domain/models/app/analytics'
export type { ComponentTemplate } from '@/domain/models/app/components/component'
export type { Automation } from '@/domain/models/app/automations'
export type { Connection } from '@/domain/models/app/connections'
export type { EnvVar } from '@/domain/models/app/env'
export type { Form } from '@/domain/models/app/forms'
export type { ActionTemplate } from '@/domain/models/app/actions'

// `*Config` aliases mirror the public surface published in dist/index.d.ts
// (generated from the root src/index.ts by the build script). This file is the
// `paths` target for `@sovrium/types` during typecheck (tsconfig.json), so the
// alias surface MUST stay in sync with the build script's TYPE_EXPORTS list —
// otherwise consumers (apps/*) resolve the package here and hit TS2305 on any
// name present in dist but missing below.
export type { Page as PageConfig } from '@/domain/models/app/pages'
export type { Table as TableConfig } from '@/domain/models/app/tables'
export type { ComponentTemplate as ComponentConfig } from '@/domain/models/app/components/component'
export type { Theme as ThemeConfig } from '@/domain/models/app/theme'
export type { Auth as AuthConfig } from '@/domain/models/app/auth'
export type { Languages as LanguageConfig } from '@/domain/models/app/languages'
export type { BuiltInAnalytics as AnalyticsConfig } from '@/domain/models/app/analytics'
export type { Automation as AutomationConfig } from '@/domain/models/app/automations'
export type { Agent as AgentConfig } from '@/domain/models/app/agents'
export type { Connection as ConnectionConfig } from '@/domain/models/app/connections'
export type { Form as FormConfig } from '@/domain/models/app/forms'
export type { EnvVar as EnvConfig } from '@/domain/models/app/env'

/**
 * CodeContext - typed context object passed to every runTypescript code action.
 *
 * Operators MUST annotate their execute() parameter as CodeContext:
 *   async function execute(context: CodeContext) { ... }
 *
 * The TypeScriptValidator rejects any code action whose execute() declares a
 * first parameter without this annotation, so type errors on context.<key>
 * accesses surface at server startup instead of failing silently at request
 * time.
 *
 * Five properties: `inputData`, `actions`, `env`, `log`, `packages`. The
 * trigger payload and prior step outputs are NOT exposed directly — every
 * value the code needs must be declared explicitly via the action's
 * `inputData` prop using `{{trigger.data.X}}` / `{{steps.Y.Z}}` template
 * references, resolved before the sandbox sees the data. This makes a
 * code action a pure function of its declared inputs.
 *
 * `actions` references reusable action templates declared at the schema
 * root (`app.actions[]`), NOT sibling steps in the same automation.
 * `context.actions.<templateName>(input)` invokes the named template,
 * substituting its `$vars` with the caller-supplied `input` shallow-
 * merged on top of declared variable defaults.
 *
 * `inputData`, `packages`, and `actions` return type use `any` (not
 * `unknown`): they hold dynamic JSON / module / action-output shapes,
 * and `unknown` would force narrowing on every property access. `log`
 * is strictly typed so `context.log.debug()` (or any unknown method)
 * fails type-checking at startup.
 */
export interface CodeContext {
  /** Template-resolved key-value pairs declared in the action's inputData prop */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic JSON shape, see interface JSDoc
  readonly inputData: Record<string, any>
  /**
   * Template-resolved key-value pairs declared in the action's `input`
   * prop — an alias for `inputData` surfaced under a shorter name. Present
   * only when the action declared an `input` field.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic JSON shape, see interface JSDoc
  readonly input?: Record<string, any>
  /**
   * Two-shape callable surface:
   * - `actions.ref('<templateName>', vars)` — invoke a template declared at app.actions[]
   * - `actions.<actionType>.<operator>(props)` — invoke a native action type directly (no template required)
   *
   * The reserved method `ref` disambiguates templates from native types;
   * a template named `ref` is rejected at schema validation.
   */
  readonly actions: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic return shape (templates return arbitrary handler output)
    readonly ref: (templateName: string, vars?: Record<string, unknown>) => Promise<any>
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic native dispatch (props/return shapes are per-handler, not type-narrowed yet)
  } & Record<string, Record<string, (props?: Record<string, unknown>) => Promise<any>>>
  /** Environment variables (values redacted in logs when length >= 8) */
  readonly env: Record<string, string>
  /** Structured logging — info/warn/error */
  readonly log: {
    readonly info: (...args: ReadonlyArray<unknown>) => void
    readonly warn: (...args: ReadonlyArray<unknown>) => void
    readonly error: (...args: ReadonlyArray<unknown>) => void
  }
  /** Declared npm packages, keyed by package name (e.g. packages.lodash) */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- dynamic module shape, see interface JSDoc
  readonly packages: Record<string, any>
}

/**
 * Identity function that provides TypeScript autocompletion for Sovrium app configs.
 */
export const defineConfig = <T>(config: T): T => config
