/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

// Automations — the catalog of what the operator declared, and the history of
// what it did.
//
// ─── WHAT KEPT THIS A BUILDER, AND WHAT CLOSED IT ──────────────────────────
//
// Two gaps, both properties of the config surface rather than of this console,
// and each found by spending the previous one.
//
// The first was the CONTROL. A config `select` hydrated into a Base UI trigger +
// listbox, while this surface's own acceptance tests drive it as a browser
// `<select>` — `selectOption('bump-views-on-update')`, `toHaveValue('')`. That
// is a DOM change the tests refuse, and rewriting them is a specification
// decision rather than part of a migration. `select.native` is the
// answer: the engine already server-renders a real element with the real
// choices in it and disables it only because an island is about to replace it,
// so the mode is that element left enabled.
//
// The second was the "All" ROW. The filter's options can only come from
// `dataSource.system` — a preset page cannot read the OPERATOR's
// `app.automations` — and a system option source REPLACES `options` outright,
// while `options` XOR `dataSource` is refused at decode. So the row that
// submits nothing had nowhere to be declared, and a native select with no such
// row selects its FIRST option: the surface would have opened pre-filtered to
// whichever automation sorted first, quietly contradicting the unfiltered count
// printed beside it. `select.emptyOption` is that row, folded into the
// resolved list before either renderer sees it.
//
// ─── THE FILTER BAR IS TWO PUBLISHERS, NOT AN ISLAND ───────────────────────
//
// `shared-filter-select` was a bespoke island whose entire job was to dispatch
// one `island:system-query` event. `select.publishes` is that dispatch as a
// declaration: each control names the channel and the request-param key it
// contributes, the grid's `bindTo` + `sharedFilter` names the same channel, and
// the vanilla runtime binds the `change` listener. No hydration at all.
//
// ─── WHAT MOVED, VISIBLY ───────────────────────────────────────────────────
//
// The two filter captions. The island rendered "Automation" / "Status" beside
// the control and carried the accessible name in an `aria-label`; the native
// rendering derives its accessible name from the visible label it wraps, so the
// caption IS the name — "Filter by automation" / "Filter by status". Every
// locator in the specs addresses the accessible name, which is unchanged; the
// `@regression` screenshot is not, and its Linux baseline is regenerated by CI.

import { emptyState, pageHeading, tabQuery, tabbedBody, tabPanel } from '../../components/dataPage'
import { withShell } from '../../components/shell'
import {
  AUTOMATION_RUN_DETAIL_ENDPOINT,
  AUTOMATION_RUNS_ENDPOINT,
  AUTOMATIONS_ENDPOINT,
  AUTOMATIONS_OVERVIEW_ENDPOINT,
} from '../../systemSources'
import type { PageConfig } from 'sovrium'

/** One node of a page's component tree, as the config type expresses it. */
type PageComponent = NonNullable<PageConfig['components']>[number]

/**
 * Id of the catalog grid. Doubles as the `onSuccess.refetch` target, so a pause
 * or resume re-queries this same table and the State cell reconciles without a
 * page reload.
 */
const CATALOG_GRID_ID = 'automations-catalog-grid'

/** Id of the run-history grid — addressed directly by the surface's own specs. */
const RUNS_GRID_ID = 'automation-runs-grid'

/**
 * The shared-filter CHANNEL both selects publish on and the runs grid subscribes
 * to.
 *
 * It was the bespoke publisher island's `sourceId`; under `publishes` it is a
 * plain channel name that no element has to own. Kept spelled the same so the
 * before/after of this migration is a change of mechanism and not of address.
 */
const RUNS_FILTER_CHANNEL = 'automation-runs-filter'

/** Id of the run-detail drawer — the `openDrawer` target the action column fires. */
const RUNS_DETAIL_ID = 'automation-runs-detail'

/**
 * Catalog columns.
 *
 * `valueLabels` is render-time only: the endpoint contract keeps the raw
 * `'active' | 'paused' | 'disabled'` enum, and its response schema is strict, so
 * relabelling server-side is impossible by design.
 *
 * `Paused by` / `Paused at` are two columns rather than one concatenated string:
 * during an incident an operator needs both WHO stopped it and WHEN, and
 * separate columns sort and format properly. `pausedBy` is nullable — the pause
 * outlives the account that set it (`ON DELETE SET NULL`), so a deleted operator
 * leaves the pause standing with an empty actor.
 *
 * The State column carries no colour. [internal ref] A7 names this exact surface: the
 * console's own status pills are chrome, because Sovrium invented that
 * vocabulary rather than the app author, and A1 retired `success` / `warning`.
 */
const CATALOG_COLUMNS = [
  { field: 'name', label: 'Automation' },
  { field: 'trigger', label: 'Trigger' },
  {
    field: 'state',
    label: 'State',
    valueLabels: { active: 'Active', paused: 'Paused', disabled: 'Disabled in config' },
  },
  { field: 'pausedBy', label: 'Paused by' },
  { field: 'pausedAt', label: 'Paused at', format: 'datetime' },
  {
    type: 'actions',
    label: '',
    actions: [
      {
        label: 'Pause',
        visibleWhen: { field: 'state', eq: 'active' },
        // Both labels EXPLICIT: the confirm-gate runtime falls back to FRENCH
        // ('Confirmer' / 'Annuler'), which is a live defect in the English
        // console and is reported separately. Do not drop these to "use the
        // default": the default is wrong.
        //
        // The message's second sentence is a factual claim, verified before it
        // shipped: every gate is consulted at dispatch/resolve time, nothing
        // re-checks inside the run loop, and there is no delayed-resume path.
        confirm: {
          title: 'Pause this automation?',
          message: 'New runs stop until you resume. A run already in progress is not cancelled.',
          confirmLabel: 'Pause',
          cancelLabel: 'Cancel',
        },
        action: {
          type: 'fetch',
          method: 'POST',
          // Automation names are constrained to /^[a-z][a-z0-9-]*$/ by AppSchema,
          // so they are URL-safe unencoded — the same property the webhook routes
          // already rely on.
          url: '/api/admin/automations/$record.name/pause',
          // `type` + `message` are REQUIRED on a fetch `onSuccess`, so the
          // refetch cannot ride alone. The retired builder declared a bare
          // `{ refetch }` and got away with it only because a synthesised page
          // is never decoded; expressed as config it has to say what the
          // operator is told, which is the users directory's pattern too.
          onSuccess: { type: 'toast', message: 'Automation paused', refetch: CATALOG_GRID_ID },
        },
      },
      {
        // No confirm gate: resume is the reversal of a reversible action, so a
        // gate here is friction without consequence. Confirmation is reserved
        // for the direction that stops production work.
        label: 'Resume',
        visibleWhen: { field: 'state', eq: 'paused' },
        action: {
          type: 'fetch',
          method: 'POST',
          url: '/api/admin/automations/$record.name/resume',
          onSuccess: { type: 'toast', message: 'Automation resumed', refetch: CATALOG_GRID_ID },
        },
      },
      // A `state: 'disabled'` row satisfies NEITHER predicate, so no control
      // renders on it. Configuration is code-only ([internal ref] D2) and the console
      // must never offer to change it; a Resume button that cannot work would be
      // the same class of lie as a search box returning wrong answers.
    ],
  },
]

/**
 * The catalog grid, with NO heading of its own.
 *
 * It sits directly under the page heading, which already reads "Automations" —
 * a section heading here restated it verbatim, which is the ornament [internal ref] D4
 * cuts. The run history below DOES take an `h3`, because it is the section that
 * needs naming to be told apart from the catalog above it.
 */
const catalogGrid = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: { className: 'px-6' },
    children: [
      {
        type: 'table',
        props: { id: CATALOG_GRID_ID, 'aria-label': '$t:admin.automations.region' },
        dataSource: {
          system: { endpoint: AUTOMATIONS_ENDPOINT, rowsKey: 'items', idKey: 'name' },
        },
        columns: CATALOG_COLUMNS,
        toolbar: { sort: true },
        emptyMessage: 'No automations',
      },
    ],
  }) as PageComponent

/**
 * One filter control.
 *
 * `props.className` lands on the `<label>` the native rendering wraps the
 * control in; the caption's own class list is the renderer's, so the two
 * controls cannot drift apart. `w-56` is what keeps them from stretching: the
 * control carries `w-full`, so an unbounded label would let the automation
 * filter's width follow its longest option name.
 */
const filter = (
  id: string,
  label: string,
  param: string,
  choices: Record<string, unknown>
): PageComponent =>
  ({
    type: 'select',
    native: true,
    props: { id, label, className: 'w-56' },
    emptyOption: { label: 'All' },
    publishes: { bindTo: RUNS_FILTER_CHANNEL, param },
    ...choices,
  }) as PageComponent

/**
 * The filter bar: the automation picker and the status picker, both publishing
 * on {@link RUNS_FILTER_CHANNEL}.
 *
 * The automation options come from the SAME endpoint the catalog above binds —
 * one projection, two consumers — because the operator's `app.automations` is
 * unreadable from a preset page and this is the fact that stands in for it.
 *
 * The status list is static and its VALUES are the engine's, not the operator's:
 * a successful run persists as `completed`, so the "Success" choice carries
 * `completed`. The retired island held that mapping in TypeScript
 * (`toQueryStatus`) precisely because its option value was the operator word;
 * declaring the engine value directly deletes the mapping rather than moving it.
 */
const filterBar = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: { className: 'mb-4 flex flex-wrap items-end gap-3' },
    children: [
      filter('automation-filter', 'Filter by automation', 'automationName', {
        dataSource: {
          system: { endpoint: AUTOMATIONS_ENDPOINT, rowsKey: 'items', idKey: 'name' },
          valueKey: 'name',
          labelKey: 'name',
        },
      }),
      filter('status-filter', 'Filter by status', 'status', {
        options: [
          { value: 'completed', label: 'Success' },
          { value: 'failed', label: 'Failed' },
          { value: 'completed-with-errors', label: 'Partial' },
        ],
      }),
    ],
  }) as PageComponent

/**
 * The run-history grid.
 *
 * ## Why the search box needs BOTH `search` and `toolbar.search`
 *
 * The render guard is `showSearch && searchConfig` — `toolbar.search` alone
 * renders no box, and `search` alone leaves the toolbar without the affordance.
 * Declaring only one is the quiet way to ship an inert control.
 *
 * The term goes to the SERVER, which applies it over every run and echoes
 * `appliedQuery` — the signal that tells the grid to stand down from filtering
 * the page it holds. Without that echo a client narrows an already-narrowed page
 * and hides matches living past it, and only on fields that happen to be
 * rendered columns, which is how that class of bug stays invisible.
 */
const runsGrid = (): PageComponent =>
  ({
    type: 'table',
    props: { id: RUNS_GRID_ID, 'aria-label': '$t:admin.automations.runs.heading' },
    dataSource: {
      system: {
        endpoint: AUTOMATION_RUNS_ENDPOINT,
        rowsKey: 'items',
        idKey: 'id',
        bindTo: RUNS_FILTER_CHANNEL,
        sharedFilter: { params: ['automationName', 'status'] },
      },
    },
    columns: [
      { field: 'automationName', label: 'Automation' },
      {
        field: 'status',
        label: 'Status',
        cellStyle: [
          {
            when: { eq: 'Success' },
            className: 'bg-success-bg text-success-fg rounded-full px-2 py-0.5 text-sm',
          },
          {
            when: { eq: 'Failed' },
            // The error role, not the "danger" one: the theme declares no such
            // role at all, so both halves of the pair that stood here emitted
            // no rule and a Failed run was painted exactly like an unstyled
            // cell — the one status on this table that has to read at a
            // glance. This is the same pill the Blocked and Revoked statuses
            // wear on the users and connections surfaces.
            className: 'bg-error-bg text-error-fg rounded-full px-2 py-0.5 text-sm',
          },
          {
            when: { eq: 'Partial' },
            className: 'bg-warning-bg text-warning-fg rounded-full px-2 py-0.5 text-sm',
          },
        ],
      },
      { field: 'startedAt', label: 'Started', format: 'datetime' },
      { field: 'durationMs', label: 'Duration', align: 'right' },
      {
        type: 'actions',
        label: '',
        actions: [
          { label: 'View run', action: { action: 'openDrawer', component: RUNS_DETAIL_ID } },
        ],
      },
    ],
    search: { enabled: true, placeholder: 'Search runs' },
    toolbar: { search: true, sort: true },
    // The grid owns the page's scroll on this surface: the KPI strip, the
    // filter bar and the read-window note keep their natural height above it
    // and the rows take whatever is left, so the column header stays pinned
    // and the operator never scrolls a labelled table into an unlabelled one.
    layout: 'fill',
    emptyMessage: 'No runs',
    noMatchMessage: 'No run matches “{query}”',
  }) as PageComponent

/**
 * The run-detail drill-down as a record-bound `drawer`.
 *
 * A SYSTEM-detail source, so `recordFields` describes the endpoint ENVELOPE (a
 * run row plus its `steps`) rather than a declared table — there is no table to
 * derive from and none to PATCH, which is why it is `canEdit: false`.
 *
 * ─── THE DATA IN / OUT / ERROR OF A RUN, AND WHY `steps` IS JSON ───────────
 *
 * `triggerData` is what STARTED the run — for a form trigger, the submitted
 * body, the form, the submission id and the row it linked. It shipped in this
 * envelope from the beginning and nothing drew it, so the commonest question an
 * operator opens a failed run with — what was it given? — had no answer on this
 * surface at all. `renderAs: 'json'` because it is an arbitrary blob whose shape
 * differs per trigger type; a `key-value` reading flattens one level and prints
 * `[object Object]` for the rest.
 *
 * `steps` moved from `renderAs: 'list'` to `'json'` for the same reason,
 * measured on a real failed run: each step carries `input`, `output` and
 * `error`, and `input` is itself an object, so the list rendering printed the
 * step's name and status and then `input: [object Object]` — the two fields an
 * operator came for, mangled. JSON prints all three intact.
 *
 * ─── THE SLOT UNDER THE FIELDS: WHAT IT CLOSES, AND WHAT IT DOES NOT ──────
 *
 * A `drawer` DOES have a `children` slot. The author's content renders after
 * the record fields, and a `$record.*` token inside it resolves in the BROWSER
 * once the record lands (`record-drawer-children.tsx`). This comment asserted
 * the opposite — "a drawer has no children slot at all" — until 2026-09-16,
 * and the sentence outlived the gap it described by exactly one merge.
 *
 * What the slot closes here is the question a failed run actually ends on:
 * where do I change this? The console cannot answer with a control, because
 * [internal ref] makes configuration code-only, so it answers with the ADDRESS — the
 * honest form of the same help, and the one thing this drawer could not say
 * before.
 *
 * What the slot does NOT close is the canvas's `timeline` step RAIL — one
 * marker per step, click one and the Data in / out / Error panel beside it
 * swaps. That needs ITERATION over a record's array and the slot has no
 * spelling for it: it resolves SCALARS into text nodes, and a structural
 * `timeline` renders AUTHORED children rather than rows, so it could not draw
 * N steps from a record even on a page. `steps` therefore stays
 * `renderAs: 'json'`, and the rail stays routed rather than faked.
 * Step→panel selection is the separately-known gap: `rowExpand` is table-bound
 * and unavailable on a system source.
 */
/**
 * The run's steps, one addressable station each, in the drawer's own slot.
 *
 * ─── WHAT MADE THIS POSSIBLE, AND WHERE IT IS ALLOWED TO LIVE ──────────────
 *
 * `container.repeat` renders a container's CHILDREN once per element of an
 * array the bound record already carries, and it is legal in exactly one
 * position: inside a record-bound `drawer`'s `children`, where a record has
 * actually been fetched. Everywhere else it is refused at decode rather than
 * being inert config with no visible symptom.
 *
 * The container REPEATS ITS CHILDREN rather than itself, so the per-step
 * attributes sit on the single child that gets cloned — the same shape the
 * system-rows expander uses, where the `<li>` is synthesized and the template
 * owns the node one level in.
 *
 * ─── THREE THINGS A STEP CAN SAY HERE, AND TWO IT CANNOT ───────────────────
 *
 * Inside a repeat, `$record.<key>` resolves against THE ELEMENT and coerces
 * with `String(value)`, with `null` and a missing key both becoming the empty
 * string. So a step's SCALARS reach the rail: `name`, `status`, and the
 * nullable `error`, which renders as nothing on a step that did not fail and
 * therefore needs no gate.
 *
 * It needs no gate, which is fortunate, because it could not have one:
 * `visibility.record` is REFUSED on or under a `repeat` (rule 3 of
 * `repeatPlacementViolations`) — a per-element gate fires on the server for a
 * system row template and would silently do nothing in a client-side repeat,
 * so v1 refuses it loudly rather than shipping a predicate that evaporates.
 *
 * What a step CANNOT say is `input` and `output`. Both are OBJECTS, and
 * `substitute-record-vars.ts` maps an object-valued key to the UNSUBSTITUTED
 * token rather than to `[object Object]` — so `$record.input` would reach the
 * browser as the literal text `$record.input`. That is deliberate upstream and
 * correct: `String({})` is indistinguishable from a null column, and those are
 * different facts.
 *
 * ─── THE COST OF DROPPING THE JSON BLOB, STATED RATHER THAN HIDDEN ─────────
 *
 * `steps` left `recordFields` because a rail above a dump of the same array is
 * the debug-dump shape this drawer's own field labels exist to avoid. That
 * costs the per-step `input` / `output`, and the cost is REAL, not theoretical:
 * measured on the first real failed run this console recorded, the step's
 * `error` read `email.send requires a \`to\` address` while the reason it had
 * none was visible only in `input.to`, which was the empty string.
 *
 * So the rail answers "which step, and what did it say"; it does not yet answer
 * "what was it given". Closing that needs either step-to-panel selection
 * (`rowExpand` is table-bound and unavailable on a system source) or a
 * pre-rendered summary STRING per step on the wire — the same move
 * `findings[].message` already makes on the organisation read, for the same
 * reason: a config page can print a string but cannot format one.
 */
const stepRail = (): PageComponent =>
  ({
    type: 'container',
    element: 'section',
    props: {
      'aria-label': 'Steps',
      'data-testid': 'run-steps',
      className: 'border-border flex flex-col gap-2 border-t pt-3',
    },
    children: [
      {
        type: 'text',
        element: 'h3',
        props: {
          className: 'text-foreground-subtle text-xs font-medium tracking-wide uppercase',
        },
        content: 'Steps',
      },
      {
        // The repeating host. Its `divide-y` is what separates the clones,
        // because a `first:`-style variant on the template would fire on every
        // copy — each one is an only child of its own render.
        type: 'container',
        element: 'div',
        repeat: { record: 'steps' },
        props: {
          className: 'border-border divide-border divide-y overflow-hidden rounded-lg border',
        },
        children: [
          {
            type: 'container',
            element: 'div',
            // `data-testid` is a LITERAL; the two `$record.` attributes beside
            // it resolve per copy, and the bound is narrower than "props".
            //
            // Measured, not assumed: inside a repeat a token resolves in
            // CONTENT and in `data-*` ATTRIBUTES, and in no other prop —
            // `[internal ref]`. The client-side expander
            // writes a value through `setAttribute`, and a `data-*` attribute
            // navigates nothing, fetches nothing and styles nothing, so it is
            // the half that needs no per-destination escaping answer. A token
            // in `className`, `style` or `href` still survives verbatim; do
            // not read the two below as licence to author a third elsewhere.
            //
            // Only SCALARS resolve. `index` and `status` are scalars on
            // `adminRunStepSchema`, so each station states its own; a step's
            // object-valued `input` / `output` would leave its token in place
            // rather than print `[object Object]`, which is what the panel gap
            // is for.
            props: {
              className: 'flex flex-col gap-0.5 px-3 py-2',
              'data-testid': 'run-step',
              'data-step-index': '$record.index',
              'data-step-status': '$record.status',
            },
            children: [
              {
                type: 'container',
                element: 'div',
                props: { className: 'flex items-baseline justify-between gap-3' },
                children: [
                  {
                    type: 'text',
                    element: 'span',
                    props: { className: 'text-foreground min-w-0 font-mono text-xs' },
                    content: '$record.name',
                  },
                  {
                    // The status word arrives in the operator's vocabulary, not
                    // the engine's: the system-source hook localises the DETAIL
                    // path as well as the list one, and descends into a run's
                    // `steps`, so a step that completed reads `Success` here
                    // and in the grid that opened this drawer
                    //.
                    //
                    // The map is deliberately partial — `completed`, `failed`
                    // and `completed-with-errors` have labels; anything else
                    // the engine emits prints verbatim rather than being
                    // guessed at. Printed as it arrives either way: a config
                    // page has no string operations, and a second spelling
                    // invented here is exactly how one vocabulary comes to have
                    // two on one screen.
                    type: 'text',
                    element: 'span',
                    props: { className: 'text-foreground-subtle shrink-0 text-xs' },
                    content: '$record.status',
                  },
                ],
              },
              {
                // Empty and therefore invisible on a step that did not fail —
                // `null` substitutes to the empty string, which is what makes
                // this line safe without the gate a repeat may not carry.
                type: 'text',
                element: 'span',
                props: { className: 'text-error-fg text-xs' },
                content: '$record.error',
              },
            ],
          },
        ],
      },
    ],
  }) as PageComponent

const detailDrawer = (): PageComponent =>
  ({
    type: 'drawer',
    id: RUNS_DETAIL_ID,
    // No `role`, so this is a `dialog` — see the note on the links definition
    // drawer. A `region` is a landmark with no dismiss contract, so Escape did
    // nothing and focus never entered the drawer.
    props: { title: 'Run details' },
    dataSource: { system: { endpoint: AUTOMATION_RUN_DETAIL_ENDPOINT, param: 'runId' } },
    canEdit: false,
    // Every field carries a `label`. Without one the panel prints the ENVELOPE
    // key — `automationName`, `durationMs`, `triggerType` — which is the API's
    // spelling rather than the operator's, and reads as a debug dump beside the
    // English the rest of the console speaks.
    recordFields: [
      { name: 'automationName', type: 'single-line-text', label: 'Automation' },
      { name: 'status', type: 'single-line-text', label: 'Status' },
      { name: 'triggerType', type: 'single-line-text', label: 'Trigger' },
      { name: 'startedAt', type: 'single-line-text', label: 'Started' },
      { name: 'completedAt', type: 'single-line-text', label: 'Finished' },
      { name: 'durationMs', type: 'single-line-text', label: 'Duration (ms)' },
      { name: 'attempt', type: 'single-line-text', label: 'Attempt' },
      { name: 'triggerData', type: 'json', label: 'Data in', renderAs: 'json' },
      // `steps` is NOT here any more. It is drawn as a rail in the slot below —
      // see `stepRail`, which also records what that costs.
      { name: 'error', type: 'long-text', label: 'Failure', renderAs: 'code' },
    ],
    // The address, under the fields. Two lines rather than one because they do
    // two jobs: the first is a value an operator copies into an editor, the
    // second is why there is no button here to press instead.
    children: [
      stepRail(),
      {
        type: 'container',
        element: 'div',
        props: { className: 'border-border flex flex-col gap-1 border-t pt-3' },
        children: [
          {
            type: 'text',
            element: 'span',
            props: { className: 'text-foreground-subtle font-mono text-xs' },
            // Resolved in the browser, not here: the drawer is built before
            // anyone knows which run it will open for.
            content: 'automations[] → $record.automationName',
          },
          {
            type: 'text',
            element: 'p',
            props: { className: 'text-foreground-subtle text-sm' },
            content: '$t:admin.automations.runs.detail.configuredInCode',
          },
        ],
      },
    ],
    actions: [
      {
        label: 'Retry',
        confirm: 'Confirm retry',
        action: {
          type: 'fetch',
          method: 'POST',
          url: '/api/admin/automations/runs/$record.id/retry',
        },
      },
    ],
  }) as PageComponent

/**
 * The two halves of this route, and the `?tab=` value that addresses each.
 *
 * HISTORY FIRST, and that is the whole point of the reorder. An operator opens
 * this surface because something ran — or did not — so the run feed is the
 * answer they came for; the catalogue is what they consult once they know which
 * automation to look at. It was the other way round, with the catalogue on top
 * and the feed below a heading, so reading the last failure meant scrolling
 * past a directory every time.
 */
const TABS = [
  { id: 'history', label: 'History' },
  { id: 'automations', label: 'Automations' },
] as const

/**
 * One run figure, read as a pre-computed scalar from the automations-overview
 * envelope.
 *
 * All four tiles share ONE request: the system-value hook keys its cache on the
 * endpoint AND the query and deliberately not on the value path.
 */
const overviewKpi = (
  label: string,
  valuePath: string,
  kpiFormat: Readonly<Record<string, unknown>>
): PageComponent =>
  ({
    type: 'kpi',
    label,
    dataSource: { system: { endpoint: AUTOMATIONS_OVERVIEW_ENDPOINT, valuePath } },
    kpiFormat,
  }) as PageComponent

/**
 * The run figures, which shipped in `/api/admin/automations/overview` and were
 * drawn by nothing.
 *
 * ─── WHY HERE AND NOT IN THE CHROME BAR ────────────────────────────────────
 *
 * The canvas puts these four in the 48px bar as a count and a facts line — a
 * row of plain text, not cards. Config cannot express that: a system-bound
 * scalar is a `kpi`, `kpi` is a lazy island, and an island in the chrome paints
 * a skeleton inside the bar on every load. There is no `text` that binds a
 * system value, so the bar placement is a PLATFORM gap rather than an authoring
 * choice, and it is filed as one. A strip at the top of the panel is what
 * config does support, and it is what every sibling data surface already does.
 *
 * `success_rate` formats with `scale: '100'`, which is the combinator that
 * renders a 0–1 RATIO as a whole percent — the endpoint returns `1` for "every
 * run succeeded". Read as "the number is already a percentage, leave it alone"
 * it goes the other way and prints `1%` over a perfect record; measured, and
 * that is what it printed before this line was corrected.
 */
const runsKpiStrip = (): PageComponent =>
  ({
    type: 'container',
    element: 'div',
    props: {
      role: 'region',
      'aria-label': '$t:admin.automations.metrics.region',
      // Two-up at the narrowest width, not one-up. This strip sits ABOVE a
      // `layout: 'fill'` grid, which takes whatever height the chrome above it
      // leaves; one-up stacked all four cards and took 376px of a 665px pinned
      // column at 375, which with the filter bar, the read-window note and the
      // gaps over-subscribed the column and squeezed the grid to its 2px
      // border. The rows were then clipped inside a zero-height scroller on a
      // page that does not scroll, so the run feed was unreachable by any
      // gesture. Four short figures read fine two-up, and it hands ~172px back.
      className: 'grid grid-cols-2 gap-4 lg:grid-cols-4',
    },
    children: [
      overviewKpi('Automations', 'totals.automations', { type: 'number' }),
      overviewKpi('Runs (24h)', 'totals.runs_24h', { type: 'number' }),
      overviewKpi('Failures (24h)', 'totals.failures_24h', { type: 'number' }),
      overviewKpi('Success rate', 'totals.success_rate', {
        type: 'percentage',
        options: { scale: '100' },
      }),
    ],
  }) as PageComponent

/**
 * The History panel: the run figures, the filter bar, the run feed, its
 * read-window statement, and the detail drawer the feed opens.
 *
 * The `px-6` / `p-6` the two sections carried are GONE. They were the gutter of
 * a body stacked under a page title; the console's content column supplies its
 * own 16px now, and a second inset made the grid sit 24px further in than every
 * other grid in the console.
 */
const historyPanel = (): PageComponent =>
  tabPanel([
    runsKpiStrip(),
    filterBar(),
    runsGrid(),
    // The read-window statement, and the load-bearing half is the second
    // sentence: it names the affordance that DOES reach older runs (search
    // and the filters both query server-side over every run) and admits
    // that a narrowed result carries the same 25-row cap. Without it,
    // removing the pager would just relocate the wrong answer one
    // interaction later.
    {
      type: 'text',
      element: 'p',
      props: { className: 'text-foreground-subtle text-md' },
      content: '$t:admin.automations.runs.scope',
    } as PageComponent,
    detailDrawer(),
  ])

/**
 * The Automations panel: the catalogue, with pause and resume on each row.
 *
 * Its own `h3` is gone with the split — the tab caption above it names it, and
 * a heading directly under a trigger that says the same word is the duplication
 * the chrome bar already retired once this console.
 */
const catalogPanel = (): PageComponent => tabPanel([catalogGrid()], { scroll: true })

/**
 * Everything that needs at least one declared automation.
 *
 * `declares` EXCLUDES rather than hides, so exactly one of this and the empty
 * state below reaches the document. The predicate is the same one the retired
 * builder tested — a non-empty `app.automations` — expressed as a capability
 * rather than recomputed here.
 *
 * The GATE is on the strip, not inside it: an app declaring no automations gets
 * the empty state and NO tab bar, rather than two triggers over two empty
 * tables. A strip is an offer of two answers, and there are none to offer.
 */
const liveBody = (): PageComponent =>
  ({
    ...(tabbedBody('$t:admin.automations.tabs.region', TABS, [historyPanel(), catalogPanel()], {
      fill: true,
    }) as Record<string, unknown>),
    visibility: { declares: 'automations' },
  }) as PageComponent

/**
 * The whole-page empty state.
 *
 * With no automations declared there is nothing to catalogue AND nothing to run,
 * so one region stands in for both sections.
 */
const noAutomations = (): PageComponent =>
  ({
    ...(emptyState(
      '$t:admin.automations.empty.heading',
      '$t:admin.automations.empty.body',
      '$t:admin.automations.empty.hint'
    ) as Record<string, unknown>),
    visibility: { unlessDeclares: 'automations' },
  }) as PageComponent

export default withShell(
  {
    id: 'dashboard-data-automations',
    name: 'dashboard-data-automations',
    path: '/automations',
    meta: { title: '$t:admin.meta.automations', lang: 'en-US' },
    // `?tab=` is the address of each half. Without this block `$query.tab` is
    // left verbatim and the strip silently opens on History for every link.
    query: tabQuery(TABS),
    components: [
      pageHeading('$t:admin.automations.heading', '$t:admin.automations.blurb'),
      liveBody(),
      noAutomations(),
    ],
  } as PageConfig,
  { breadcrumb: { automations: '$t:admin.crumb.automations' }, fill: true }
) satisfies PageConfig
