/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/**
 * The shared shape of a generated module that EMBEDS files rather than inlining
 * them: one `import _xN from '…' with { type: 'file' }` per file, and a literal
 * that maps a key to each import.
 *
 * Two generators write this shape today — the in-binary manual
 * (`generate-embedded-docs.ts`) and the Agent Skills (`generate-embedded-skills.ts`)
 * — and they must agree on it byte for byte where they overlap, because
 * `build-binary.ts` reads the import lines back with a regex to prove every
 * embedded file is still on disk. Two hand-written copies of the template would
 * drift on a detail (a quote, the attribute spacing) that only that regex notices.
 *
 * Why embedded rather than inlined is each generator's own argument, and it is
 * the same one: `scripts/build/generate-css-assets.ts` harvests Tailwind
 * candidates out of every `src/**` `.ts` file, comments and string literals
 * included, so prose emitted as a string literal would flood the CSS corpus.
 * A file import costs the file's bytes in the binary and nothing in the corpus.
 */

import { fileImportSpecifier } from './posix-path'

/** The licence block every generated `.ts` file opens with. */
export const GENERATED_LICENSE = `/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */
`

/**
 * The header of a generated module: licence, lint and type opt-outs, the
 * generator that owns it, and one line of `what`.
 *
 * `@ts-nocheck` because a `with { type: 'file' }` import has no static type —
 * a typed accessor module beside each payload recovers it, in one place.
 * `what` may carry further `// ` lines; the caller writes the prefix.
 */
export const generatedModuleHeader = (generator: string, what: string): string =>
  `${GENERATED_LICENSE}
/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by ${generator} — DO NOT EDIT.
// ${what}
`

/**
 * One file-import line per path, and the identifier each path is bound to.
 *
 * @param paths - Repo-relative paths, in the order the identifiers are numbered.
 * @param options - `prefix` names the bindings (`_d0`, `_s0`); `relRoot` is the
 *   path from the generated module's directory back to the repository root.
 */
export const renderFileImports = (
  paths: readonly string[],
  options: { readonly prefix: string; readonly relRoot: string }
): { readonly imports: string; readonly identifierOf: (path: string) => string } => {
  const index = new Map(paths.map((path, at) => [path, `${options.prefix}${at}`] as const))
  return {
    imports: paths
      .map(
        (path) =>
          `import ${index.get(path) ?? ''} from '${fileImportSpecifier(options.relRoot, path)}' with { type: 'file' }`
      )
      .join('\n'),
    identifierOf: (path) => {
      const identifier = index.get(path)
      if (identifier === undefined) {
        throw new Error(`renderFileImports: no import was rendered for ${path}`)
      }
      return identifier
    },
  }
}
