/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */


import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import ts from 'typescript'

const PROJECT_ROOT = join(import.meta.dir, '..')
const TYPES_PKG = join(PROJECT_ROOT, 'packages', 'types')
const DIST_DIR = join(TYPES_PKG, 'dist')
const COMING_SOON_INTERNAL_FILE = join(PROJECT_ROOT, 'schemas/.coming-soon.internal.json')

const TYPE_EXPORTS = [
  { exported: 'AppConfig', source: 'AppConfig' },
  { exported: 'PageConfig', source: 'PageConfig' },
  { exported: 'TableConfig', source: 'TableConfig' },
  { exported: 'ComponentConfig', source: 'ComponentConfig' },
  { exported: 'ThemeConfig', source: 'ThemeConfig' },
  { exported: 'AuthConfig', source: 'AuthConfig' },
  { exported: 'LanguageConfig', source: 'LanguageConfig' },
  { exported: 'AnalyticsConfig', source: 'AnalyticsConfig' },
  { exported: 'StartOptions', source: 'StartOptions' },
  { exported: 'GenerateStaticOptions', source: 'GenerateStaticOptions' },
] as const

const COMING_SOON_JSDOC = '/** @deprecated COMING SOON — not yet implemented. */'

interface InternalComingSoonEntry {
  readonly schemaFile: string
  readonly effectSchemaNames: readonly string[]
  readonly linkedUserStories?: readonly string[]
  readonly fixmeSpecIds?: readonly string[]
  readonly reason?: string
  readonly discriminatorTag?: string
  readonly parentSchemaName?: string
  readonly leafSchemaTags?: readonly (readonly [string, string])[]
}

interface InternalComingSoonManifest {
  readonly generatedAt: string
  readonly entries: readonly InternalComingSoonEntry[]
}


function extractTypes(): string {
  console.log('\n▸ Extracting types via TypeScript Compiler API')

  const configPath = join(PROJECT_ROOT, 'tsconfig.json')
  const configFile = ts.readConfigFile(configPath, ts.sys.readFile)
  const parsedConfig = ts.parseJsonConfigFileContent(configFile.config, ts.sys, PROJECT_ROOT)

  const program = ts.createProgram(parsedConfig.fileNames, parsedConfig.options)
  const checker = program.getTypeChecker()

  const entryFile = program.getSourceFile(join(PROJECT_ROOT, 'src', 'index.ts'))
  if (!entryFile) {
    console.error('✗ Could not find src/index.ts')
    process.exit(1)
  }

  const moduleSymbol = checker.getSymbolAtLocation(entryFile)
  if (!moduleSymbol) {
    console.error('✗ Could not get module symbol for src/index.ts')
    process.exit(1)
  }

  const exports = checker.getExportsOfModule(moduleSymbol)
  const lines: string[] = []

  lines.push('// Auto-generated by scripts/build-types.ts — DO NOT EDIT')
  lines.push(
    '// This file contains zero-dependency TypeScript types for Sovrium app configuration.'
  )
  lines.push('')

  for (const { exported, source } of TYPE_EXPORTS) {
    const sym = exports.find((e) => e.getName() === source)
    if (!sym) {
      console.warn(`  ⚠ Type '${source}' not found in src/index.ts exports, skipping`)
      continue
    }

    const declaredType = checker.getDeclaredTypeOfSymbol(sym)
    let resolvedType = declaredType

    if (sym.flags & ts.SymbolFlags.TypeAlias) {
      const aliasDecl = sym.declarations?.[0]
      if (aliasDecl && ts.isTypeAliasDeclaration(aliasDecl)) {
        resolvedType = checker.getTypeAtLocation(aliasDecl)
      }
    }

    const typeString = checker.typeToString(
      resolvedType,
      entryFile,
      ts.TypeFormatFlags.NoTruncation |
        ts.TypeFormatFlags.MultilineObjectLiterals |
        ts.TypeFormatFlags.UseFullyQualifiedType |
        ts.TypeFormatFlags.InTypeAlias |
        ts.TypeFormatFlags.WriteArrayAsGenericType
    )

    lines.push(`export type ${exported} = ${typeString}`)
    lines.push('')
    console.log(`  ✓ ${exported} (${typeString.length} chars)`)
  }

  lines.push('/**')
  lines.push(' * CodeContext - typed context object passed to every runTypescript code action.')
  lines.push(' *')
  lines.push(' * Operators MUST annotate execute() as: `function execute(context: CodeContext)`.')
  lines.push(' * The TypeScriptValidator rejects any execute() with an untyped first parameter.')
  lines.push(' *')
  lines.push(' * Trigger payloads and prior step outputs are NOT directly reachable; declare')
  lines.push(' * each value via the action`s `inputData` prop using `{{trigger.data.X}}` /')
  lines.push(' * `{{steps.Y.Z}}` template references. `actions` references reusable templates')
  lines.push(' * at app.actions[] — call by name with input vars.')
  lines.push(' */')
  lines.push('export interface CodeContext {')
  lines.push('  /** Template-resolved key-value pairs declared in the action`s inputData prop */')
  lines.push('  // eslint-disable-next-line @typescript-eslint/no-explicit-any')
  lines.push('  readonly inputData: Record<string, any>')
  lines.push(
    '  /** Two-shape callable surface: actions.ref(<template>, vars) or actions.<type>.<op>(props) */'
  )
  lines.push('  // eslint-disable-next-line @typescript-eslint/no-explicit-any')
  lines.push('  readonly actions: {')
  lines.push(
    '    readonly ref: (templateName: string, vars?: Record<string, unknown>) => Promise<any>'
  )
  lines.push(
    '  } & Record<string, Record<string, (props?: Record<string, unknown>) => Promise<any>>>'
  )
  lines.push('  /** Environment variables (values redacted in logs when length >= 8) */')
  lines.push('  readonly env: Record<string, string>')
  lines.push('  /** Structured logging — info/warn/error */')
  lines.push('  readonly log: {')
  lines.push('    readonly info: (...args: ReadonlyArray<unknown>) => void')
  lines.push('    readonly warn: (...args: ReadonlyArray<unknown>) => void')
  lines.push('    readonly error: (...args: ReadonlyArray<unknown>) => void')
  lines.push('  }')
  lines.push('  /** Declared npm packages, keyed by package name (e.g. packages.lodash) */')
  lines.push('  // eslint-disable-next-line @typescript-eslint/no-explicit-any')
  lines.push('  readonly packages: Record<string, any>')
  lines.push('}')
  lines.push('')

  lines.push('/**')
  lines.push(
    ' * Identity function that provides TypeScript autocompletion for Sovrium app configs.'
  )
  lines.push(' *')
  lines.push(' * @example')
  lines.push(' * ```typescript')
  lines.push(" * import { defineConfig } from '@sovrium/types'")
  lines.push(' *')
  lines.push(' * export default defineConfig({')
  lines.push(" *   name: 'my-app',")
  lines.push(" *   description: 'My application',")
  lines.push(' * })')
  lines.push(' * ```')
  lines.push(' */')
  lines.push('export declare const defineConfig: <T extends AppConfig>(config: T) => T')
  lines.push('')

  return lines.join('\n')
}


function buildJS(): void {
  console.log('\n▸ Building minimal JS bundle')

  const jsContent = [
    '// @sovrium/types - TypeScript type definitions for Sovrium app configuration',
    '// This package provides zero-dependency types for authoring Sovrium config files.',
    '',
    '/**',
    ' * Identity function that provides TypeScript autocompletion for Sovrium app configs.',
    ' * @param {object} config - The app configuration object',
    ' * @returns {object} The same config object (identity)',
    ' */',
    'export const defineConfig = (config) => config;',
    '',
  ].join('\n')

  writeFileSync(join(DIST_DIR, 'index.js'), jsContent)
  console.log('  Built dist/index.js')
}


const SCHEMA_LITERAL_PATTERN = /Schema\.Literal\(\s*['"]([^'"]+)['"]\s*\)/g

function extractDiscriminatorLiterals(source: string): readonly string[] {
  const matches = [...source.matchAll(SCHEMA_LITERAL_PATTERN)]
  const literals = matches.map((m) => m[1]).filter((s): s is string => typeof s === 'string')
  return [...new Set(literals)]
}

function readInternalManifest(manifestPath: string): InternalComingSoonManifest | null {
  if (!existsSync(manifestPath)) {
    console.warn('[build-types] no internal coming-soon manifest found, skipping JSDoc injection.')
    return null
  }

  let raw: string
  try {
    raw = readFileSync(manifestPath, 'utf-8')
  } catch {
    console.warn(
      '[build-types] no internal coming-soon manifest readable, skipping JSDoc injection.'
    )
    return null
  }

  let parsed: InternalComingSoonManifest
  try {
    parsed = JSON.parse(raw) as InternalComingSoonManifest
  } catch {
    console.warn(
      '[build-types] no internal coming-soon manifest parseable, skipping JSDoc injection.'
    )
    return null
  }

  if (!parsed.entries || parsed.entries.length === 0) {
    console.warn(
      '[build-types] no internal coming-soon manifest entries, skipping JSDoc injection.'
    )
    return null
  }

  return parsed
}

function injectComingSoonJsDoc(dtsContent: string, manifestPath: string): string {
  const manifest = readInternalManifest(manifestPath)
  if (!manifest) return dtsContent

  const variantTags = [
    ...new Set(
      manifest.entries
        .map((e) => e.discriminatorTag)
        .filter((t): t is string => typeof t === 'string')
    ),
  ].sort()
  const leafTags = new Set<string>()
  for (const entry of manifest.entries) {
    if (entry.discriminatorTag !== undefined) continue
    if (entry.leafSchemaTags) {
      for (const [literal] of entry.leafSchemaTags) {
        leafTags.add(literal)
      }
      continue
    }
    const sourcePath = join(PROJECT_ROOT, entry.schemaFile)
    if (!existsSync(sourcePath)) continue
    let source: string
    try {
      source = readFileSync(sourcePath, 'utf-8')
    } catch {
      continue
    }
    for (const literal of extractDiscriminatorLiterals(source)) {
      leafTags.add(literal)
    }
  }
  const allLiteralTags = [...new Set([...variantTags, ...leafTags])].sort()

  let mutated = dtsContent
  let literalInjections = 0
  for (const tag of allLiteralTags) {
    const escaped = tag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const tokenPattern = new RegExp(`(?<!\\* )"${escaped}"`, 'g')
    mutated = mutated.replace(tokenPattern, (m) => {
      literalInjections++
      return `${COMING_SOON_JSDOC} ${m}`
    })
  }

  const wholeFileSchemasNotInLiterals = new Set<string>()
  const flaggedLiteralsSet = new Set(allLiteralTags)
  for (const entry of manifest.entries) {
    if (entry.discriminatorTag !== undefined) continue
    let coveredByLiterals = false
    if (entry.leafSchemaTags) {
      for (const [literal] of entry.leafSchemaTags) {
        if (flaggedLiteralsSet.has(literal)) {
          coveredByLiterals = true
          break
        }
      }
    }
    if (coveredByLiterals) continue
    for (const name of entry.effectSchemaNames) {
      wholeFileSchemasNotInLiterals.add(name)
    }
  }

  const exportNames = TYPE_EXPORTS.map((t) => t.exported)
    .slice()
    .sort()
  const typesToFlag = new Set<string>()
  for (const name of exportNames) {
    const typeBodyPattern = new RegExp(`export type ${name} = ([^\\n]+)`, 'm')
    const match = mutated.match(typeBodyPattern)
    if (!match || !match[1]) continue
    const body = match[1]
    for (const schemaName of wholeFileSchemasNotInLiterals) {
      if (body.includes(schemaName)) {
        typesToFlag.add(name)
        break
      }
    }
  }

  const sortedToFlag = [...typesToFlag].sort()
  for (const name of sortedToFlag) {
    const exportLine = `export type ${name} = `
    mutated = mutated.replace(exportLine, `${COMING_SOON_JSDOC}\n${exportLine}`)
  }

  if (literalInjections === 0 && sortedToFlag.length === 0) {
    console.log(
      '[build-types] no coming-soon discriminators surfaced in published types — no JSDoc to inject.'
    )
    return mutated
  }

  if (literalInjections > 0) {
    console.log(
      `[build-types] injected @deprecated COMING SOON JSDoc on ${literalInjections} discriminator literal occurrence(s) across ${allLiteralTags.length} unique tag(s)`
    )
  }
  if (sortedToFlag.length > 0) {
    console.log(
      `[build-types] injected @deprecated COMING SOON JSDoc on ${sortedToFlag.length} top-level type(s): ${sortedToFlag.join(', ')}`
    )
  }
  return mutated
}


function verify(dtsContent: string): void {
  console.log('\n▸ Verifying outputs')

  if (dtsContent.includes('import') && dtsContent.includes('effect')) {
    console.error('✗ Generated .d.ts contains Effect references!')
    process.exit(1)
  }

  if (!dtsContent.includes('AppConfig')) {
    console.error('✗ Missing AppConfig export!')
    process.exit(1)
  }
  if (!dtsContent.includes('defineConfig')) {
    console.error('✗ Missing defineConfig export!')
    process.exit(1)
  }
  if (!dtsContent.includes('CodeContext')) {
    console.error('✗ Missing CodeContext export!')
    process.exit(1)
  }

  const dtsSize = Buffer.byteLength(dtsContent, 'utf-8')
  const jsSize = readFileSync(join(DIST_DIR, 'index.js')).length
  console.log(`  index.d.ts: ${(dtsSize / 1024).toFixed(1)} KB`)
  console.log(`  index.js:   ${(jsSize / 1024).toFixed(1)} KB`)

  if (dtsSize < 500) {
    console.error('✗ Generated .d.ts suspiciously small — types may not have resolved correctly')
    process.exit(1)
  }
}


async function main(): Promise<void> {
  console.log('Building @sovrium/types package...')

  mkdirSync(DIST_DIR, { recursive: true })

  const rawDts = extractTypes()
  const finalDts = injectComingSoonJsDoc(rawDts, COMING_SOON_INTERNAL_FILE)
  writeFileSync(join(DIST_DIR, 'index.d.ts'), finalDts)

  buildJS()
  verify(finalDts)

  console.log('\n✓ @sovrium/types build complete — packages/types/dist/ ready')
}

await main()
