/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */


import { readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const PROJECT_ROOT = join(import.meta.dir, '..')
const OUT_FILE = join(
  PROJECT_ROOT,
  'src',
  'infrastructure',
  'assets',
  'embedded-static-assets.generated.ts'
)
const REL_ROOT = '../../..'

interface ImportLine {
  readonly varName: string
  readonly importPath: string
}

const sqlFiles = (dir: string): readonly string[] =>
  readdirSync(join(PROJECT_ROOT, dir))
    .filter((f) => f.endsWith('.sql'))
    .toSorted()


const imports: ImportLine[] = []
let counter = 0
const nextVar = (): string => `_a${counter++}`

const addImport = (relPath: string): string => {
  const varName = nextVar()
  imports.push({ varName, importPath: `${REL_ROOT}/${relPath}` })
  return varName
}

const buildDialect = (dir: string): string => {
  const journalVar = addImport(`${dir}/meta/_journal.json`)
  const entries = sqlFiles(dir).map(
    (f) => `      ${JSON.stringify(f)}: ${addImport(`${dir}/${f}`)},`
  )
  return `{
    journal: ${journalVar},
    migrations: {
${entries.join('\n')}
    },
  }`
}

const pgBlock = buildDialect('drizzle')
const sqliteBlock = buildDialect('drizzle/sqlite')

const agentEntries = readdirSync(join(PROJECT_ROOT, 'agents'))
  .filter((f) => f.endsWith('.md'))
  .toSorted()
  .map((f) => `  ${JSON.stringify(f)}: ${addImport(`agents/${f}`)},`)

const exampleEntries = readdirSync(join(PROJECT_ROOT, 'examples'))
  .filter((f) => !f.endsWith('.ts'))
  .toSorted()
  .map((f) => `  ${JSON.stringify(f)}: ${addImport(`examples/${f}`)},`)


const header = `/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by scripts/generate-embedded-static-assets.ts — DO NOT EDIT.
// Each \`with { type: 'file' }\` import embeds the file into the compiled binary
// and resolves to its on-disk path in dev/bundled mode.
`

const importBlock = imports
  .map((i) => `import ${i.varName} from '${i.importPath}' with { type: 'file' }`)
  .join('\n')

const body = `
/** Per-dialect migration files drizzle's runtime migrator reads. */
export const MIGRATION_FILES = {
  pg: ${pgBlock},
  sqlite: ${sqliteBlock},
}

/** Agent template filename → embedded path. */
export const AGENT_FILES = {
${agentEntries.join('\n')}
}

/** Example filename → embedded path. */
export const EXAMPLE_FILES = {
${exampleEntries.join('\n')}
}
`

writeFileSync(OUT_FILE, `${header}\n${importBlock}\n${body}`)
console.log(
  `✓ embedded-static-assets.generated.ts — ${imports.length} files (` +
    `${sqlFiles('drizzle').length} pg + ${sqlFiles('drizzle/sqlite').length} sqlite migrations, ` +
    `${agentEntries.length} agents, ${exampleEntries.length} examples)`
)
