/**
 * Copyright (c) 2025 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

import type { Page } from '@/domain/models/app'

/**
 * Format HTML with Prettier for professional formatting
 * Loads Prettier config and formats HTML using the HTML parser
 */
export const formatHtmlWithPrettier = async (html: string): Promise<string> => {
  const prettier = await import('prettier')
  const config = await prettier.resolveConfig(process.cwd())

  return await prettier.format(html, {
    ...config,
    parser: 'html',
  })
}

/**
 * Generate sitemap.xml content
 */
export const generateSitemapContent = (
  pages: readonly Page[],
  baseUrl: string,
  _basePath: string = '',
  languages?: readonly string[]
): string => {
  // Filter out pages with noindex AND underscore-prefixed pages
  const indexablePages = pages.filter((page) => !page.meta?.noindex && !page.path.startsWith('/_'))

  // Generate lastmod date (current date in ISO format)
  const lastmod = new Date().toISOString().split('T')[0]

  // Generate sitemap entries using immutable patterns
  const entries: readonly string[] =
    languages && languages.length > 0
      ? // Multi-language mode: Generate entries for each language
        languages.flatMap((lang) =>
          indexablePages.map((page) => {
            const priority = page.meta?.priority ?? 0.5
            const changefreq = page.meta?.changefreq ?? 'monthly'
            // Multi-language URLs: /{lang}/ or /{lang}{path}
            // Add trailing slash for root path (/) within language
            const pagePath = page.path === '/' ? '' : page.path
            const fullPath = `/${lang}${pagePath}${pagePath === '' ? '/' : ''}`

            return `  <url>
    <loc>${baseUrl}${fullPath}</loc>
    <lastmod>${lastmod}</lastmod>
    <priority>${priority.toFixed(1)}</priority>
    <changefreq>${changefreq}</changefreq>
  </url>`
          })
        )
      : // Single language mode: Generate entries without language prefix
        indexablePages.map((page) => {
          const priority = page.meta?.priority ?? 0.5
          const changefreq = page.meta?.changefreq ?? 'monthly'
          const fullPath = page.path

          return `  <url>
    <loc>${baseUrl}${fullPath}</loc>
    <lastmod>${lastmod}</lastmod>
    <priority>${priority.toFixed(1)}</priority>
    <changefreq>${changefreq}</changefreq>
  </url>`
        })

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</urlset>`
}

/**
 * Generate robots.txt content
 */
export const generateRobotsContent = (
  pages: readonly Page[],
  baseUrl: string,
  _basePath: string = '',
  includeSitemap: boolean = false
): string => {
  const baseLines = ['User-agent: *', 'Allow: /']

  // Add Disallow rules for:
  // 1. Pages with noindex or robots directives containing "noindex"
  // 2. Underscore-prefixed pages (admin/internal pages)
  const disallowedPages = pages.filter(
    (page) =>
      page.meta?.noindex === true ||
      (page.meta?.robots && page.meta.robots.includes('noindex')) ||
      page.path.startsWith('/_')
  )

  const disallowLines = disallowedPages.map((page) => `Disallow: ${page.path}`)

  const sitemapLine = includeSitemap ? [`Sitemap: ${baseUrl}/sitemap.xml`] : []
  const lines = [...baseLines, ...disallowLines, ...sitemapLine]

  return lines.join('\n')
}

/**
 * Generate client-side hydration script
 *
 * This minimal script enables React hydration on the client side.
 * For production, this would:
 * - Load React runtime
 * - Re-render components with client-side state
 * - Attach event listeners
 * - Enable interactive features
 *
 * Current implementation: Minimal placeholder for testing
 */
export const generateClientHydrationScript = (): string => {
  return `/**
 * Sovrium Client-Side Hydration Script
 * Generated by Sovrium Static Site Generator
 */

// Minimal hydration script for static sites
// This enables client-side interactivity after initial SSR
console.log('Sovrium: Client-side hydration enabled')

// Future: Load React runtime and hydrate components
// Future: Initialize client-side routing
// Future: Restore interactive state
`
}
