/**
 * Copyright (c) 2025-2026 ESSENTIAL SERVICES
 *
 * This source code is licensed under the Business Source License 1.1
 * found in the LICENSE.md file in the root directory of this source tree.
 */

/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by scripts/build/generate-embedded-static-assets.ts — DO NOT EDIT.
// Each `with { type: 'file' }` import embeds the file into the compiled binary
// and resolves to its on-disk path in dev/bundled mode.

import _a0 from '../../../drizzle/20260602205447_icy_northstar/migration.sql' with { type: 'file' }
import _a1 from '../../../drizzle/20260618211153_glossy_squadron_supreme/migration.sql' with { type: 'file' }
import _a2 from '../../../drizzle/20260621142655_bitter_calypso/migration.sql' with { type: 'file' }
import _a3 from '../../../drizzle/20260624081237_magenta_the_anarchist/migration.sql' with { type: 'file' }
import _a4 from '../../../drizzle/20260714085939_absurd_zaran/migration.sql' with { type: 'file' }
import _a5 from '../../../drizzle/20260726125042_greedy_smasher/migration.sql' with { type: 'file' }
import _a6 from '../../../drizzle/20260731213247_material_lizard/migration.sql' with { type: 'file' }
import _a7 from '../../../drizzle/20260813191315_quick_piledriver/migration.sql' with { type: 'file' }
import _a8 from '../../../drizzle/20260815190551_cloudy_sentinels/migration.sql' with { type: 'file' }
import _a9 from '../../../drizzle/20260825200817_lazy_azazel/migration.sql' with { type: 'file' }
import _a10 from '../../../drizzle/20260826074005_giant_young_avengers/migration.sql' with { type: 'file' }
import _a11 from '../../../drizzle/20260826115558_crazy_beyonder/migration.sql' with { type: 'file' }
import _a12 from '../../../drizzle/20260826195412_known_union_jack/migration.sql' with { type: 'file' }
import _a13 from '../../../drizzle/20260830063526_perpetual_karma/migration.sql' with { type: 'file' }
import _a14 from '../../../drizzle/20260916173103_careful_madripoor/migration.sql' with { type: 'file' }
import _a15 from '../../../drizzle/20260919061248_talented_hawkeye/migration.sql' with { type: 'file' }
import _a16 from '../../../drizzle/20260923154439_slimy_william_stryker/migration.sql' with { type: 'file' }
import _a17 from '../../../drizzle/20260924173608_amused_shinobi_shaw/migration.sql' with { type: 'file' }
import _a18 from '../../../drizzle/20260924174107_melodic_blacklash/migration.sql' with { type: 'file' }
import _a19 from '../../../drizzle/20260924200822_brave_miracleman/migration.sql' with { type: 'file' }
import _a20 from '../../../drizzle/20260925004046_strange_randall_flagg/migration.sql' with { type: 'file' }
import _a21 from '../../../drizzle/20260926014641_foamy_freak/migration.sql' with { type: 'file' }
import _a22 from '../../../drizzle/20260927132129_normal_triton/migration.sql' with { type: 'file' }
import _a23 from '../../../drizzle/20260930153508_premium_dreaming_celestial/migration.sql' with { type: 'file' }
import _a24 from '../../../drizzle/20261004200628_short_silvermane/migration.sql' with { type: 'file' }
import _a25 from '../../../drizzle/20261004202526_curious_jackpot/migration.sql' with { type: 'file' }
import _a26 from '../../../drizzle/sqlite/20260602205456_mute_cassandra_nova/migration.sql' with { type: 'file' }
import _a27 from '../../../drizzle/sqlite/20260618211159_famous_leper_queen/migration.sql' with { type: 'file' }
import _a28 from '../../../drizzle/sqlite/20260621142632_quick_texas_twister/migration.sql' with { type: 'file' }
import _a29 from '../../../drizzle/sqlite/20260624081244_absent_dakota_north/migration.sql' with { type: 'file' }
import _a30 from '../../../drizzle/sqlite/20260714085948_shocking_lyja/migration.sql' with { type: 'file' }
import _a31 from '../../../drizzle/sqlite/20260726125047_stormy_sersi/migration.sql' with { type: 'file' }
import _a32 from '../../../drizzle/sqlite/20260731213219_fantastic_mojo/migration.sql' with { type: 'file' }
import _a33 from '../../../drizzle/sqlite/20260813191250_closed_black_bird/migration.sql' with { type: 'file' }
import _a34 from '../../../drizzle/sqlite/20260815190523_illegal_makkari/migration.sql' with { type: 'file' }
import _a35 from '../../../drizzle/sqlite/20260825200823_ambiguous_mysterio/migration.sql' with { type: 'file' }
import _a36 from '../../../drizzle/sqlite/20260826074010_smart_the_renegades/migration.sql' with { type: 'file' }
import _a37 from '../../../drizzle/sqlite/20260826115525_careful_risque/migration.sql' with { type: 'file' }
import _a38 from '../../../drizzle/sqlite/20260826195345_amused_shriek/migration.sql' with { type: 'file' }
import _a39 from '../../../drizzle/sqlite/20260830063505_jazzy_karma/migration.sql' with { type: 'file' }
import _a40 from '../../../drizzle/sqlite/20260916173116_remarkable_mimic/migration.sql' with { type: 'file' }
import _a41 from '../../../drizzle/sqlite/20260919061234_chubby_maddog/migration.sql' with { type: 'file' }
import _a42 from '../../../drizzle/sqlite/20260923154441_magenta_maverick/migration.sql' with { type: 'file' }
import _a43 from '../../../drizzle/sqlite/20260924173610_faulty_wallop/migration.sql' with { type: 'file' }
import _a44 from '../../../drizzle/sqlite/20260924174112_heavy_giant_girl/migration.sql' with { type: 'file' }
import _a45 from '../../../drizzle/sqlite/20260924200824_nostalgic_darkhawk/migration.sql' with { type: 'file' }
import _a46 from '../../../drizzle/sqlite/20260925004033_handy_the_phantom/migration.sql' with { type: 'file' }
import _a47 from '../../../drizzle/sqlite/20260926014643_lowly_scorpion/migration.sql' with { type: 'file' }
import _a48 from '../../../drizzle/sqlite/20260927132132_stormy_lockheed/migration.sql' with { type: 'file' }
import _a49 from '../../../drizzle/sqlite/20260930153455_public_human_fly/migration.sql' with { type: 'file' }
import _a50 from '../../../drizzle/sqlite/20261004200629_next_risque/migration.sql' with { type: 'file' }
import _a51 from '../../../drizzle/sqlite/20261004202528_narrow_meteorite/migration.sql' with { type: 'file' }
import _a52 from '../../../templates/api-only/.buildpacks' with { type: 'file' }
import _a53 from '../../../templates/api-only/.env.example' with { type: 'file' }
import _a54 from '../../../templates/api-only/app.yaml' with { type: 'file' }
import _a55 from '../../../templates/api-only/CLAUDE.md' with { type: 'file' }
import _a56 from '../../../templates/api-only/config/auth.yaml' with { type: 'file' }
import _a57 from '../../../templates/api-only/config/design.yaml' with { type: 'file' }
import _a58 from '../../../templates/api-only/config/pages/home.yaml' with { type: 'file' }
import _a59 from '../../../templates/api-only/config/tables/projects.yaml' with { type: 'file' }
import _a60 from '../../../templates/api-only/config/tables/tasks.yaml' with { type: 'file' }
import _a61 from '../../../templates/api-only/LICENSE' with { type: 'file' }
import _a62 from '../../../templates/api-only/Procfile' with { type: 'file' }
import _a63 from '../../../templates/api-only/public/favicon.svg' with { type: 'file' }
import _a64 from '../../../templates/api-only/README.md' with { type: 'file' }
import _a65 from '../../../templates/api-only/scalingo.json' with { type: 'file' }
import _a66 from '../../../templates/api-only/seed/projects.yaml' with { type: 'file' }
import _a67 from '../../../templates/api-only/seed/tasks.yaml' with { type: 'file' }
import _a68 from '../../../templates/api-only/seed/users.yaml' with { type: 'file' }
import _a69 from '../../../templates/assets/.buildpacks' with { type: 'file' }
import _a70 from '../../../templates/assets/.env.example' with { type: 'file' }
import _a71 from '../../../templates/assets/app.yaml' with { type: 'file' }
import _a72 from '../../../templates/assets/CLAUDE.md' with { type: 'file' }
import _a73 from '../../../templates/assets/config/auth.yaml' with { type: 'file' }
import _a74 from '../../../templates/assets/config/design.yaml' with { type: 'file' }
import _a75 from '../../../templates/assets/config/pages/_register-asset.yaml' with { type: 'file' }
import _a76 from '../../../templates/assets/config/pages/_shell.yaml' with { type: 'file' }
import _a77 from '../../../templates/assets/config/pages/gallery.yaml' with { type: 'file' }
import _a78 from '../../../templates/assets/config/pages/lifecycle.yaml' with { type: 'file' }
import _a79 from '../../../templates/assets/config/pages/locations.yaml' with { type: 'file' }
import _a80 from '../../../templates/assets/config/pages/register.yaml' with { type: 'file' }
import _a81 from '../../../templates/assets/config/pages/sign-in.yaml' with { type: 'file' }
import _a82 from '../../../templates/assets/config/tables/asset_events.yaml' with { type: 'file' }
import _a83 from '../../../templates/assets/config/tables/assets.yaml' with { type: 'file' }
import _a84 from '../../../templates/assets/config/tables/check_outs.yaml' with { type: 'file' }
import _a85 from '../../../templates/assets/config/tables/locations.yaml' with { type: 'file' }
import _a86 from '../../../templates/assets/LICENSE' with { type: 'file' }
import _a87 from '../../../templates/assets/Procfile' with { type: 'file' }
import _a88 from '../../../templates/assets/public/.gitkeep' with { type: 'file' }
import _a89 from '../../../templates/assets/public/README.md' with { type: 'file' }
import _a90 from '../../../templates/assets/README.md' with { type: 'file' }
import _a91 from '../../../templates/assets/scalingo.json' with { type: 'file' }
import _a92 from '../../../templates/assets/seed/asset_events.yaml' with { type: 'file' }
import _a93 from '../../../templates/assets/seed/assets.yaml' with { type: 'file' }
import _a94 from '../../../templates/assets/seed/check_outs.yaml' with { type: 'file' }
import _a95 from '../../../templates/assets/seed/locations.yaml' with { type: 'file' }
import _a96 from '../../../templates/assets/seed/users.yaml' with { type: 'file' }
import _a97 from '../../../templates/automation-recipes/.buildpacks' with { type: 'file' }
import _a98 from '../../../templates/automation-recipes/.env.example' with { type: 'file' }
import _a99 from '../../../templates/automation-recipes/app.yaml' with { type: 'file' }
import _a100 from '../../../templates/automation-recipes/CLAUDE.md' with { type: 'file' }
import _a101 from '../../../templates/automation-recipes/config/auth.yaml' with { type: 'file' }
import _a102 from '../../../templates/automation-recipes/config/automations/alert-on-failure.yaml' with { type: 'file' }
import _a103 from '../../../templates/automation-recipes/config/automations/capture-lead-from-webhook.yaml' with { type: 'file' }
import _a104 from '../../../templates/automation-recipes/config/automations/daily-digest.yaml' with { type: 'file' }
import _a105 from '../../../templates/automation-recipes/config/automations/log-new-lead.yaml' with { type: 'file' }
import _a106 from '../../../templates/automation-recipes/config/design.yaml' with { type: 'file' }
import _a107 from '../../../templates/automation-recipes/config/pages/_shell.yaml' with { type: 'file' }
import _a108 from '../../../templates/automation-recipes/config/pages/activity.yaml' with { type: 'file' }
import _a109 from '../../../templates/automation-recipes/config/pages/home.yaml' with { type: 'file' }
import _a110 from '../../../templates/automation-recipes/config/pages/leads.yaml' with { type: 'file' }
import _a111 from '../../../templates/automation-recipes/config/pages/sign-in.yaml' with { type: 'file' }
import _a112 from '../../../templates/automation-recipes/config/tables/activity_log.yaml' with { type: 'file' }
import _a113 from '../../../templates/automation-recipes/config/tables/leads.yaml' with { type: 'file' }
import _a114 from '../../../templates/automation-recipes/LICENSE' with { type: 'file' }
import _a115 from '../../../templates/automation-recipes/Procfile' with { type: 'file' }
import _a116 from '../../../templates/automation-recipes/public/.gitkeep' with { type: 'file' }
import _a117 from '../../../templates/automation-recipes/public/README.md' with { type: 'file' }
import _a118 from '../../../templates/automation-recipes/README.md' with { type: 'file' }
import _a119 from '../../../templates/automation-recipes/scalingo.json' with { type: 'file' }
import _a120 from '../../../templates/automation-recipes/seed/activity_log.yaml' with { type: 'file' }
import _a121 from '../../../templates/automation-recipes/seed/leads.yaml' with { type: 'file' }
import _a122 from '../../../templates/automation-recipes/seed/users.yaml' with { type: 'file' }
import _a123 from '../../../templates/blog/.buildpacks' with { type: 'file' }
import _a124 from '../../../templates/blog/.env.example' with { type: 'file' }
import _a125 from '../../../templates/blog/app.yaml' with { type: 'file' }
import _a126 from '../../../templates/blog/CLAUDE.md' with { type: 'file' }
import _a127 from '../../../templates/blog/config/agents/blog-editor.yaml' with { type: 'file' }
import _a128 from '../../../templates/blog/config/auth.yaml' with { type: 'file' }
import _a129 from '../../../templates/blog/config/automations/publish-scheduled.yaml' with { type: 'file' }
import _a130 from '../../../templates/blog/config/automations/schedule-on-date.yaml' with { type: 'file' }
import _a131 from '../../../templates/blog/config/automations/stamp-new-comment.yaml' with { type: 'file' }
import _a132 from '../../../templates/blog/config/design.yaml' with { type: 'file' }
import _a133 from '../../../templates/blog/config/forms/comment.yaml' with { type: 'file' }
import _a134 from '../../../templates/blog/config/forms/new-post.yaml' with { type: 'file' }
import _a135 from '../../../templates/blog/config/pages/_shell.yaml' with { type: 'file' }
import _a136 from '../../../templates/blog/config/pages/_site-footer.yaml' with { type: 'file' }
import _a137 from '../../../templates/blog/config/pages/_site-header.yaml' with { type: 'file' }
import _a138 from '../../../templates/blog/config/pages/admin-ai-editor.yaml' with { type: 'file' }
import _a139 from '../../../templates/blog/config/pages/admin-authors.yaml' with { type: 'file' }
import _a140 from '../../../templates/blog/config/pages/admin-comments.yaml' with { type: 'file' }
import _a141 from '../../../templates/blog/config/pages/admin-login.yaml' with { type: 'file' }
import _a142 from '../../../templates/blog/config/pages/admin-post-edit.yaml' with { type: 'file' }
import _a143 from '../../../templates/blog/config/pages/admin-posts.yaml' with { type: 'file' }
import _a144 from '../../../templates/blog/config/pages/admin-tags.yaml' with { type: 'file' }
import _a145 from '../../../templates/blog/config/pages/essay.yaml' with { type: 'file' }
import _a146 from '../../../templates/blog/config/pages/index.yaml' with { type: 'file' }
import _a147 from '../../../templates/blog/config/pages/not-found.yaml' with { type: 'file' }
import _a148 from '../../../templates/blog/config/tables/authors.yaml' with { type: 'file' }
import _a149 from '../../../templates/blog/config/tables/comments.yaml' with { type: 'file' }
import _a150 from '../../../templates/blog/config/tables/posts.yaml' with { type: 'file' }
import _a151 from '../../../templates/blog/config/tables/tags.yaml' with { type: 'file' }
import _a152 from '../../../templates/blog/LICENSE' with { type: 'file' }
import _a153 from '../../../templates/blog/Procfile' with { type: 'file' }
import _a154 from '../../../templates/blog/public/.gitkeep' with { type: 'file' }
import _a155 from '../../../templates/blog/public/favicon.svg' with { type: 'file' }
import _a156 from '../../../templates/blog/public/README.md' with { type: 'file' }
import _a157 from '../../../templates/blog/README.md' with { type: 'file' }
import _a158 from '../../../templates/blog/scalingo.json' with { type: 'file' }
import _a159 from '../../../templates/blog/seed/assets/avatar-aoife.png' with { type: 'file' }
import _a160 from '../../../templates/blog/seed/assets/avatar-mireille.png' with { type: 'file' }
import _a161 from '../../../templates/blog/seed/assets/avatar-tomas.png' with { type: 'file' }
import _a162 from '../../../templates/blog/seed/assets/cover-backup.png' with { type: 'file' }
import _a163 from '../../../templates/blog/seed/assets/cover-config-file.png' with { type: 'file' }
import _a164 from '../../../templates/blog/seed/assets/cover-design-decisions.png' with { type: 'file' }
import _a165 from '../../../templates/blog/seed/assets/cover-first-five-minutes.png' with { type: 'file' }
import _a166 from '../../../templates/blog/seed/assets/cover-licence.png' with { type: 'file' }
import _a167 from '../../../templates/blog/seed/assets/cover-migration.png' with { type: 'file' }
import _a168 from '../../../templates/blog/seed/assets/cover-thirty-people.png' with { type: 'file' }
import _a169 from '../../../templates/blog/seed/authors.yaml' with { type: 'file' }
import _a170 from '../../../templates/blog/seed/comments.yaml' with { type: 'file' }
import _a171 from '../../../templates/blog/seed/posts.yaml' with { type: 'file' }
import _a172 from '../../../templates/blog/seed/tags.yaml' with { type: 'file' }
import _a173 from '../../../templates/blog/seed/users.yaml' with { type: 'file' }
import _a174 from '../../../templates/catalog.json' with { type: 'file' }
import _a175 from '../../../templates/company-os/.buildpacks' with { type: 'file' }
import _a176 from '../../../templates/company-os/.env.example' with { type: 'file' }
import _a177 from '../../../templates/company-os/app.yaml' with { type: 'file' }
import _a178 from '../../../templates/company-os/CLAUDE.md' with { type: 'file' }
import _a179 from '../../../templates/company-os/config/agents/ops-assistant.yaml' with { type: 'file' }
import _a180 from '../../../templates/company-os/config/auth.yaml' with { type: 'file' }
import _a181 from '../../../templates/company-os/config/automations/approve-time-off.yaml' with { type: 'file' }
import _a182 from '../../../templates/company-os/config/automations/notify-contact-on-resolved-ticket.yaml' with { type: 'file' }
import _a183 from '../../../templates/company-os/config/automations/open-project-on-won-deal.yaml' with { type: 'file' }
import _a184 from '../../../templates/company-os/config/design.yaml' with { type: 'file' }
import _a185 from '../../../templates/company-os/config/pages/_add-deal.yaml' with { type: 'file' }
import _a186 from '../../../templates/company-os/config/pages/_shell.yaml' with { type: 'file' }
import _a187 from '../../../templates/company-os/config/pages/assistant.yaml' with { type: 'file' }
import _a188 from '../../../templates/company-os/config/pages/companies.yaml' with { type: 'file' }
import _a189 from '../../../templates/company-os/config/pages/delivery.yaml' with { type: 'file' }
import _a190 from '../../../templates/company-os/config/pages/home.yaml' with { type: 'file' }
import _a191 from '../../../templates/company-os/config/pages/people.yaml' with { type: 'file' }
import _a192 from '../../../templates/company-os/config/pages/sales.yaml' with { type: 'file' }
import _a193 from '../../../templates/company-os/config/pages/sign-in.yaml' with { type: 'file' }
import _a194 from '../../../templates/company-os/config/pages/support.yaml' with { type: 'file' }
import _a195 from '../../../templates/company-os/config/tables/companies.yaml' with { type: 'file' }
import _a196 from '../../../templates/company-os/config/tables/contacts.yaml' with { type: 'file' }
import _a197 from '../../../templates/company-os/config/tables/deals.yaml' with { type: 'file' }
import _a198 from '../../../templates/company-os/config/tables/employees.yaml' with { type: 'file' }
import _a199 from '../../../templates/company-os/config/tables/project_tasks.yaml' with { type: 'file' }
import _a200 from '../../../templates/company-os/config/tables/projects.yaml' with { type: 'file' }
import _a201 from '../../../templates/company-os/config/tables/tickets.yaml' with { type: 'file' }
import _a202 from '../../../templates/company-os/config/tables/time_off_requests.yaml' with { type: 'file' }
import _a203 from '../../../templates/company-os/LICENSE' with { type: 'file' }
import _a204 from '../../../templates/company-os/Procfile' with { type: 'file' }
import _a205 from '../../../templates/company-os/public/.gitkeep' with { type: 'file' }
import _a206 from '../../../templates/company-os/public/README.md' with { type: 'file' }
import _a207 from '../../../templates/company-os/README.md' with { type: 'file' }
import _a208 from '../../../templates/company-os/scalingo.json' with { type: 'file' }
import _a209 from '../../../templates/company-os/seed/companies.yaml' with { type: 'file' }
import _a210 from '../../../templates/company-os/seed/contacts.yaml' with { type: 'file' }
import _a211 from '../../../templates/company-os/seed/deals.yaml' with { type: 'file' }
import _a212 from '../../../templates/company-os/seed/employees.yaml' with { type: 'file' }
import _a213 from '../../../templates/company-os/seed/project_tasks.yaml' with { type: 'file' }
import _a214 from '../../../templates/company-os/seed/projects.yaml' with { type: 'file' }
import _a215 from '../../../templates/company-os/seed/tickets.yaml' with { type: 'file' }
import _a216 from '../../../templates/company-os/seed/time_off_requests.yaml' with { type: 'file' }
import _a217 from '../../../templates/company-os/seed/users.yaml' with { type: 'file' }
import _a218 from '../../../templates/content-calendar/.buildpacks' with { type: 'file' }
import _a219 from '../../../templates/content-calendar/.env.example' with { type: 'file' }
import _a220 from '../../../templates/content-calendar/app.yaml' with { type: 'file' }
import _a221 from '../../../templates/content-calendar/CLAUDE.md' with { type: 'file' }
import _a222 from '../../../templates/content-calendar/config/auth.yaml' with { type: 'file' }
import _a223 from '../../../templates/content-calendar/config/automations/approve-for-scheduling.yaml' with { type: 'file' }
import _a224 from '../../../templates/content-calendar/config/automations/monday-digest.yaml' with { type: 'file' }
import _a225 from '../../../templates/content-calendar/config/automations/own-new-piece.yaml' with { type: 'file' }
import _a226 from '../../../templates/content-calendar/config/design.yaml' with { type: 'file' }
import _a227 from '../../../templates/content-calendar/config/forms/new-piece.yaml' with { type: 'file' }
import _a228 from '../../../templates/content-calendar/config/pages/_new-piece-dialog.yaml' with { type: 'file' }
import _a229 from '../../../templates/content-calendar/config/pages/_piece-detail.yaml' with { type: 'file' }
import _a230 from '../../../templates/content-calendar/config/pages/_shell.yaml' with { type: 'file' }
import _a231 from '../../../templates/content-calendar/config/pages/calendar.yaml' with { type: 'file' }
import _a232 from '../../../templates/content-calendar/config/pages/content.yaml' with { type: 'file' }
import _a233 from '../../../templates/content-calendar/config/pages/pipeline.yaml' with { type: 'file' }
import _a234 from '../../../templates/content-calendar/config/pages/sign-in.yaml' with { type: 'file' }
import _a235 from '../../../templates/content-calendar/config/tables/campaigns.yaml' with { type: 'file' }
import _a236 from '../../../templates/content-calendar/config/tables/content.yaml' with { type: 'file' }
import _a237 from '../../../templates/content-calendar/LICENSE' with { type: 'file' }
import _a238 from '../../../templates/content-calendar/Procfile' with { type: 'file' }
import _a239 from '../../../templates/content-calendar/public/.gitkeep' with { type: 'file' }
import _a240 from '../../../templates/content-calendar/public/README.md' with { type: 'file' }
import _a241 from '../../../templates/content-calendar/README.md' with { type: 'file' }
import _a242 from '../../../templates/content-calendar/scalingo.json' with { type: 'file' }
import _a243 from '../../../templates/content-calendar/seed/assets/thumbnail-install.png' with { type: 'file' }
import _a244 from '../../../templates/content-calendar/seed/campaigns.yaml' with { type: 'file' }
import _a245 from '../../../templates/content-calendar/seed/content.yaml' with { type: 'file' }
import _a246 from '../../../templates/content-calendar/seed/users.yaml' with { type: 'file' }
import _a247 from '../../../templates/crm/.buildpacks' with { type: 'file' }
import _a248 from '../../../templates/crm/.env.example' with { type: 'file' }
import _a249 from '../../../templates/crm/app.yaml' with { type: 'file' }
import _a250 from '../../../templates/crm/CLAUDE.md' with { type: 'file' }
import _a251 from '../../../templates/crm/config/agents/records-assistant.yaml' with { type: 'file' }
import _a252 from '../../../templates/crm/config/auth.yaml' with { type: 'file' }
import _a253 from '../../../templates/crm/config/automations/deal-won-notification.yaml' with { type: 'file' }
import _a254 from '../../../templates/crm/config/design.yaml' with { type: 'file' }
import _a255 from '../../../templates/crm/config/pages/_shell.yaml' with { type: 'file' }
import _a256 from '../../../templates/crm/config/pages/assistant.yaml' with { type: 'file' }
import _a257 from '../../../templates/crm/config/pages/companies.yaml' with { type: 'file' }
import _a258 from '../../../templates/crm/config/pages/contacts.yaml' with { type: 'file' }
import _a259 from '../../../templates/crm/config/pages/pipeline.yaml' with { type: 'file' }
import _a260 from '../../../templates/crm/config/pages/sign-in.yaml' with { type: 'file' }
import _a261 from '../../../templates/crm/config/pages/tasks.yaml' with { type: 'file' }
import _a262 from '../../../templates/crm/config/tables/companies.yaml' with { type: 'file' }
import _a263 from '../../../templates/crm/config/tables/contacts.yaml' with { type: 'file' }
import _a264 from '../../../templates/crm/config/tables/deals.yaml' with { type: 'file' }
import _a265 from '../../../templates/crm/config/tables/tasks.yaml' with { type: 'file' }
import _a266 from '../../../templates/crm/LICENSE' with { type: 'file' }
import _a267 from '../../../templates/crm/Procfile' with { type: 'file' }
import _a268 from '../../../templates/crm/public/.gitkeep' with { type: 'file' }
import _a269 from '../../../templates/crm/public/README.md' with { type: 'file' }
import _a270 from '../../../templates/crm/README.md' with { type: 'file' }
import _a271 from '../../../templates/crm/scalingo.json' with { type: 'file' }
import _a272 from '../../../templates/crm/seed/companies.yaml' with { type: 'file' }
import _a273 from '../../../templates/crm/seed/contacts.yaml' with { type: 'file' }
import _a274 from '../../../templates/crm/seed/deals.yaml' with { type: 'file' }
import _a275 from '../../../templates/crm/seed/tasks.yaml' with { type: 'file' }
import _a276 from '../../../templates/crm/seed/users.yaml' with { type: 'file' }
import _a277 from '../../../templates/docs-site/.buildpacks' with { type: 'file' }
import _a278 from '../../../templates/docs-site/.env.example' with { type: 'file' }
import _a279 from '../../../templates/docs-site/app.yaml' with { type: 'file' }
import _a280 from '../../../templates/docs-site/CLAUDE.md' with { type: 'file' }
import _a281 from '../../../templates/docs-site/config/design.yaml' with { type: 'file' }
import _a282 from '../../../templates/docs-site/config/pages/_brand-bar.yaml' with { type: 'file' }
import _a283 from '../../../templates/docs-site/config/pages/_docs-header.yaml' with { type: 'file' }
import _a284 from '../../../templates/docs-site/config/pages/_section-cards.yaml' with { type: 'file' }
import _a285 from '../../../templates/docs-site/config/pages/_site-footer.yaml' with { type: 'file' }
import _a286 from '../../../templates/docs-site/config/pages/_site-header.yaml' with { type: 'file' }
import _a287 from '../../../templates/docs-site/config/pages/docs.yaml' with { type: 'file' }
import _a288 from '../../../templates/docs-site/config/pages/home.yaml' with { type: 'file' }
import _a289 from '../../../templates/docs-site/config/pages/not-found.yaml' with { type: 'file' }
import _a290 from '../../../templates/docs-site/content/docs/guides/configuration.md' with { type: 'file' }
import _a291 from '../../../templates/docs-site/content/docs/guides/deployment.md' with { type: 'file' }
import _a292 from '../../../templates/docs-site/content/docs/guides/theming.md' with { type: 'file' }
import _a293 from '../../../templates/docs-site/content/docs/installation.md' with { type: 'file' }
import _a294 from '../../../templates/docs-site/content/docs/introduction.md' with { type: 'file' }
import _a295 from '../../../templates/docs-site/content/docs/quick-start.md' with { type: 'file' }
import _a296 from '../../../templates/docs-site/LICENSE' with { type: 'file' }
import _a297 from '../../../templates/docs-site/Procfile' with { type: 'file' }
import _a298 from '../../../templates/docs-site/public/.gitkeep' with { type: 'file' }
import _a299 from '../../../templates/docs-site/public/docs/files-to-pages.avif' with { type: 'file' }
import _a300 from '../../../templates/docs-site/public/README.md' with { type: 'file' }
import _a301 from '../../../templates/docs-site/README.md' with { type: 'file' }
import _a302 from '../../../templates/docs-site/scalingo.json' with { type: 'file' }
import _a303 from '../../../templates/events/.buildpacks' with { type: 'file' }
import _a304 from '../../../templates/events/.env.example' with { type: 'file' }
import _a305 from '../../../templates/events/app.yaml' with { type: 'file' }
import _a306 from '../../../templates/events/CLAUDE.md' with { type: 'file' }
import _a307 from '../../../templates/events/config/auth.yaml' with { type: 'file' }
import _a308 from '../../../templates/events/config/automations/confirm-registration.yaml' with { type: 'file' }
import _a309 from '../../../templates/events/config/automations/recount-seats.yaml' with { type: 'file' }
import _a310 from '../../../templates/events/config/design.yaml' with { type: 'file' }
import _a311 from '../../../templates/events/config/forms/join-waitlist.yaml' with { type: 'file' }
import _a312 from '../../../templates/events/config/forms/new-event.yaml' with { type: 'file' }
import _a313 from '../../../templates/events/config/forms/register.yaml' with { type: 'file' }
import _a314 from '../../../templates/events/config/pages/_shell.yaml' with { type: 'file' }
import _a315 from '../../../templates/events/config/pages/_site-footer.yaml' with { type: 'file' }
import _a316 from '../../../templates/events/config/pages/_site-header.yaml' with { type: 'file' }
import _a317 from '../../../templates/events/config/pages/calendar.yaml' with { type: 'file' }
import _a318 from '../../../templates/events/config/pages/home.yaml' with { type: 'file' }
import _a319 from '../../../templates/events/config/pages/on-the-waitlist.yaml' with { type: 'file' }
import _a320 from '../../../templates/events/config/pages/register.yaml' with { type: 'file' }
import _a321 from '../../../templates/events/config/pages/registrations.yaml' with { type: 'file' }
import _a322 from '../../../templates/events/config/pages/sign-in.yaml' with { type: 'file' }
import _a323 from '../../../templates/events/config/pages/thanks-event.yaml' with { type: 'file' }
import _a324 from '../../../templates/events/config/pages/thanks.yaml' with { type: 'file' }
import _a325 from '../../../templates/events/config/pages/waitlist.yaml' with { type: 'file' }
import _a326 from '../../../templates/events/config/tables/events.yaml' with { type: 'file' }
import _a327 from '../../../templates/events/config/tables/registrations.yaml' with { type: 'file' }
import _a328 from '../../../templates/events/LICENSE' with { type: 'file' }
import _a329 from '../../../templates/events/Procfile' with { type: 'file' }
import _a330 from '../../../templates/events/public/.gitkeep' with { type: 'file' }
import _a331 from '../../../templates/events/public/README.md' with { type: 'file' }
import _a332 from '../../../templates/events/README.md' with { type: 'file' }
import _a333 from '../../../templates/events/scalingo.json' with { type: 'file' }
import _a334 from '../../../templates/events/seed/events.yaml' with { type: 'file' }
import _a335 from '../../../templates/events/seed/registrations.yaml' with { type: 'file' }
import _a336 from '../../../templates/events/seed/users.yaml' with { type: 'file' }
import _a337 from '../../../templates/expenses/.buildpacks' with { type: 'file' }
import _a338 from '../../../templates/expenses/.env.example' with { type: 'file' }
import _a339 from '../../../templates/expenses/app.yaml' with { type: 'file' }
import _a340 from '../../../templates/expenses/CLAUDE.md' with { type: 'file' }
import _a341 from '../../../templates/expenses/config/auth.yaml' with { type: 'file' }
import _a342 from '../../../templates/expenses/config/automations/approve-expense.yaml' with { type: 'file' }
import _a343 from '../../../templates/expenses/config/automations/mark-reimbursed.yaml' with { type: 'file' }
import _a344 from '../../../templates/expenses/config/automations/reject-with-reason.yaml' with { type: 'file' }
import _a345 from '../../../templates/expenses/config/design.yaml' with { type: 'file' }
import _a346 from '../../../templates/expenses/config/forms/add-expense.yaml' with { type: 'file' }
import _a347 from '../../../templates/expenses/config/pages/_shell.yaml' with { type: 'file' }
import _a348 from '../../../templates/expenses/config/pages/home.yaml' with { type: 'file' }
import _a349 from '../../../templates/expenses/config/pages/my-expenses.yaml' with { type: 'file' }
import _a350 from '../../../templates/expenses/config/pages/reimburse.yaml' with { type: 'file' }
import _a351 from '../../../templates/expenses/config/pages/review.yaml' with { type: 'file' }
import _a352 from '../../../templates/expenses/config/pages/sign-in.yaml' with { type: 'file' }
import _a353 from '../../../templates/expenses/config/tables/expenses.yaml' with { type: 'file' }
import _a354 from '../../../templates/expenses/LICENSE' with { type: 'file' }
import _a355 from '../../../templates/expenses/Procfile' with { type: 'file' }
import _a356 from '../../../templates/expenses/public/.gitkeep' with { type: 'file' }
import _a357 from '../../../templates/expenses/public/README.md' with { type: 'file' }
import _a358 from '../../../templates/expenses/README.md' with { type: 'file' }
import _a359 from '../../../templates/expenses/scalingo.json' with { type: 'file' }
import _a360 from '../../../templates/expenses/seed/assets/breakfast.jpg' with { type: 'file' }
import _a361 from '../../../templates/expenses/seed/assets/coffee.jpg' with { type: 'file' }
import _a362 from '../../../templates/expenses/seed/assets/desk.jpg' with { type: 'file' }
import _a363 from '../../../templates/expenses/seed/assets/dinner-lyon.jpg' with { type: 'file' }
import _a364 from '../../../templates/expenses/seed/assets/flights-ber.pdf' with { type: 'file' }
import _a365 from '../../../templates/expenses/seed/assets/headset.pdf' with { type: 'file' }
import _a366 from '../../../templates/expenses/seed/assets/hotel-ber.pdf' with { type: 'file' }
import _a367 from '../../../templates/expenses/seed/assets/invoice-seats.pdf' with { type: 'file' }
import _a368 from '../../../templates/expenses/seed/assets/lunch.jpg' with { type: 'file' }
import _a369 from '../../../templates/expenses/seed/assets/monitor.pdf' with { type: 'file' }
import _a370 from '../../../templates/expenses/seed/assets/pm.pdf' with { type: 'file' }
import _a371 from '../../../templates/expenses/seed/assets/rail.pdf' with { type: 'file' }
import _a372 from '../../../templates/expenses/seed/assets/saas-annual.pdf' with { type: 'file' }
import _a373 from '../../../templates/expenses/seed/assets/tablet.pdf' with { type: 'file' }
import _a374 from '../../../templates/expenses/seed/assets/ticket.pdf' with { type: 'file' }
import _a375 from '../../../templates/expenses/seed/assets/transfer.jpg' with { type: 'file' }
import _a376 from '../../../templates/expenses/seed/assets/upgrade.pdf' with { type: 'file' }
import _a377 from '../../../templates/expenses/seed/expenses.yaml' with { type: 'file' }
import _a378 from '../../../templates/expenses/seed/users.yaml' with { type: 'file' }
import _a379 from '../../../templates/hello-world/.buildpacks' with { type: 'file' }
import _a380 from '../../../templates/hello-world/.env.example' with { type: 'file' }
import _a381 from '../../../templates/hello-world/app.yaml' with { type: 'file' }
import _a382 from '../../../templates/hello-world/CLAUDE.md' with { type: 'file' }
import _a383 from '../../../templates/hello-world/LICENSE' with { type: 'file' }
import _a384 from '../../../templates/hello-world/Procfile' with { type: 'file' }
import _a385 from '../../../templates/hello-world/public/.gitkeep' with { type: 'file' }
import _a386 from '../../../templates/hello-world/public/README.md' with { type: 'file' }
import _a387 from '../../../templates/hello-world/README.md' with { type: 'file' }
import _a388 from '../../../templates/hello-world/scalingo.json' with { type: 'file' }
import _a389 from '../../../templates/helpdesk/.buildpacks' with { type: 'file' }
import _a390 from '../../../templates/helpdesk/.env.example' with { type: 'file' }
import _a391 from '../../../templates/helpdesk/app.yaml' with { type: 'file' }
import _a392 from '../../../templates/helpdesk/CLAUDE.md' with { type: 'file' }
import _a393 from '../../../templates/helpdesk/config/auth.yaml' with { type: 'file' }
import _a394 from '../../../templates/helpdesk/config/automations/when-a-ticket-arrives.yaml' with { type: 'file' }
import _a395 from '../../../templates/helpdesk/config/automations/when-resolved.yaml' with { type: 'file' }
import _a396 from '../../../templates/helpdesk/config/design.yaml' with { type: 'file' }
import _a397 from '../../../templates/helpdesk/config/forms/contact-support.yaml' with { type: 'file' }
import _a398 from '../../../templates/helpdesk/config/forms/rate-answer.yaml' with { type: 'file' }
import _a399 from '../../../templates/helpdesk/config/pages/_shell.yaml' with { type: 'file' }
import _a400 from '../../../templates/helpdesk/config/pages/_site-footer.yaml' with { type: 'file' }
import _a401 from '../../../templates/helpdesk/config/pages/_site-header.yaml' with { type: 'file' }
import _a402 from '../../../templates/helpdesk/config/pages/home.yaml' with { type: 'file' }
import _a403 from '../../../templates/helpdesk/config/pages/rate.yaml' with { type: 'file' }
import _a404 from '../../../templates/helpdesk/config/pages/reports.yaml' with { type: 'file' }
import _a405 from '../../../templates/helpdesk/config/pages/sign-in.yaml' with { type: 'file' }
import _a406 from '../../../templates/helpdesk/config/pages/thanks.yaml' with { type: 'file' }
import _a407 from '../../../templates/helpdesk/config/pages/tickets.yaml' with { type: 'file' }
import _a408 from '../../../templates/helpdesk/config/pages/triage.yaml' with { type: 'file' }
import _a409 from '../../../templates/helpdesk/config/tables/ratings.yaml' with { type: 'file' }
import _a410 from '../../../templates/helpdesk/config/tables/ticket_replies.yaml' with { type: 'file' }
import _a411 from '../../../templates/helpdesk/config/tables/tickets.yaml' with { type: 'file' }
import _a412 from '../../../templates/helpdesk/LICENSE' with { type: 'file' }
import _a413 from '../../../templates/helpdesk/Procfile' with { type: 'file' }
import _a414 from '../../../templates/helpdesk/public/.gitkeep' with { type: 'file' }
import _a415 from '../../../templates/helpdesk/public/README.md' with { type: 'file' }
import _a416 from '../../../templates/helpdesk/README.md' with { type: 'file' }
import _a417 from '../../../templates/helpdesk/scalingo.json' with { type: 'file' }
import _a418 from '../../../templates/helpdesk/seed/ratings.yaml' with { type: 'file' }
import _a419 from '../../../templates/helpdesk/seed/ticket_replies.yaml' with { type: 'file' }
import _a420 from '../../../templates/helpdesk/seed/tickets.yaml' with { type: 'file' }
import _a421 from '../../../templates/helpdesk/seed/users.yaml' with { type: 'file' }
import _a422 from '../../../templates/intranet/.buildpacks' with { type: 'file' }
import _a423 from '../../../templates/intranet/.env.example' with { type: 'file' }
import _a424 from '../../../templates/intranet/app.yaml' with { type: 'file' }
import _a425 from '../../../templates/intranet/CLAUDE.md' with { type: 'file' }
import _a426 from '../../../templates/intranet/config/auth.yaml' with { type: 'file' }
import _a427 from '../../../templates/intranet/config/automations/sign-new-announcement.yaml' with { type: 'file' }
import _a428 from '../../../templates/intranet/config/design.yaml' with { type: 'file' }
import _a429 from '../../../templates/intranet/config/forms/publish-announcement.yaml' with { type: 'file' }
import _a430 from '../../../templates/intranet/config/pages/_post-card.yaml' with { type: 'file' }
import _a431 from '../../../templates/intranet/config/pages/_post-drawer.yaml' with { type: 'file' }
import _a432 from '../../../templates/intranet/config/pages/_shell.yaml' with { type: 'file' }
import _a433 from '../../../templates/intranet/config/pages/_site-footer.yaml' with { type: 'file' }
import _a434 from '../../../templates/intranet/config/pages/_site-header.yaml' with { type: 'file' }
import _a435 from '../../../templates/intranet/config/pages/home.yaml' with { type: 'file' }
import _a436 from '../../../templates/intranet/config/pages/news.yaml' with { type: 'file' }
import _a437 from '../../../templates/intranet/config/pages/people.yaml' with { type: 'file' }
import _a438 from '../../../templates/intranet/config/pages/portal.yaml' with { type: 'file' }
import _a439 from '../../../templates/intranet/config/pages/publish.yaml' with { type: 'file' }
import _a440 from '../../../templates/intranet/config/pages/resources.yaml' with { type: 'file' }
import _a441 from '../../../templates/intranet/config/pages/sign-in-password.yaml' with { type: 'file' }
import _a442 from '../../../templates/intranet/config/pages/sign-in.yaml' with { type: 'file' }
import _a443 from '../../../templates/intranet/config/tables/acknowledgements.yaml' with { type: 'file' }
import _a444 from '../../../templates/intranet/config/tables/company.yaml' with { type: 'file' }
import _a445 from '../../../templates/intranet/config/tables/events.yaml' with { type: 'file' }
import _a446 from '../../../templates/intranet/config/tables/members.yaml' with { type: 'file' }
import _a447 from '../../../templates/intranet/config/tables/posts.yaml' with { type: 'file' }
import _a448 from '../../../templates/intranet/config/tables/resources.yaml' with { type: 'file' }
import _a449 from '../../../templates/intranet/LICENSE' with { type: 'file' }
import _a450 from '../../../templates/intranet/Procfile' with { type: 'file' }
import _a451 from '../../../templates/intranet/public/.gitkeep' with { type: 'file' }
import _a452 from '../../../templates/intranet/public/README.md' with { type: 'file' }
import _a453 from '../../../templates/intranet/README.md' with { type: 'file' }
import _a454 from '../../../templates/intranet/scalingo.json' with { type: 'file' }
import _a455 from '../../../templates/intranet/seed/acknowledgements.yaml' with { type: 'file' }
import _a456 from '../../../templates/intranet/seed/company.yaml' with { type: 'file' }
import _a457 from '../../../templates/intranet/seed/events.yaml' with { type: 'file' }
import _a458 from '../../../templates/intranet/seed/members.yaml' with { type: 'file' }
import _a459 from '../../../templates/intranet/seed/posts.yaml' with { type: 'file' }
import _a460 from '../../../templates/intranet/seed/resources.yaml' with { type: 'file' }
import _a461 from '../../../templates/intranet/seed/users.yaml' with { type: 'file' }
import _a462 from '../../../templates/inventory/.buildpacks' with { type: 'file' }
import _a463 from '../../../templates/inventory/.env.example' with { type: 'file' }
import _a464 from '../../../templates/inventory/app.yaml' with { type: 'file' }
import _a465 from '../../../templates/inventory/CLAUDE.md' with { type: 'file' }
import _a466 from '../../../templates/inventory/config/agents/catalog-assistant.yaml' with { type: 'file' }
import _a467 from '../../../templates/inventory/config/auth.yaml' with { type: 'file' }
import _a468 from '../../../templates/inventory/config/design.yaml' with { type: 'file' }
import _a469 from '../../../templates/inventory/config/pages/_add-order.yaml' with { type: 'file' }
import _a470 from '../../../templates/inventory/config/pages/_add-product.yaml' with { type: 'file' }
import _a471 from '../../../templates/inventory/config/pages/_product-columns.yaml' with { type: 'file' }
import _a472 from '../../../templates/inventory/config/pages/_record-movement.yaml' with { type: 'file' }
import _a473 from '../../../templates/inventory/config/pages/_shell.yaml' with { type: 'file' }
import _a474 from '../../../templates/inventory/config/pages/assistant.yaml' with { type: 'file' }
import _a475 from '../../../templates/inventory/config/pages/orders.yaml' with { type: 'file' }
import _a476 from '../../../templates/inventory/config/pages/products.yaml' with { type: 'file' }
import _a477 from '../../../templates/inventory/config/pages/sign-in.yaml' with { type: 'file' }
import _a478 from '../../../templates/inventory/config/pages/stock.yaml' with { type: 'file' }
import _a479 from '../../../templates/inventory/config/pages/suppliers.yaml' with { type: 'file' }
import _a480 from '../../../templates/inventory/config/tables/orders.yaml' with { type: 'file' }
import _a481 from '../../../templates/inventory/config/tables/products.yaml' with { type: 'file' }
import _a482 from '../../../templates/inventory/config/tables/purchase_orders.yaml' with { type: 'file' }
import _a483 from '../../../templates/inventory/config/tables/stock_movements.yaml' with { type: 'file' }
import _a484 from '../../../templates/inventory/config/tables/suppliers.yaml' with { type: 'file' }
import _a485 from '../../../templates/inventory/config/tables/warehouses.yaml' with { type: 'file' }
import _a486 from '../../../templates/inventory/LICENSE' with { type: 'file' }
import _a487 from '../../../templates/inventory/Procfile' with { type: 'file' }
import _a488 from '../../../templates/inventory/public/.gitkeep' with { type: 'file' }
import _a489 from '../../../templates/inventory/public/README.md' with { type: 'file' }
import _a490 from '../../../templates/inventory/README.md' with { type: 'file' }
import _a491 from '../../../templates/inventory/scalingo.json' with { type: 'file' }
import _a492 from '../../../templates/inventory/seed/orders.yaml' with { type: 'file' }
import _a493 from '../../../templates/inventory/seed/products.yaml' with { type: 'file' }
import _a494 from '../../../templates/inventory/seed/purchase_orders.yaml' with { type: 'file' }
import _a495 from '../../../templates/inventory/seed/stock_movements.yaml' with { type: 'file' }
import _a496 from '../../../templates/inventory/seed/suppliers.yaml' with { type: 'file' }
import _a497 from '../../../templates/inventory/seed/users.yaml' with { type: 'file' }
import _a498 from '../../../templates/inventory/seed/warehouses.yaml' with { type: 'file' }
import _a499 from '../../../templates/knowledge-base/.buildpacks' with { type: 'file' }
import _a500 from '../../../templates/knowledge-base/.env.example' with { type: 'file' }
import _a501 from '../../../templates/knowledge-base/app.yaml' with { type: 'file' }
import _a502 from '../../../templates/knowledge-base/CLAUDE.md' with { type: 'file' }
import _a503 from '../../../templates/knowledge-base/config/agents/handbook-assistant.yaml' with { type: 'file' }
import _a504 from '../../../templates/knowledge-base/config/auth.yaml' with { type: 'file' }
import _a505 from '../../../templates/knowledge-base/config/design.yaml' with { type: 'file' }
import _a506 from '../../../templates/knowledge-base/config/pages/_kb-header.yaml' with { type: 'file' }
import _a507 from '../../../templates/knowledge-base/config/pages/_managers-nav.yaml' with { type: 'file' }
import _a508 from '../../../templates/knowledge-base/config/pages/_site-footer.yaml' with { type: 'file' }
import _a509 from '../../../templates/knowledge-base/config/pages/_site-header.yaml' with { type: 'file' }
import _a510 from '../../../templates/knowledge-base/config/pages/assistant.yaml' with { type: 'file' }
import _a511 from '../../../templates/knowledge-base/config/pages/home.yaml' with { type: 'file' }
import _a512 from '../../../templates/knowledge-base/config/pages/kb-managers.yaml' with { type: 'file' }
import _a513 from '../../../templates/knowledge-base/config/pages/kb.yaml' with { type: 'file' }
import _a514 from '../../../templates/knowledge-base/config/pages/sign-in.yaml' with { type: 'file' }
import _a515 from '../../../templates/knowledge-base/content/kb/getting-started/first-week.md' with { type: 'file' }
import _a516 from '../../../templates/knowledge-base/content/kb/getting-started/welcome.md' with { type: 'file' }
import _a517 from '../../../templates/knowledge-base/content/kb/it/laptop.md' with { type: 'file' }
import _a518 from '../../../templates/knowledge-base/content/kb/policies/expense-policy.md' with { type: 'file' }
import _a519 from '../../../templates/knowledge-base/content/kb/policies/security-policy.md' with { type: 'file' }
import _a520 from '../../../templates/knowledge-base/content/kb/start.md' with { type: 'file' }
import _a521 from '../../../templates/knowledge-base/content/kb-managers/hiring.md' with { type: 'file' }
import _a522 from '../../../templates/knowledge-base/content/kb-managers/pay-reviews.md' with { type: 'file' }
import _a523 from '../../../templates/knowledge-base/LICENSE' with { type: 'file' }
import _a524 from '../../../templates/knowledge-base/Procfile' with { type: 'file' }
import _a525 from '../../../templates/knowledge-base/public/.gitkeep' with { type: 'file' }
import _a526 from '../../../templates/knowledge-base/public/handbook/laptop-setup.avif' with { type: 'file' }
import _a527 from '../../../templates/knowledge-base/public/README.md' with { type: 'file' }
import _a528 from '../../../templates/knowledge-base/README.md' with { type: 'file' }
import _a529 from '../../../templates/knowledge-base/scalingo.json' with { type: 'file' }
import _a530 from '../../../templates/knowledge-base/seed/users.yaml' with { type: 'file' }
import _a531 from '../../../templates/landing-page/.buildpacks' with { type: 'file' }
import _a532 from '../../../templates/landing-page/.env.example' with { type: 'file' }
import _a533 from '../../../templates/landing-page/app.yaml' with { type: 'file' }
import _a534 from '../../../templates/landing-page/CLAUDE.md' with { type: 'file' }
import _a535 from '../../../templates/landing-page/config/auth.yaml' with { type: 'file' }
import _a536 from '../../../templates/landing-page/config/components/feature-card.yaml' with { type: 'file' }
import _a537 from '../../../templates/landing-page/config/components/language-switcher.yaml' with { type: 'file' }
import _a538 from '../../../templates/landing-page/config/components/step-card.yaml' with { type: 'file' }
import _a539 from '../../../templates/landing-page/config/design.yaml' with { type: 'file' }
import _a540 from '../../../templates/landing-page/config/forms/demo-request.yaml' with { type: 'file' }
import _a541 from '../../../templates/landing-page/config/languages.yaml' with { type: 'file' }
import _a542 from '../../../templates/landing-page/config/pages/_body.yaml' with { type: 'file' }
import _a543 from '../../../templates/landing-page/config/pages/_demo.yaml' with { type: 'file' }
import _a544 from '../../../templates/landing-page/config/pages/_hero.yaml' with { type: 'file' }
import _a545 from '../../../templates/landing-page/config/pages/_site-footer.yaml' with { type: 'file' }
import _a546 from '../../../templates/landing-page/config/pages/_site-header.yaml' with { type: 'file' }
import _a547 from '../../../templates/landing-page/config/pages/home.yaml' with { type: 'file' }
import _a548 from '../../../templates/landing-page/config/tables/demo-requests.yaml' with { type: 'file' }
import _a549 from '../../../templates/landing-page/LICENSE' with { type: 'file' }
import _a550 from '../../../templates/landing-page/Procfile' with { type: 'file' }
import _a551 from '../../../templates/landing-page/public/.gitkeep' with { type: 'file' }
import _a552 from '../../../templates/landing-page/public/favicon.svg' with { type: 'file' }
import _a553 from '../../../templates/landing-page/public/og-en.png' with { type: 'file' }
import _a554 from '../../../templates/landing-page/public/og-fr.png' with { type: 'file' }
import _a555 from '../../../templates/landing-page/public/README.md' with { type: 'file' }
import _a556 from '../../../templates/landing-page/README.md' with { type: 'file' }
import _a557 from '../../../templates/landing-page/scalingo.json' with { type: 'file' }
import _a558 from '../../../templates/mcp-server/.buildpacks' with { type: 'file' }
import _a559 from '../../../templates/mcp-server/.env.example' with { type: 'file' }
import _a560 from '../../../templates/mcp-server/app.yaml' with { type: 'file' }
import _a561 from '../../../templates/mcp-server/CLAUDE.md' with { type: 'file' }
import _a562 from '../../../templates/mcp-server/config/auth.yaml' with { type: 'file' }
import _a563 from '../../../templates/mcp-server/config/design.yaml' with { type: 'file' }
import _a564 from '../../../templates/mcp-server/config/pages/home.yaml' with { type: 'file' }
import _a565 from '../../../templates/mcp-server/config/tables/documents.yaml' with { type: 'file' }
import _a566 from '../../../templates/mcp-server/config/tables/tags.yaml' with { type: 'file' }
import _a567 from '../../../templates/mcp-server/LICENSE' with { type: 'file' }
import _a568 from '../../../templates/mcp-server/Procfile' with { type: 'file' }
import _a569 from '../../../templates/mcp-server/public/favicon.svg' with { type: 'file' }
import _a570 from '../../../templates/mcp-server/README.md' with { type: 'file' }
import _a571 from '../../../templates/mcp-server/scalingo.json' with { type: 'file' }
import _a572 from '../../../templates/mcp-server/seed/documents.yaml' with { type: 'file' }
import _a573 from '../../../templates/mcp-server/seed/tags.yaml' with { type: 'file' }
import _a574 from '../../../templates/mcp-server/seed/users.yaml' with { type: 'file' }
import _a575 from '../../../templates/people/.buildpacks' with { type: 'file' }
import _a576 from '../../../templates/people/.env.example' with { type: 'file' }
import _a577 from '../../../templates/people/app.yaml' with { type: 'file' }
import _a578 from '../../../templates/people/CLAUDE.md' with { type: 'file' }
import _a579 from '../../../templates/people/config/auth.yaml' with { type: 'file' }
import _a580 from '../../../templates/people/config/automations/approve-time-off.yaml' with { type: 'file' }
import _a581 from '../../../templates/people/config/design.yaml' with { type: 'file' }
import _a582 from '../../../templates/people/config/pages/_shell.yaml' with { type: 'file' }
import _a583 from '../../../templates/people/config/pages/directory.yaml' with { type: 'file' }
import _a584 from '../../../templates/people/config/pages/overview.yaml' with { type: 'file' }
import _a585 from '../../../templates/people/config/pages/requests.yaml' with { type: 'file' }
import _a586 from '../../../templates/people/config/pages/sign-in.yaml' with { type: 'file' }
import _a587 from '../../../templates/people/config/pages/time-off.yaml' with { type: 'file' }
import _a588 from '../../../templates/people/config/tables/employees.yaml' with { type: 'file' }
import _a589 from '../../../templates/people/config/tables/time_off_requests.yaml' with { type: 'file' }
import _a590 from '../../../templates/people/LICENSE' with { type: 'file' }
import _a591 from '../../../templates/people/Procfile' with { type: 'file' }
import _a592 from '../../../templates/people/public/.gitkeep' with { type: 'file' }
import _a593 from '../../../templates/people/public/README.md' with { type: 'file' }
import _a594 from '../../../templates/people/README.md' with { type: 'file' }
import _a595 from '../../../templates/people/scalingo.json' with { type: 'file' }
import _a596 from '../../../templates/people/seed/employees.yaml' with { type: 'file' }
import _a597 from '../../../templates/people/seed/time_off_requests.yaml' with { type: 'file' }
import _a598 from '../../../templates/people/seed/users.yaml' with { type: 'file' }
import _a599 from '../../../templates/projects/.buildpacks' with { type: 'file' }
import _a600 from '../../../templates/projects/.env.example' with { type: 'file' }
import _a601 from '../../../templates/projects/app.yaml' with { type: 'file' }
import _a602 from '../../../templates/projects/CLAUDE.md' with { type: 'file' }
import _a603 from '../../../templates/projects/config/auth.yaml' with { type: 'file' }
import _a604 from '../../../templates/projects/config/automations/notify-assignee-on-blocked.yaml' with { type: 'file' }
import _a605 from '../../../templates/projects/config/design.yaml' with { type: 'file' }
import _a606 from '../../../templates/projects/config/pages/_add-task.yaml' with { type: 'file' }
import _a607 from '../../../templates/projects/config/pages/_shell.yaml' with { type: 'file' }
import _a608 from '../../../templates/projects/config/pages/board.yaml' with { type: 'file' }
import _a609 from '../../../templates/projects/config/pages/calendar.yaml' with { type: 'file' }
import _a610 from '../../../templates/projects/config/pages/dashboard.yaml' with { type: 'file' }
import _a611 from '../../../templates/projects/config/pages/sign-in.yaml' with { type: 'file' }
import _a612 from '../../../templates/projects/config/pages/timeline.yaml' with { type: 'file' }
import _a613 from '../../../templates/projects/config/tables/projects.yaml' with { type: 'file' }
import _a614 from '../../../templates/projects/config/tables/tasks.yaml' with { type: 'file' }
import _a615 from '../../../templates/projects/LICENSE' with { type: 'file' }
import _a616 from '../../../templates/projects/Procfile' with { type: 'file' }
import _a617 from '../../../templates/projects/public/.gitkeep' with { type: 'file' }
import _a618 from '../../../templates/projects/public/README.md' with { type: 'file' }
import _a619 from '../../../templates/projects/README.md' with { type: 'file' }
import _a620 from '../../../templates/projects/scalingo.json' with { type: 'file' }
import _a621 from '../../../templates/projects/seed/projects.yaml' with { type: 'file' }
import _a622 from '../../../templates/projects/seed/tasks.yaml' with { type: 'file' }
import _a623 from '../../../templates/projects/seed/users.yaml' with { type: 'file' }
import _a624 from '../../../templates/README.md' with { type: 'file' }
import _a625 from '../../../src/admin/assets/samples/sample-chime.mp3' with { type: 'file' }
import _a626 from '../../../src/admin/assets/samples/sample-motion.webm' with { type: 'file' }
import _a627 from '../../../src/admin/assets/samples/sample-still.avif' with { type: 'file' }
import _a628 from '../../../assets/logo/academy/mark-dark-outline.svg' with { type: 'file' }
import _a629 from '../../../assets/logo/academy/mark-light-outline.svg' with { type: 'file' }
import _a630 from '../../../assets/logo/cloud/mark-dark-outline.svg' with { type: 'file' }
import _a631 from '../../../assets/logo/cloud/mark-light-outline.svg' with { type: 'file' }
import _a632 from '../../../assets/logo/partner/mark-dark-outline.svg' with { type: 'file' }
import _a633 from '../../../assets/logo/partner/mark-light-outline.svg' with { type: 'file' }
import _a634 from '../../../assets/logo/sovrium/mark-dark-outline.svg' with { type: 'file' }
import _a635 from '../../../assets/logo/sovrium/mark-light-outline.svg' with { type: 'file' }

/** Per-dialect migration folder name → embedded `migration.sql` path. */
export const MIGRATION_FILES = {
  pg: {
    migrations: {
      "20260602205447_icy_northstar": _a0,
      "20260618211153_glossy_squadron_supreme": _a1,
      "20260621142655_bitter_calypso": _a2,
      "20260624081237_magenta_the_anarchist": _a3,
      "20260714085939_absurd_zaran": _a4,
      "20260726125042_greedy_smasher": _a5,
      "20260731213247_material_lizard": _a6,
      "20260813191315_quick_piledriver": _a7,
      "20260815190551_cloudy_sentinels": _a8,
      "20260825200817_lazy_azazel": _a9,
      "20260826074005_giant_young_avengers": _a10,
      "20260826115558_crazy_beyonder": _a11,
      "20260826195412_known_union_jack": _a12,
      "20260830063526_perpetual_karma": _a13,
      "20260916173103_careful_madripoor": _a14,
      "20260919061248_talented_hawkeye": _a15,
      "20260923154439_slimy_william_stryker": _a16,
      "20260924173608_amused_shinobi_shaw": _a17,
      "20260924174107_melodic_blacklash": _a18,
      "20260924200822_brave_miracleman": _a19,
      "20260925004046_strange_randall_flagg": _a20,
      "20260926014641_foamy_freak": _a21,
      "20260927132129_normal_triton": _a22,
      "20260930153508_premium_dreaming_celestial": _a23,
      "20261004200628_short_silvermane": _a24,
      "20261004202526_curious_jackpot": _a25,
    },
  },
  sqlite: {
    migrations: {
      "20260602205456_mute_cassandra_nova": _a26,
      "20260618211159_famous_leper_queen": _a27,
      "20260621142632_quick_texas_twister": _a28,
      "20260624081244_absent_dakota_north": _a29,
      "20260714085948_shocking_lyja": _a30,
      "20260726125047_stormy_sersi": _a31,
      "20260731213219_fantastic_mojo": _a32,
      "20260813191250_closed_black_bird": _a33,
      "20260815190523_illegal_makkari": _a34,
      "20260825200823_ambiguous_mysterio": _a35,
      "20260826074010_smart_the_renegades": _a36,
      "20260826115525_careful_risque": _a37,
      "20260826195345_amused_shriek": _a38,
      "20260830063505_jazzy_karma": _a39,
      "20260916173116_remarkable_mimic": _a40,
      "20260919061234_chubby_maddog": _a41,
      "20260923154441_magenta_maverick": _a42,
      "20260924173610_faulty_wallop": _a43,
      "20260924174112_heavy_giant_girl": _a44,
      "20260924200824_nostalgic_darkhawk": _a45,
      "20260925004033_handy_the_phantom": _a46,
      "20260926014643_lowly_scorpion": _a47,
      "20260927132132_stormy_lockheed": _a48,
      "20260930153455_public_human_fly": _a49,
      "20261004200629_next_risque": _a50,
      "20261004202528_narrow_meteorite": _a51,
    },
  },
}

/** Example filename → embedded path. */
export const TEMPLATE_FILES = {
  "api-only/.buildpacks": _a52,
  "api-only/.env.example": _a53,
  "api-only/app.yaml": _a54,
  "api-only/CLAUDE.md": _a55,
  "api-only/config/auth.yaml": _a56,
  "api-only/config/design.yaml": _a57,
  "api-only/config/pages/home.yaml": _a58,
  "api-only/config/tables/projects.yaml": _a59,
  "api-only/config/tables/tasks.yaml": _a60,
  "api-only/LICENSE": _a61,
  "api-only/Procfile": _a62,
  "api-only/public/favicon.svg": _a63,
  "api-only/README.md": _a64,
  "api-only/scalingo.json": _a65,
  "api-only/seed/projects.yaml": _a66,
  "api-only/seed/tasks.yaml": _a67,
  "api-only/seed/users.yaml": _a68,
  "assets/.buildpacks": _a69,
  "assets/.env.example": _a70,
  "assets/app.yaml": _a71,
  "assets/CLAUDE.md": _a72,
  "assets/config/auth.yaml": _a73,
  "assets/config/design.yaml": _a74,
  "assets/config/pages/_register-asset.yaml": _a75,
  "assets/config/pages/_shell.yaml": _a76,
  "assets/config/pages/gallery.yaml": _a77,
  "assets/config/pages/lifecycle.yaml": _a78,
  "assets/config/pages/locations.yaml": _a79,
  "assets/config/pages/register.yaml": _a80,
  "assets/config/pages/sign-in.yaml": _a81,
  "assets/config/tables/asset_events.yaml": _a82,
  "assets/config/tables/assets.yaml": _a83,
  "assets/config/tables/check_outs.yaml": _a84,
  "assets/config/tables/locations.yaml": _a85,
  "assets/LICENSE": _a86,
  "assets/Procfile": _a87,
  "assets/public/.gitkeep": _a88,
  "assets/public/README.md": _a89,
  "assets/README.md": _a90,
  "assets/scalingo.json": _a91,
  "assets/seed/asset_events.yaml": _a92,
  "assets/seed/assets.yaml": _a93,
  "assets/seed/check_outs.yaml": _a94,
  "assets/seed/locations.yaml": _a95,
  "assets/seed/users.yaml": _a96,
  "automation-recipes/.buildpacks": _a97,
  "automation-recipes/.env.example": _a98,
  "automation-recipes/app.yaml": _a99,
  "automation-recipes/CLAUDE.md": _a100,
  "automation-recipes/config/auth.yaml": _a101,
  "automation-recipes/config/automations/alert-on-failure.yaml": _a102,
  "automation-recipes/config/automations/capture-lead-from-webhook.yaml": _a103,
  "automation-recipes/config/automations/daily-digest.yaml": _a104,
  "automation-recipes/config/automations/log-new-lead.yaml": _a105,
  "automation-recipes/config/design.yaml": _a106,
  "automation-recipes/config/pages/_shell.yaml": _a107,
  "automation-recipes/config/pages/activity.yaml": _a108,
  "automation-recipes/config/pages/home.yaml": _a109,
  "automation-recipes/config/pages/leads.yaml": _a110,
  "automation-recipes/config/pages/sign-in.yaml": _a111,
  "automation-recipes/config/tables/activity_log.yaml": _a112,
  "automation-recipes/config/tables/leads.yaml": _a113,
  "automation-recipes/LICENSE": _a114,
  "automation-recipes/Procfile": _a115,
  "automation-recipes/public/.gitkeep": _a116,
  "automation-recipes/public/README.md": _a117,
  "automation-recipes/README.md": _a118,
  "automation-recipes/scalingo.json": _a119,
  "automation-recipes/seed/activity_log.yaml": _a120,
  "automation-recipes/seed/leads.yaml": _a121,
  "automation-recipes/seed/users.yaml": _a122,
  "blog/.buildpacks": _a123,
  "blog/.env.example": _a124,
  "blog/app.yaml": _a125,
  "blog/CLAUDE.md": _a126,
  "blog/config/agents/blog-editor.yaml": _a127,
  "blog/config/auth.yaml": _a128,
  "blog/config/automations/publish-scheduled.yaml": _a129,
  "blog/config/automations/schedule-on-date.yaml": _a130,
  "blog/config/automations/stamp-new-comment.yaml": _a131,
  "blog/config/design.yaml": _a132,
  "blog/config/forms/comment.yaml": _a133,
  "blog/config/forms/new-post.yaml": _a134,
  "blog/config/pages/_shell.yaml": _a135,
  "blog/config/pages/_site-footer.yaml": _a136,
  "blog/config/pages/_site-header.yaml": _a137,
  "blog/config/pages/admin-ai-editor.yaml": _a138,
  "blog/config/pages/admin-authors.yaml": _a139,
  "blog/config/pages/admin-comments.yaml": _a140,
  "blog/config/pages/admin-login.yaml": _a141,
  "blog/config/pages/admin-post-edit.yaml": _a142,
  "blog/config/pages/admin-posts.yaml": _a143,
  "blog/config/pages/admin-tags.yaml": _a144,
  "blog/config/pages/essay.yaml": _a145,
  "blog/config/pages/index.yaml": _a146,
  "blog/config/pages/not-found.yaml": _a147,
  "blog/config/tables/authors.yaml": _a148,
  "blog/config/tables/comments.yaml": _a149,
  "blog/config/tables/posts.yaml": _a150,
  "blog/config/tables/tags.yaml": _a151,
  "blog/LICENSE": _a152,
  "blog/Procfile": _a153,
  "blog/public/.gitkeep": _a154,
  "blog/public/favicon.svg": _a155,
  "blog/public/README.md": _a156,
  "blog/README.md": _a157,
  "blog/scalingo.json": _a158,
  "blog/seed/assets/avatar-aoife.png": _a159,
  "blog/seed/assets/avatar-mireille.png": _a160,
  "blog/seed/assets/avatar-tomas.png": _a161,
  "blog/seed/assets/cover-backup.png": _a162,
  "blog/seed/assets/cover-config-file.png": _a163,
  "blog/seed/assets/cover-design-decisions.png": _a164,
  "blog/seed/assets/cover-first-five-minutes.png": _a165,
  "blog/seed/assets/cover-licence.png": _a166,
  "blog/seed/assets/cover-migration.png": _a167,
  "blog/seed/assets/cover-thirty-people.png": _a168,
  "blog/seed/authors.yaml": _a169,
  "blog/seed/comments.yaml": _a170,
  "blog/seed/posts.yaml": _a171,
  "blog/seed/tags.yaml": _a172,
  "blog/seed/users.yaml": _a173,
  "catalog.json": _a174,
  "company-os/.buildpacks": _a175,
  "company-os/.env.example": _a176,
  "company-os/app.yaml": _a177,
  "company-os/CLAUDE.md": _a178,
  "company-os/config/agents/ops-assistant.yaml": _a179,
  "company-os/config/auth.yaml": _a180,
  "company-os/config/automations/approve-time-off.yaml": _a181,
  "company-os/config/automations/notify-contact-on-resolved-ticket.yaml": _a182,
  "company-os/config/automations/open-project-on-won-deal.yaml": _a183,
  "company-os/config/design.yaml": _a184,
  "company-os/config/pages/_add-deal.yaml": _a185,
  "company-os/config/pages/_shell.yaml": _a186,
  "company-os/config/pages/assistant.yaml": _a187,
  "company-os/config/pages/companies.yaml": _a188,
  "company-os/config/pages/delivery.yaml": _a189,
  "company-os/config/pages/home.yaml": _a190,
  "company-os/config/pages/people.yaml": _a191,
  "company-os/config/pages/sales.yaml": _a192,
  "company-os/config/pages/sign-in.yaml": _a193,
  "company-os/config/pages/support.yaml": _a194,
  "company-os/config/tables/companies.yaml": _a195,
  "company-os/config/tables/contacts.yaml": _a196,
  "company-os/config/tables/deals.yaml": _a197,
  "company-os/config/tables/employees.yaml": _a198,
  "company-os/config/tables/project_tasks.yaml": _a199,
  "company-os/config/tables/projects.yaml": _a200,
  "company-os/config/tables/tickets.yaml": _a201,
  "company-os/config/tables/time_off_requests.yaml": _a202,
  "company-os/LICENSE": _a203,
  "company-os/Procfile": _a204,
  "company-os/public/.gitkeep": _a205,
  "company-os/public/README.md": _a206,
  "company-os/README.md": _a207,
  "company-os/scalingo.json": _a208,
  "company-os/seed/companies.yaml": _a209,
  "company-os/seed/contacts.yaml": _a210,
  "company-os/seed/deals.yaml": _a211,
  "company-os/seed/employees.yaml": _a212,
  "company-os/seed/project_tasks.yaml": _a213,
  "company-os/seed/projects.yaml": _a214,
  "company-os/seed/tickets.yaml": _a215,
  "company-os/seed/time_off_requests.yaml": _a216,
  "company-os/seed/users.yaml": _a217,
  "content-calendar/.buildpacks": _a218,
  "content-calendar/.env.example": _a219,
  "content-calendar/app.yaml": _a220,
  "content-calendar/CLAUDE.md": _a221,
  "content-calendar/config/auth.yaml": _a222,
  "content-calendar/config/automations/approve-for-scheduling.yaml": _a223,
  "content-calendar/config/automations/monday-digest.yaml": _a224,
  "content-calendar/config/automations/own-new-piece.yaml": _a225,
  "content-calendar/config/design.yaml": _a226,
  "content-calendar/config/forms/new-piece.yaml": _a227,
  "content-calendar/config/pages/_new-piece-dialog.yaml": _a228,
  "content-calendar/config/pages/_piece-detail.yaml": _a229,
  "content-calendar/config/pages/_shell.yaml": _a230,
  "content-calendar/config/pages/calendar.yaml": _a231,
  "content-calendar/config/pages/content.yaml": _a232,
  "content-calendar/config/pages/pipeline.yaml": _a233,
  "content-calendar/config/pages/sign-in.yaml": _a234,
  "content-calendar/config/tables/campaigns.yaml": _a235,
  "content-calendar/config/tables/content.yaml": _a236,
  "content-calendar/LICENSE": _a237,
  "content-calendar/Procfile": _a238,
  "content-calendar/public/.gitkeep": _a239,
  "content-calendar/public/README.md": _a240,
  "content-calendar/README.md": _a241,
  "content-calendar/scalingo.json": _a242,
  "content-calendar/seed/assets/thumbnail-install.png": _a243,
  "content-calendar/seed/campaigns.yaml": _a244,
  "content-calendar/seed/content.yaml": _a245,
  "content-calendar/seed/users.yaml": _a246,
  "crm/.buildpacks": _a247,
  "crm/.env.example": _a248,
  "crm/app.yaml": _a249,
  "crm/CLAUDE.md": _a250,
  "crm/config/agents/records-assistant.yaml": _a251,
  "crm/config/auth.yaml": _a252,
  "crm/config/automations/deal-won-notification.yaml": _a253,
  "crm/config/design.yaml": _a254,
  "crm/config/pages/_shell.yaml": _a255,
  "crm/config/pages/assistant.yaml": _a256,
  "crm/config/pages/companies.yaml": _a257,
  "crm/config/pages/contacts.yaml": _a258,
  "crm/config/pages/pipeline.yaml": _a259,
  "crm/config/pages/sign-in.yaml": _a260,
  "crm/config/pages/tasks.yaml": _a261,
  "crm/config/tables/companies.yaml": _a262,
  "crm/config/tables/contacts.yaml": _a263,
  "crm/config/tables/deals.yaml": _a264,
  "crm/config/tables/tasks.yaml": _a265,
  "crm/LICENSE": _a266,
  "crm/Procfile": _a267,
  "crm/public/.gitkeep": _a268,
  "crm/public/README.md": _a269,
  "crm/README.md": _a270,
  "crm/scalingo.json": _a271,
  "crm/seed/companies.yaml": _a272,
  "crm/seed/contacts.yaml": _a273,
  "crm/seed/deals.yaml": _a274,
  "crm/seed/tasks.yaml": _a275,
  "crm/seed/users.yaml": _a276,
  "docs-site/.buildpacks": _a277,
  "docs-site/.env.example": _a278,
  "docs-site/app.yaml": _a279,
  "docs-site/CLAUDE.md": _a280,
  "docs-site/config/design.yaml": _a281,
  "docs-site/config/pages/_brand-bar.yaml": _a282,
  "docs-site/config/pages/_docs-header.yaml": _a283,
  "docs-site/config/pages/_section-cards.yaml": _a284,
  "docs-site/config/pages/_site-footer.yaml": _a285,
  "docs-site/config/pages/_site-header.yaml": _a286,
  "docs-site/config/pages/docs.yaml": _a287,
  "docs-site/config/pages/home.yaml": _a288,
  "docs-site/config/pages/not-found.yaml": _a289,
  "docs-site/content/docs/guides/configuration.md": _a290,
  "docs-site/content/docs/guides/deployment.md": _a291,
  "docs-site/content/docs/guides/theming.md": _a292,
  "docs-site/content/docs/installation.md": _a293,
  "docs-site/content/docs/introduction.md": _a294,
  "docs-site/content/docs/quick-start.md": _a295,
  "docs-site/LICENSE": _a296,
  "docs-site/Procfile": _a297,
  "docs-site/public/.gitkeep": _a298,
  "docs-site/public/docs/files-to-pages.avif": _a299,
  "docs-site/public/README.md": _a300,
  "docs-site/README.md": _a301,
  "docs-site/scalingo.json": _a302,
  "events/.buildpacks": _a303,
  "events/.env.example": _a304,
  "events/app.yaml": _a305,
  "events/CLAUDE.md": _a306,
  "events/config/auth.yaml": _a307,
  "events/config/automations/confirm-registration.yaml": _a308,
  "events/config/automations/recount-seats.yaml": _a309,
  "events/config/design.yaml": _a310,
  "events/config/forms/join-waitlist.yaml": _a311,
  "events/config/forms/new-event.yaml": _a312,
  "events/config/forms/register.yaml": _a313,
  "events/config/pages/_shell.yaml": _a314,
  "events/config/pages/_site-footer.yaml": _a315,
  "events/config/pages/_site-header.yaml": _a316,
  "events/config/pages/calendar.yaml": _a317,
  "events/config/pages/home.yaml": _a318,
  "events/config/pages/on-the-waitlist.yaml": _a319,
  "events/config/pages/register.yaml": _a320,
  "events/config/pages/registrations.yaml": _a321,
  "events/config/pages/sign-in.yaml": _a322,
  "events/config/pages/thanks-event.yaml": _a323,
  "events/config/pages/thanks.yaml": _a324,
  "events/config/pages/waitlist.yaml": _a325,
  "events/config/tables/events.yaml": _a326,
  "events/config/tables/registrations.yaml": _a327,
  "events/LICENSE": _a328,
  "events/Procfile": _a329,
  "events/public/.gitkeep": _a330,
  "events/public/README.md": _a331,
  "events/README.md": _a332,
  "events/scalingo.json": _a333,
  "events/seed/events.yaml": _a334,
  "events/seed/registrations.yaml": _a335,
  "events/seed/users.yaml": _a336,
  "expenses/.buildpacks": _a337,
  "expenses/.env.example": _a338,
  "expenses/app.yaml": _a339,
  "expenses/CLAUDE.md": _a340,
  "expenses/config/auth.yaml": _a341,
  "expenses/config/automations/approve-expense.yaml": _a342,
  "expenses/config/automations/mark-reimbursed.yaml": _a343,
  "expenses/config/automations/reject-with-reason.yaml": _a344,
  "expenses/config/design.yaml": _a345,
  "expenses/config/forms/add-expense.yaml": _a346,
  "expenses/config/pages/_shell.yaml": _a347,
  "expenses/config/pages/home.yaml": _a348,
  "expenses/config/pages/my-expenses.yaml": _a349,
  "expenses/config/pages/reimburse.yaml": _a350,
  "expenses/config/pages/review.yaml": _a351,
  "expenses/config/pages/sign-in.yaml": _a352,
  "expenses/config/tables/expenses.yaml": _a353,
  "expenses/LICENSE": _a354,
  "expenses/Procfile": _a355,
  "expenses/public/.gitkeep": _a356,
  "expenses/public/README.md": _a357,
  "expenses/README.md": _a358,
  "expenses/scalingo.json": _a359,
  "expenses/seed/assets/breakfast.jpg": _a360,
  "expenses/seed/assets/coffee.jpg": _a361,
  "expenses/seed/assets/desk.jpg": _a362,
  "expenses/seed/assets/dinner-lyon.jpg": _a363,
  "expenses/seed/assets/flights-ber.pdf": _a364,
  "expenses/seed/assets/headset.pdf": _a365,
  "expenses/seed/assets/hotel-ber.pdf": _a366,
  "expenses/seed/assets/invoice-seats.pdf": _a367,
  "expenses/seed/assets/lunch.jpg": _a368,
  "expenses/seed/assets/monitor.pdf": _a369,
  "expenses/seed/assets/pm.pdf": _a370,
  "expenses/seed/assets/rail.pdf": _a371,
  "expenses/seed/assets/saas-annual.pdf": _a372,
  "expenses/seed/assets/tablet.pdf": _a373,
  "expenses/seed/assets/ticket.pdf": _a374,
  "expenses/seed/assets/transfer.jpg": _a375,
  "expenses/seed/assets/upgrade.pdf": _a376,
  "expenses/seed/expenses.yaml": _a377,
  "expenses/seed/users.yaml": _a378,
  "hello-world/.buildpacks": _a379,
  "hello-world/.env.example": _a380,
  "hello-world/app.yaml": _a381,
  "hello-world/CLAUDE.md": _a382,
  "hello-world/LICENSE": _a383,
  "hello-world/Procfile": _a384,
  "hello-world/public/.gitkeep": _a385,
  "hello-world/public/README.md": _a386,
  "hello-world/README.md": _a387,
  "hello-world/scalingo.json": _a388,
  "helpdesk/.buildpacks": _a389,
  "helpdesk/.env.example": _a390,
  "helpdesk/app.yaml": _a391,
  "helpdesk/CLAUDE.md": _a392,
  "helpdesk/config/auth.yaml": _a393,
  "helpdesk/config/automations/when-a-ticket-arrives.yaml": _a394,
  "helpdesk/config/automations/when-resolved.yaml": _a395,
  "helpdesk/config/design.yaml": _a396,
  "helpdesk/config/forms/contact-support.yaml": _a397,
  "helpdesk/config/forms/rate-answer.yaml": _a398,
  "helpdesk/config/pages/_shell.yaml": _a399,
  "helpdesk/config/pages/_site-footer.yaml": _a400,
  "helpdesk/config/pages/_site-header.yaml": _a401,
  "helpdesk/config/pages/home.yaml": _a402,
  "helpdesk/config/pages/rate.yaml": _a403,
  "helpdesk/config/pages/reports.yaml": _a404,
  "helpdesk/config/pages/sign-in.yaml": _a405,
  "helpdesk/config/pages/thanks.yaml": _a406,
  "helpdesk/config/pages/tickets.yaml": _a407,
  "helpdesk/config/pages/triage.yaml": _a408,
  "helpdesk/config/tables/ratings.yaml": _a409,
  "helpdesk/config/tables/ticket_replies.yaml": _a410,
  "helpdesk/config/tables/tickets.yaml": _a411,
  "helpdesk/LICENSE": _a412,
  "helpdesk/Procfile": _a413,
  "helpdesk/public/.gitkeep": _a414,
  "helpdesk/public/README.md": _a415,
  "helpdesk/README.md": _a416,
  "helpdesk/scalingo.json": _a417,
  "helpdesk/seed/ratings.yaml": _a418,
  "helpdesk/seed/ticket_replies.yaml": _a419,
  "helpdesk/seed/tickets.yaml": _a420,
  "helpdesk/seed/users.yaml": _a421,
  "intranet/.buildpacks": _a422,
  "intranet/.env.example": _a423,
  "intranet/app.yaml": _a424,
  "intranet/CLAUDE.md": _a425,
  "intranet/config/auth.yaml": _a426,
  "intranet/config/automations/sign-new-announcement.yaml": _a427,
  "intranet/config/design.yaml": _a428,
  "intranet/config/forms/publish-announcement.yaml": _a429,
  "intranet/config/pages/_post-card.yaml": _a430,
  "intranet/config/pages/_post-drawer.yaml": _a431,
  "intranet/config/pages/_shell.yaml": _a432,
  "intranet/config/pages/_site-footer.yaml": _a433,
  "intranet/config/pages/_site-header.yaml": _a434,
  "intranet/config/pages/home.yaml": _a435,
  "intranet/config/pages/news.yaml": _a436,
  "intranet/config/pages/people.yaml": _a437,
  "intranet/config/pages/portal.yaml": _a438,
  "intranet/config/pages/publish.yaml": _a439,
  "intranet/config/pages/resources.yaml": _a440,
  "intranet/config/pages/sign-in-password.yaml": _a441,
  "intranet/config/pages/sign-in.yaml": _a442,
  "intranet/config/tables/acknowledgements.yaml": _a443,
  "intranet/config/tables/company.yaml": _a444,
  "intranet/config/tables/events.yaml": _a445,
  "intranet/config/tables/members.yaml": _a446,
  "intranet/config/tables/posts.yaml": _a447,
  "intranet/config/tables/resources.yaml": _a448,
  "intranet/LICENSE": _a449,
  "intranet/Procfile": _a450,
  "intranet/public/.gitkeep": _a451,
  "intranet/public/README.md": _a452,
  "intranet/README.md": _a453,
  "intranet/scalingo.json": _a454,
  "intranet/seed/acknowledgements.yaml": _a455,
  "intranet/seed/company.yaml": _a456,
  "intranet/seed/events.yaml": _a457,
  "intranet/seed/members.yaml": _a458,
  "intranet/seed/posts.yaml": _a459,
  "intranet/seed/resources.yaml": _a460,
  "intranet/seed/users.yaml": _a461,
  "inventory/.buildpacks": _a462,
  "inventory/.env.example": _a463,
  "inventory/app.yaml": _a464,
  "inventory/CLAUDE.md": _a465,
  "inventory/config/agents/catalog-assistant.yaml": _a466,
  "inventory/config/auth.yaml": _a467,
  "inventory/config/design.yaml": _a468,
  "inventory/config/pages/_add-order.yaml": _a469,
  "inventory/config/pages/_add-product.yaml": _a470,
  "inventory/config/pages/_product-columns.yaml": _a471,
  "inventory/config/pages/_record-movement.yaml": _a472,
  "inventory/config/pages/_shell.yaml": _a473,
  "inventory/config/pages/assistant.yaml": _a474,
  "inventory/config/pages/orders.yaml": _a475,
  "inventory/config/pages/products.yaml": _a476,
  "inventory/config/pages/sign-in.yaml": _a477,
  "inventory/config/pages/stock.yaml": _a478,
  "inventory/config/pages/suppliers.yaml": _a479,
  "inventory/config/tables/orders.yaml": _a480,
  "inventory/config/tables/products.yaml": _a481,
  "inventory/config/tables/purchase_orders.yaml": _a482,
  "inventory/config/tables/stock_movements.yaml": _a483,
  "inventory/config/tables/suppliers.yaml": _a484,
  "inventory/config/tables/warehouses.yaml": _a485,
  "inventory/LICENSE": _a486,
  "inventory/Procfile": _a487,
  "inventory/public/.gitkeep": _a488,
  "inventory/public/README.md": _a489,
  "inventory/README.md": _a490,
  "inventory/scalingo.json": _a491,
  "inventory/seed/orders.yaml": _a492,
  "inventory/seed/products.yaml": _a493,
  "inventory/seed/purchase_orders.yaml": _a494,
  "inventory/seed/stock_movements.yaml": _a495,
  "inventory/seed/suppliers.yaml": _a496,
  "inventory/seed/users.yaml": _a497,
  "inventory/seed/warehouses.yaml": _a498,
  "knowledge-base/.buildpacks": _a499,
  "knowledge-base/.env.example": _a500,
  "knowledge-base/app.yaml": _a501,
  "knowledge-base/CLAUDE.md": _a502,
  "knowledge-base/config/agents/handbook-assistant.yaml": _a503,
  "knowledge-base/config/auth.yaml": _a504,
  "knowledge-base/config/design.yaml": _a505,
  "knowledge-base/config/pages/_kb-header.yaml": _a506,
  "knowledge-base/config/pages/_managers-nav.yaml": _a507,
  "knowledge-base/config/pages/_site-footer.yaml": _a508,
  "knowledge-base/config/pages/_site-header.yaml": _a509,
  "knowledge-base/config/pages/assistant.yaml": _a510,
  "knowledge-base/config/pages/home.yaml": _a511,
  "knowledge-base/config/pages/kb-managers.yaml": _a512,
  "knowledge-base/config/pages/kb.yaml": _a513,
  "knowledge-base/config/pages/sign-in.yaml": _a514,
  "knowledge-base/content/kb/getting-started/first-week.md": _a515,
  "knowledge-base/content/kb/getting-started/welcome.md": _a516,
  "knowledge-base/content/kb/it/laptop.md": _a517,
  "knowledge-base/content/kb/policies/expense-policy.md": _a518,
  "knowledge-base/content/kb/policies/security-policy.md": _a519,
  "knowledge-base/content/kb/start.md": _a520,
  "knowledge-base/content/kb-managers/hiring.md": _a521,
  "knowledge-base/content/kb-managers/pay-reviews.md": _a522,
  "knowledge-base/LICENSE": _a523,
  "knowledge-base/Procfile": _a524,
  "knowledge-base/public/.gitkeep": _a525,
  "knowledge-base/public/handbook/laptop-setup.avif": _a526,
  "knowledge-base/public/README.md": _a527,
  "knowledge-base/README.md": _a528,
  "knowledge-base/scalingo.json": _a529,
  "knowledge-base/seed/users.yaml": _a530,
  "landing-page/.buildpacks": _a531,
  "landing-page/.env.example": _a532,
  "landing-page/app.yaml": _a533,
  "landing-page/CLAUDE.md": _a534,
  "landing-page/config/auth.yaml": _a535,
  "landing-page/config/components/feature-card.yaml": _a536,
  "landing-page/config/components/language-switcher.yaml": _a537,
  "landing-page/config/components/step-card.yaml": _a538,
  "landing-page/config/design.yaml": _a539,
  "landing-page/config/forms/demo-request.yaml": _a540,
  "landing-page/config/languages.yaml": _a541,
  "landing-page/config/pages/_body.yaml": _a542,
  "landing-page/config/pages/_demo.yaml": _a543,
  "landing-page/config/pages/_hero.yaml": _a544,
  "landing-page/config/pages/_site-footer.yaml": _a545,
  "landing-page/config/pages/_site-header.yaml": _a546,
  "landing-page/config/pages/home.yaml": _a547,
  "landing-page/config/tables/demo-requests.yaml": _a548,
  "landing-page/LICENSE": _a549,
  "landing-page/Procfile": _a550,
  "landing-page/public/.gitkeep": _a551,
  "landing-page/public/favicon.svg": _a552,
  "landing-page/public/og-en.png": _a553,
  "landing-page/public/og-fr.png": _a554,
  "landing-page/public/README.md": _a555,
  "landing-page/README.md": _a556,
  "landing-page/scalingo.json": _a557,
  "mcp-server/.buildpacks": _a558,
  "mcp-server/.env.example": _a559,
  "mcp-server/app.yaml": _a560,
  "mcp-server/CLAUDE.md": _a561,
  "mcp-server/config/auth.yaml": _a562,
  "mcp-server/config/design.yaml": _a563,
  "mcp-server/config/pages/home.yaml": _a564,
  "mcp-server/config/tables/documents.yaml": _a565,
  "mcp-server/config/tables/tags.yaml": _a566,
  "mcp-server/LICENSE": _a567,
  "mcp-server/Procfile": _a568,
  "mcp-server/public/favicon.svg": _a569,
  "mcp-server/README.md": _a570,
  "mcp-server/scalingo.json": _a571,
  "mcp-server/seed/documents.yaml": _a572,
  "mcp-server/seed/tags.yaml": _a573,
  "mcp-server/seed/users.yaml": _a574,
  "people/.buildpacks": _a575,
  "people/.env.example": _a576,
  "people/app.yaml": _a577,
  "people/CLAUDE.md": _a578,
  "people/config/auth.yaml": _a579,
  "people/config/automations/approve-time-off.yaml": _a580,
  "people/config/design.yaml": _a581,
  "people/config/pages/_shell.yaml": _a582,
  "people/config/pages/directory.yaml": _a583,
  "people/config/pages/overview.yaml": _a584,
  "people/config/pages/requests.yaml": _a585,
  "people/config/pages/sign-in.yaml": _a586,
  "people/config/pages/time-off.yaml": _a587,
  "people/config/tables/employees.yaml": _a588,
  "people/config/tables/time_off_requests.yaml": _a589,
  "people/LICENSE": _a590,
  "people/Procfile": _a591,
  "people/public/.gitkeep": _a592,
  "people/public/README.md": _a593,
  "people/README.md": _a594,
  "people/scalingo.json": _a595,
  "people/seed/employees.yaml": _a596,
  "people/seed/time_off_requests.yaml": _a597,
  "people/seed/users.yaml": _a598,
  "projects/.buildpacks": _a599,
  "projects/.env.example": _a600,
  "projects/app.yaml": _a601,
  "projects/CLAUDE.md": _a602,
  "projects/config/auth.yaml": _a603,
  "projects/config/automations/notify-assignee-on-blocked.yaml": _a604,
  "projects/config/design.yaml": _a605,
  "projects/config/pages/_add-task.yaml": _a606,
  "projects/config/pages/_shell.yaml": _a607,
  "projects/config/pages/board.yaml": _a608,
  "projects/config/pages/calendar.yaml": _a609,
  "projects/config/pages/dashboard.yaml": _a610,
  "projects/config/pages/sign-in.yaml": _a611,
  "projects/config/pages/timeline.yaml": _a612,
  "projects/config/tables/projects.yaml": _a613,
  "projects/config/tables/tasks.yaml": _a614,
  "projects/LICENSE": _a615,
  "projects/Procfile": _a616,
  "projects/public/.gitkeep": _a617,
  "projects/public/README.md": _a618,
  "projects/README.md": _a619,
  "projects/scalingo.json": _a620,
  "projects/seed/projects.yaml": _a621,
  "projects/seed/tasks.yaml": _a622,
  "projects/seed/users.yaml": _a623,
  "README.md": _a624,
}

/** Design-system console sample-media basename → embedded path. */
export const DESIGN_SYSTEM_SAMPLE_FILES = {
  "sample-chime.mp3": _a625,
  "sample-motion.webm": _a626,
  "sample-still.avif": _a627,
}

/** Brand-mark `<unit>/<file>` key → embedded path. */
export const BRAND_MARK_FILES = {
  "academy/mark-dark-outline.svg": _a628,
  "academy/mark-light-outline.svg": _a629,
  "cloud/mark-dark-outline.svg": _a630,
  "cloud/mark-light-outline.svg": _a631,
  "partner/mark-dark-outline.svg": _a632,
  "partner/mark-light-outline.svg": _a633,
  "sovrium/mark-dark-outline.svg": _a634,
  "sovrium/mark-light-outline.svg": _a635,
}
