id: 1
name: members
fields:
  - id: 1
    name: name
    type: single-line-text
    required: true
  - id: 2
    name: email
    type: email
    required: true
  - id: 3
    name: bio
    type: long-text
  - id: 4
    name: location
    type: single-line-text
  - id: 5
    name: joined_at
    type: created-at
